// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../../runner.js";

export const meta = {
  "name": "Complete Doomwood Part 3",
  "description": "This will complete the Doomwood Part 3 quest.",
  "tags": [
    "story",
    "quest",
    "doomwood",
    "complete",
    "part3",
    "0complete"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7589,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7590,
    "map": "thorngarde",
    "ids": [
      7485
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7590,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7591,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7592,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7593,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "Cured Meat",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "Bag of Grain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Jug of Water",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7594,
    "map": "thorngarde",
    "ids": [
      7486
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7595,
    "map": "thorngarde",
    "ids": [
      7487,
      7488
    ]
  },
  {
    "kind": "kill",
    "questId": 7595,
    "map": "thorngarde",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7596,
    "map": "thorngarde",
    "ids": [
      7489,
      7490,
      7491
    ]
  },
  {
    "kind": "kill",
    "questId": 7596,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7597,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7598,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7599,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "NecroDrone Slain",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7600,
    "map": "thorngarde",
    "monsters": [
      "Zyrus the BioKnight"
    ]
  },
  {
    "kind": "plan",
    "questId": 7601,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Deadtech Power Core",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Targeting Systems",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Circuitry",
        "quantity": 15
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "Zyrus the BioKnight",
        "item": "BioKnight Engine",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7589,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7590,
    "map": "thorngarde",
    "ids": [
      7485
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7590,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7591,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7592,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7593,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "Cured Meat",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "Bag of Grain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Jug of Water",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7594,
    "map": "thorngarde",
    "ids": [
      7486
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7595,
    "map": "thorngarde",
    "ids": [
      7487,
      7488
    ]
  },
  {
    "kind": "kill",
    "questId": 7595,
    "map": "thorngarde",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7596,
    "map": "thorngarde",
    "ids": [
      7489,
      7490,
      7491
    ]
  },
  {
    "kind": "kill",
    "questId": 7596,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7597,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7598,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7599,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "NecroDrone Slain",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7600,
    "map": "thorngarde",
    "monsters": [
      "Zyrus the BioKnight"
    ]
  },
  {
    "kind": "plan",
    "questId": 7601,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Deadtech Power Core",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Targeting Systems",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Circuitry",
        "quantity": 15
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "Zyrus the BioKnight",
        "item": "BioKnight Engine",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7603,
    "map": "stonewood",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7604,
    "map": "stonewood",
    "ids": [
      7510
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7604,
    "map": "stonewood",
    "monsters": [
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 7605,
    "map": "stonewood",
    "monsters": [
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7511
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7512
    ]
  },
  {
    "kind": "kill",
    "questId": 7607,
    "map": "stonewood",
    "monsters": [
      "BioKnight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7608,
    "map": "stonewood",
    "ids": [
      7513
    ]
  },
  {
    "kind": "kill",
    "questId": 7589,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7590,
    "map": "thorngarde",
    "ids": [
      7485
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7590,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7591,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7592,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7593,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "Cured Meat",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "Bag of Grain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Jug of Water",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7594,
    "map": "thorngarde",
    "ids": [
      7486
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7595,
    "map": "thorngarde",
    "ids": [
      7487,
      7488
    ]
  },
  {
    "kind": "kill",
    "questId": 7595,
    "map": "thorngarde",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7596,
    "map": "thorngarde",
    "ids": [
      7489,
      7490,
      7491
    ]
  },
  {
    "kind": "kill",
    "questId": 7596,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7597,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7598,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7599,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "NecroDrone Slain",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7600,
    "map": "thorngarde",
    "monsters": [
      "Zyrus the BioKnight"
    ]
  },
  {
    "kind": "plan",
    "questId": 7601,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Deadtech Power Core",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Targeting Systems",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Circuitry",
        "quantity": 15
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "Zyrus the BioKnight",
        "item": "BioKnight Engine",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7603,
    "map": "stonewood",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7604,
    "map": "stonewood",
    "ids": [
      7510
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7604,
    "map": "stonewood",
    "monsters": [
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 7605,
    "map": "stonewood",
    "monsters": [
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7511
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7512
    ]
  },
  {
    "kind": "kill",
    "questId": 7607,
    "map": "stonewood",
    "monsters": [
      "BioKnight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7608,
    "map": "stonewood",
    "ids": [
      7513
    ]
  },
  {
    "kind": "kill",
    "questId": 7609,
    "map": "techdungeon",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7610,
    "map": "techdungeon",
    "ids": [
      7515
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7610,
    "map": "techdungeon",
    "monsters": [
      "Rotting Rat"
    ]
  },
  {
    "kind": "plan",
    "questId": 7611,
    "actions": [
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Armor Piece",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Helm"
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Deadtech Polearm"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7612,
    "map": "techdungeon",
    "ids": [
      7514
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7613,
    "map": "techdungeon",
    "ids": [
      7516
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7614,
    "map": "techdungeon",
    "ids": [
      7517
    ]
  },
  {
    "kind": "kill",
    "questId": 7614,
    "map": "techdungeon",
    "monsters": [
      "DoomBorg Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 7615,
    "map": "techdungeon",
    "monsters": [
      "Kalron the Cryptborg"
    ]
  },
  {
    "kind": "kill",
    "questId": 7589,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7590,
    "map": "thorngarde",
    "ids": [
      7485
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7590,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7591,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7592,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7593,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "Cured Meat",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "Bag of Grain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Jug of Water",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7594,
    "map": "thorngarde",
    "ids": [
      7486
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7595,
    "map": "thorngarde",
    "ids": [
      7487,
      7488
    ]
  },
  {
    "kind": "kill",
    "questId": 7595,
    "map": "thorngarde",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7596,
    "map": "thorngarde",
    "ids": [
      7489,
      7490,
      7491
    ]
  },
  {
    "kind": "kill",
    "questId": 7596,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7597,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7598,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7599,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "NecroDrone Slain",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7600,
    "map": "thorngarde",
    "monsters": [
      "Zyrus the BioKnight"
    ]
  },
  {
    "kind": "plan",
    "questId": 7601,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Deadtech Power Core",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Targeting Systems",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Circuitry",
        "quantity": 15
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "Zyrus the BioKnight",
        "item": "BioKnight Engine",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7603,
    "map": "stonewood",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7604,
    "map": "stonewood",
    "ids": [
      7510
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7604,
    "map": "stonewood",
    "monsters": [
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 7605,
    "map": "stonewood",
    "monsters": [
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7511
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7512
    ]
  },
  {
    "kind": "kill",
    "questId": 7607,
    "map": "stonewood",
    "monsters": [
      "BioKnight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7608,
    "map": "stonewood",
    "ids": [
      7513
    ]
  },
  {
    "kind": "kill",
    "questId": 7609,
    "map": "techdungeon",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7610,
    "map": "techdungeon",
    "ids": [
      7515
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7610,
    "map": "techdungeon",
    "monsters": [
      "Rotting Rat"
    ]
  },
  {
    "kind": "plan",
    "questId": 7611,
    "actions": [
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Armor Piece",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Helm"
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Deadtech Polearm"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7612,
    "map": "techdungeon",
    "ids": [
      7514
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7613,
    "map": "techdungeon",
    "ids": [
      7516
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7614,
    "map": "techdungeon",
    "ids": [
      7517
    ]
  },
  {
    "kind": "kill",
    "questId": 7614,
    "map": "techdungeon",
    "monsters": [
      "DoomBorg Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 7615,
    "map": "techdungeon",
    "monsters": [
      "Kalron the Cryptborg"
    ]
  },
  {
    "kind": "plan",
    "questId": 7623,
    "actions": [
      {
        "kind": "mapItem",
        "map": "stonewooddeep",
        "id": 7528,
        "quantity": 1
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7624,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r2",
        "pad": "Right",
        "monster": "Asherion",
        "item": "Defeat Asherion"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7625,
    "actions": [
      {
        "kind": "mapItem",
        "map": "stonewooddeep",
        "id": 7529,
        "quantity": 1
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7626,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r2",
        "pad": "Right",
        "monster": "Doomwood Treeant",
        "item": "Sturdy Wood",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7626,
    "map": "stonewooddeep",
    "ids": [
      7530
    ],
    "quantity": 8
  },
  {
    "kind": "plan",
    "questId": 7627,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Treeant",
        "item": "Area Cleared",
        "quantity": 10
      },
      {
        "kind": "mapItem",
        "map": "stonewooddeep",
        "id": 7531,
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7628,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Left",
        "monster": "Target Dummy",
        "item": "Target Dummy Slain",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7629,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Slime",
        "item": "Slime Slain",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7630,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Slime",
        "item": "Stolen Armor",
        "quantity": 7
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7631,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r7",
        "pad": "Left",
        "monster": "CryptHacker",
        "item": "Crypthacker Slain",
        "quantity": 10
      },
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r7",
        "pad": "Left",
        "monster": "CryptHacker",
        "item": "Unidentified Clue"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7632,
    "map": "stonewooddeep",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7633,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Slime",
        "item": "Acid Ooze",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r7",
        "pad": "Right",
        "monster": "NecroDrone",
        "item": "Explosive Tech",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7634,
    "map": "stonewooddeep",
    "ids": [
      7532
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7635,
    "map": "stonewooddeep",
    "ids": [
      7533
    ]
  },
  {
    "kind": "kill",
    "questId": 7636,
    "map": "stonewooddeep",
    "monsters": [
      "Sir Kut"
    ]
  },
  {
    "kind": "kill",
    "questId": 7589,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7590,
    "map": "thorngarde",
    "ids": [
      7485
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7590,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7591,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7592,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7593,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "Cured Meat",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "Bag of Grain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Jug of Water",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7594,
    "map": "thorngarde",
    "ids": [
      7486
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7595,
    "map": "thorngarde",
    "ids": [
      7487,
      7488
    ]
  },
  {
    "kind": "kill",
    "questId": 7595,
    "map": "thorngarde",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7596,
    "map": "thorngarde",
    "ids": [
      7489,
      7490,
      7491
    ]
  },
  {
    "kind": "kill",
    "questId": 7596,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7597,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7598,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7599,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "NecroDrone Slain",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7600,
    "map": "thorngarde",
    "monsters": [
      "Zyrus the BioKnight"
    ]
  },
  {
    "kind": "plan",
    "questId": 7601,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Deadtech Power Core",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Targeting Systems",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Circuitry",
        "quantity": 15
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "Zyrus the BioKnight",
        "item": "BioKnight Engine",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7603,
    "map": "stonewood",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7604,
    "map": "stonewood",
    "ids": [
      7510
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7604,
    "map": "stonewood",
    "monsters": [
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 7605,
    "map": "stonewood",
    "monsters": [
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7511
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7512
    ]
  },
  {
    "kind": "kill",
    "questId": 7607,
    "map": "stonewood",
    "monsters": [
      "BioKnight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7608,
    "map": "stonewood",
    "ids": [
      7513
    ]
  },
  {
    "kind": "kill",
    "questId": 7609,
    "map": "techdungeon",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7610,
    "map": "techdungeon",
    "ids": [
      7515
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7610,
    "map": "techdungeon",
    "monsters": [
      "Rotting Rat"
    ]
  },
  {
    "kind": "plan",
    "questId": 7611,
    "actions": [
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Armor Piece",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Helm"
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Deadtech Polearm"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7612,
    "map": "techdungeon",
    "ids": [
      7514
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7613,
    "map": "techdungeon",
    "ids": [
      7516
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7614,
    "map": "techdungeon",
    "ids": [
      7517
    ]
  },
  {
    "kind": "kill",
    "questId": 7614,
    "map": "techdungeon",
    "monsters": [
      "DoomBorg Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 7615,
    "map": "techdungeon",
    "monsters": [
      "Kalron the Cryptborg"
    ]
  },
  {
    "kind": "plan",
    "questId": 7623,
    "actions": [
      {
        "kind": "mapItem",
        "map": "stonewooddeep",
        "id": 7528,
        "quantity": 1
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7624,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r2",
        "pad": "Right",
        "monster": "Asherion",
        "item": "Defeat Asherion"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7625,
    "actions": [
      {
        "kind": "mapItem",
        "map": "stonewooddeep",
        "id": 7529,
        "quantity": 1
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7626,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r2",
        "pad": "Right",
        "monster": "Doomwood Treeant",
        "item": "Sturdy Wood",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7626,
    "map": "stonewooddeep",
    "ids": [
      7530
    ],
    "quantity": 8
  },
  {
    "kind": "plan",
    "questId": 7627,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Treeant",
        "item": "Area Cleared",
        "quantity": 10
      },
      {
        "kind": "mapItem",
        "map": "stonewooddeep",
        "id": 7531,
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7628,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Left",
        "monster": "Target Dummy",
        "item": "Target Dummy Slain",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7629,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Slime",
        "item": "Slime Slain",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7630,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Slime",
        "item": "Stolen Armor",
        "quantity": 7
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7631,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r7",
        "pad": "Left",
        "monster": "CryptHacker",
        "item": "Crypthacker Slain",
        "quantity": 10
      },
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r7",
        "pad": "Left",
        "monster": "CryptHacker",
        "item": "Unidentified Clue"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7632,
    "map": "stonewooddeep",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7633,
    "actions": [
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r3",
        "pad": "Right",
        "monster": "Doomwood Slime",
        "item": "Acid Ooze",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "stonewooddeep",
        "cell": "r7",
        "pad": "Right",
        "monster": "NecroDrone",
        "item": "Explosive Tech",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7634,
    "map": "stonewooddeep",
    "ids": [
      7532
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7635,
    "map": "stonewooddeep",
    "ids": [
      7533
    ]
  },
  {
    "kind": "kill",
    "questId": 7636,
    "map": "stonewooddeep",
    "monsters": [
      "Sir Kut"
    ]
  },
  {
    "kind": "kill",
    "questId": 7637,
    "map": "techfortress",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7638,
    "map": "techfortress",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "kill",
    "questId": 7639,
    "map": "techfortress",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7640,
    "map": "techfortress",
    "ids": [
      7561
    ]
  },
  {
    "kind": "kill",
    "questId": 7640,
    "map": "techfortress",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7641,
    "actions": [
      {
        "kind": "hunt",
        "map": "techfortress",
        "monster": "NecroDrone",
        "item": "NecroMedals",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7642,
    "map": "techfortress",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7643,
    "map": "techfortress",
    "monsters": [
      "CPU"
    ]
  },
  {
    "kind": "kill",
    "questId": 7644,
    "map": "techfortress",
    "monsters": [
      "DoomBorg Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 7645,
    "map": "techfortress",
    "monsters": [
      "DoomBorg Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 7646,
    "map": "techfortress",
    "monsters": [
      "Vortrix"
    ]
  },
  {
    "kind": "kill",
    "questId": 7653,
    "map": "techfortress",
    "monsters": [
      "MechaVortrix"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.doomwood.part3.0complete-part3",
    category: "Story",
    map: "thorngarde",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
