// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../../runner.js";

export const meta = {
  "name": "Tech Dungeon",
  "description": "This will complete the Tech Dungeon quest.",
  "tags": [
    "story",
    "quest",
    "doomwood",
    "tech-dungeon",
    "part3",
    "3tech",
    "dungeon"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7589,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7590,
    "map": "thorngarde",
    "ids": [
      7485
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7590,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7591,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7592,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "plan",
    "questId": 7593,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "Cured Meat",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "Bag of Grain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Jug of Water",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7594,
    "map": "thorngarde",
    "ids": [
      7486
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7595,
    "map": "thorngarde",
    "ids": [
      7487,
      7488
    ]
  },
  {
    "kind": "kill",
    "questId": 7595,
    "map": "thorngarde",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7596,
    "map": "thorngarde",
    "ids": [
      7489,
      7490,
      7491
    ]
  },
  {
    "kind": "kill",
    "questId": 7596,
    "map": "thorngarde",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "kill",
    "questId": 7597,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7598,
    "map": "thorngarde",
    "monsters": [
      "CryptHacker",
      "NecroDrone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7599,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Slain",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "NecroDrone Slain",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7600,
    "map": "thorngarde",
    "monsters": [
      "Zyrus the BioKnight"
    ]
  },
  {
    "kind": "plan",
    "questId": 7601,
    "actions": [
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroDrone",
        "item": "Deadtech Power Core",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "NecroMech",
        "item": "NecroMech Targeting Systems",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "CryptHacker",
        "item": "CryptHacker Circuitry",
        "quantity": 15
      },
      {
        "kind": "hunt",
        "map": "thorngarde",
        "monster": "Zyrus the BioKnight",
        "item": "BioKnight Engine",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7603,
    "map": "stonewood",
    "monsters": [
      "NecroDrone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7604,
    "map": "stonewood",
    "ids": [
      7510
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7604,
    "map": "stonewood",
    "monsters": [
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 7605,
    "map": "stonewood",
    "monsters": [
      "NecroDrone",
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7511
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 7606,
    "map": "stonewood",
    "ids": [
      7512
    ]
  },
  {
    "kind": "kill",
    "questId": 7607,
    "map": "stonewood",
    "monsters": [
      "BioKnight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7608,
    "map": "stonewood",
    "ids": [
      7513
    ]
  },
  {
    "kind": "kill",
    "questId": 7609,
    "map": "techdungeon",
    "monsters": [
      "NecroMech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7610,
    "map": "techdungeon",
    "ids": [
      7515
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7610,
    "map": "techdungeon",
    "monsters": [
      "Rotting Rat"
    ]
  },
  {
    "kind": "plan",
    "questId": 7611,
    "actions": [
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Armor Piece",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Guard Helm"
      },
      {
        "kind": "hunt",
        "map": "techdungeon",
        "cell": "r4",
        "pad": "Left",
        "monster": "DoomBorg Guard",
        "item": "Deadtech Polearm"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7612,
    "map": "techdungeon",
    "ids": [
      7514
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7613,
    "map": "techdungeon",
    "ids": [
      7516
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7614,
    "map": "techdungeon",
    "ids": [
      7517
    ]
  },
  {
    "kind": "kill",
    "questId": 7614,
    "map": "techdungeon",
    "monsters": [
      "DoomBorg Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 7615,
    "map": "techdungeon",
    "monsters": [
      "Kalron the Cryptborg"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.doomwood.part3.3tech-dungeon",
    category: "Story",
    map: "thorngarde",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
