// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Prologue",
  "description": "This will finish the Prologue quest.",
  "tags": [
    "story",
    "quest",
    "chaos-saga",
    "13-lords-of-chaos",
    "prologue",
    "lordsof",
    "chaos",
    "01prologue"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 183,
    "map": "battleundera",
    "monsters": [
      "Skeletal Fire Mage"
    ]
  },
  {
    "kind": "plan",
    "questId": 176,
    "actions": [
      {
        "kind": "hunt",
        "map": "swordhavenundead",
        "monster": "Skeletal Soldier",
        "item": "Slain Skeletal Soldier",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 177,
    "map": "swordhavenundead",
    "monsters": [
      "Skeletal Ice Mage"
    ]
  },
  {
    "kind": "kill",
    "questId": 178,
    "map": "swordhavenundead",
    "monsters": [
      "Undead Giant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 179,
    "map": "castleundead",
    "ids": [
      38
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 180,
    "map": "castleundead",
    "monsters": [
      "Skeletal Viking"
    ]
  },
  {
    "kind": "chain",
    "questId": 195
  },
  {
    "kind": "kill",
    "questId": 196,
    "map": "chaoscrypt",
    "monsters": [
      "Chaorrupted Armor"
    ]
  },
  {
    "kind": "plan",
    "questId": 6216,
    "actions": [
      {
        "kind": "mapItem",
        "map": "prison",
        "id": 39,
        "quantity": 5
      },
      {
        "kind": "buy",
        "map": "prison",
        "shopId": 1559,
        "item": 42993
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6217,
    "map": "chaoscrypt",
    "ids": [
      5662
    ]
  },
  {
    "kind": "kill",
    "questId": 6218,
    "map": "chaoscrypt",
    "monsters": [
      "Chaorrupted Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6219,
    "map": "forestchaos",
    "monsters": [
      "Chaorrupted Bear",
      "Chaorrupted Wolf"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.lordsof-chaos.01prologue",
    category: "Story",
    map: "battleundera",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
