// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "(Troll) Khasaanda",
  "description": "This will finish the Khasaanda quest.",
  "tags": [
    "story",
    "quest",
    "chaos-saga",
    "13-lords-of-chaos",
    "troll",
    "khasaanda",
    "lordsof",
    "chaos",
    "09khasaanda"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 1226,
    "actions": [
      {
        "kind": "hunt",
        "map": "crossroads",
        "monster": "Chinchilizard",
        "item": "Scaly Skin Scrub",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "bloodtusk",
        "monster": "Trollola Plant",
        "item": "Perfumed Trollola Flower",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1226,
    "map": "bloodtusk",
    "ids": [
      523
    ]
  },
  {
    "kind": "kill",
    "questId": 1227,
    "map": "crossroads",
    "monsters": [
      "Lemurphant",
      "Koalion"
    ]
  },
  {
    "kind": "plan",
    "questId": 1228,
    "actions": [
      {
        "kind": "hunt",
        "map": "bloodtusk",
        "monster": "Crystal-Rock",
        "item": "Mountain Crystal",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "crossroads",
        "monster": "Chinchilizard",
        "item": "Liz-Leather Thongs",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "crossroads",
        "monster": "Lemurphant",
        "item": "Lemurphant Ivory",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1228,
    "map": "crossroads",
    "ids": [
      525
    ]
  },
  {
    "kind": "plan",
    "questId": 1229,
    "actions": [
      {
        "kind": "hunt",
        "map": "crossroads",
        "monster": "Lemurphant",
        "item": "Lemurphant Musk",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "bloodtusk",
        "monster": "Trollola Plant",
        "item": "Trollola Plant Resin",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "crossroads",
        "monster": "Koalion",
        "item": "Fur for Firestarting",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1229,
    "map": "crossroads",
    "ids": [
      521
    ],
    "quantity": 10
  },
  {
    "kind": "chain",
    "questId": 1230
  },
  {
    "kind": "plan",
    "questId": 1231,
    "actions": [
      {
        "kind": "hunt",
        "map": "crossroads",
        "monster": "Lemurphant",
        "item": "Lemurphant Tusks",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "crossroads",
        "monster": "Koalion",
        "item": "Koalion Claw",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "bloodtusk",
        "monster": "Crystal-Rock",
        "item": "Singing Crystals",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1231,
    "map": "crossroads",
    "ids": [
      522
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 1231,
    "map": "crossroads",
    "ids": [
      524
    ],
    "quantity": 10
  },
  {
    "kind": "plan",
    "questId": 1240,
    "actions": [
      {
        "kind": "join",
        "map": "crossroads"
      },
      {
        "kind": "join",
        "map": "crossroads"
      },
      {
        "kind": "jump",
        "cell": "CutE",
        "pad": "Left"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 1272
  },
  {
    "kind": "mapItem",
    "questId": 1274,
    "map": "ravinetemple",
    "ids": [
      553
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1275,
    "map": "ravinetemple",
    "ids": [
      554
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 1275,
    "map": "ravinetemple",
    "ids": [
      555,
      556
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 1276,
    "map": "ravinetemple",
    "monsters": [
      "Temple Guardian"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1277,
    "map": "ravinetemple",
    "ids": [
      557
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 1277,
    "map": "ravinetemple",
    "monsters": [
      "Temple Guardian"
    ]
  },
  {
    "kind": "kill",
    "questId": 1278,
    "map": "ravinetemple",
    "monsters": [
      "Temple Guardian"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1369,
    "map": "alliance",
    "ids": [
      679,
      680
    ]
  },
  {
    "kind": "kill",
    "questId": 1370,
    "map": "alliance",
    "monsters": [
      "Good Soldier",
      "Evil Soldier"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1371,
    "map": "alliance",
    "ids": [
      675
    ],
    "quantity": 10
  },
  {
    "kind": "mapItem",
    "questId": 1372,
    "map": "alliance",
    "ids": [
      676
    ]
  },
  {
    "kind": "kill",
    "questId": 1373,
    "map": "alliance",
    "monsters": [
      "Chaorrupted Evil Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 1374,
    "map": "alliance",
    "monsters": [
      "General Cynari",
      "General Tibias"
    ]
  },
  {
    "kind": "kill",
    "questId": 1419,
    "map": "ancienttemple",
    "monsters": [
      "Chaotic Vulture"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1420,
    "map": "ancienttemple",
    "ids": [
      706
    ],
    "quantity": 7
  },
  {
    "kind": "kill",
    "questId": 1420,
    "map": "ancienttemple",
    "monsters": [
      "Chaotic Vulture"
    ]
  },
  {
    "kind": "kill",
    "questId": 1421,
    "map": "ancienttemple",
    "monsters": [
      "Chaos Troll Spirit"
    ]
  },
  {
    "kind": "kill",
    "questId": 1422,
    "map": "ancienttemple",
    "monsters": [
      "Serpentress"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1423,
    "map": "ancienttemple",
    "ids": [
      707
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1451,
    "map": "orecavern",
    "ids": [
      717
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1452,
    "map": "orecavern",
    "ids": [
      719
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 1452,
    "map": "orecavern",
    "monsters": [
      "Crashroom"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1453,
    "map": "orecavern",
    "ids": [
      718
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 1454,
    "map": "orecavern",
    "monsters": [
      "Chaorrupted Evil Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 1455,
    "map": "orecavern",
    "monsters": [
      "Naga Baas"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1464,
    "map": "dreamnexus",
    "ids": [
      734,
      735,
      736,
      737
    ]
  },
  {
    "kind": "plan",
    "questId": 1465,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreamnexus",
        "monster": "Dark Wyvern",
        "item": "Wyvern Scales",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "dreamnexus",
        "monster": "Dark Wyvern",
        "item": "Wyvern Claws",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "dreamnexus",
        "monster": "Aether Serpent",
        "item": "Serpent Fangs",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "dreamnexus",
        "monster": "Aether Serpent",
        "item": "Serpent Hair",
        "quantity": 2
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1466,
    "map": "dreamnexus",
    "ids": [
      738
    ],
    "quantity": 10
  },
  {
    "kind": "mapItem",
    "questId": 1466,
    "map": "dreamnexus",
    "ids": [
      739
    ],
    "quantity": 11
  },
  {
    "kind": "kill",
    "questId": 1467,
    "map": "dreamnexus",
    "monsters": [
      "Solar Phoenix",
      "Solar Phoenix"
    ]
  },
  {
    "kind": "kill",
    "questId": 1468,
    "map": "dreamnexus",
    "monsters": [
      "Khasaanda"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.lordsof-chaos.09khasaanda-troll",
    category: "Story",
    map: "crossroads",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
