// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "(The Span) Iadoa",
  "description": "This will finish the Iadoa quest.",
  "tags": [
    "story",
    "quest",
    "chaos-saga",
    "13-lords-of-chaos",
    "the-span",
    "iadoa",
    "lordsof",
    "chaos",
    "10iadoa",
    "the",
    "span"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 2239,
    "map": "thespan",
    "ids": [
      1358,
      1359,
      1360,
      1361,
      1362,
      1363
    ]
  },
  {
    "kind": "kill",
    "questId": 2240,
    "map": "timelibrary",
    "monsters": [
      "Sneak",
      "Tog",
      "Shadowscythe"
    ]
  },
  {
    "kind": "plan",
    "questId": 2241,
    "actions": [
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Moglin Ghost",
        "item": "Necromancy in AQ Knowledge"
      },
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Undead Knight",
        "item": "Tales of Planet-Peril Page",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2241,
    "map": "timelibrary",
    "ids": [
      1365
    ],
    "quantity": 3
  },
  {
    "kind": "plan",
    "questId": 2242,
    "actions": [
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Tog",
        "item": "Elemental Orb Knowledge",
        "quantity": 8
      },
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Tog",
        "item": "\"Draconic Prophecy\" Page",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2242,
    "map": "timelibrary",
    "ids": [
      1366
    ],
    "quantity": 2
  },
  {
    "kind": "plan",
    "questId": 2243,
    "actions": [
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Shadowscythe",
        "item": "Shadowscythe Combat Strategy",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Training Globe",
        "item": "Galactic Hypertron Engines: A Primer"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2243,
    "map": "timelibrary",
    "ids": [
      1367
    ]
  },
  {
    "kind": "plan",
    "questId": 2244,
    "actions": [
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Queen's Recruit",
        "item": "The Future is Now",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Queen's Recruit",
        "item": "Past Failures Brought Us Here",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "timelibrary",
        "monster": "Queen's Knight",
        "item": "Princess Freed... but for what?",
        "quantity": 2
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2244,
    "map": "timelibrary",
    "ids": [
      1368
    ]
  },
  {
    "kind": "kill",
    "questId": 2253,
    "map": "timevoid",
    "monsters": [
      "Ephemerite"
    ]
  },
  {
    "kind": "plan",
    "questId": 2254,
    "actions": [
      {
        "kind": "hunt",
        "map": "timevoid",
        "monster": "Time-Travel Fairy",
        "item": "Exaglass",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "timevoid",
        "monster": "Time-Travel Fairy",
        "item": "Fairy Plasma",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2254,
    "map": "timevoid",
    "ids": [
      1438
    ],
    "quantity": 16
  },
  {
    "kind": "mapItem",
    "questId": 2255,
    "map": "timevoid",
    "ids": [
      1439
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 2255,
    "map": "timevoid",
    "monsters": [
      "Ephemerite",
      "Time-Travel Fairy"
    ]
  },
  {
    "kind": "kill",
    "questId": 2256,
    "map": "timevoid",
    "monsters": [
      "Time-Travel Fairy",
      "Void Phoenix"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2257,
    "map": "timevoid",
    "ids": [
      1440,
      1441,
      1442,
      1443
    ]
  },
  {
    "kind": "kill",
    "questId": 2258,
    "map": "timevoid",
    "monsters": [
      "Unending Avatar"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2376,
    "map": "aqlesson",
    "ids": [
      1467
    ]
  },
  {
    "kind": "kill",
    "questId": 2377,
    "map": "aqlesson",
    "monsters": [
      "Ninja"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2378,
    "map": "aqlesson",
    "ids": [
      1468
    ],
    "quantity": 8
  },
  {
    "kind": "mapItem",
    "questId": 2378,
    "map": "aqlesson",
    "ids": [
      1469
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2379,
    "map": "aqlesson",
    "ids": [
      1470,
      1471
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 2379,
    "map": "aqlesson",
    "monsters": [
      "Eternite Ore",
      "Water Elemental"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2380,
    "map": "aqlesson",
    "ids": [
      1473,
      1472
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 2380,
    "map": "aqlesson",
    "monsters": [
      "Ice Elemental",
      "Fire Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 2381,
    "map": "aqlesson",
    "monsters": [
      "Void Dragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 2382,
    "map": "aqlesson",
    "monsters": [
      "Firezard"
    ]
  },
  {
    "kind": "kill",
    "questId": 2383,
    "map": "aqlesson",
    "monsters": [
      "Ice Elemental"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2384,
    "map": "thespan",
    "ids": [
      1474
    ]
  },
  {
    "kind": "kill",
    "questId": 2385,
    "map": "aqlesson",
    "monsters": [
      "Akriloth"
    ]
  },
  {
    "kind": "kill",
    "questId": 2386,
    "map": "aqlesson",
    "monsters": [
      "Carnax"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2470,
    "map": "dflesson",
    "ids": [
      1549
    ],
    "quantity": 8
  },
  {
    "kind": "plan",
    "questId": 2471,
    "actions": [
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Fire Elemental",
        "item": "Slain Flame Elemental",
        "quantity": 8
      },
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Fire Elemental",
        "item": "Chaos Gemerald",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2472,
    "actions": [
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Lava Slime",
        "item": "Slain Slime",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Fire Elemental",
        "item": "Slain Elemental",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Fire Elemental",
        "item": "Blue Clue"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2473,
    "actions": [
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Tog",
        "item": "Life AND the Universe",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Agitated Orb",
        "item": "Everything",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "dflesson",
        "monster": "Agitated Orb",
        "item": "Hoopy Frood's Towel",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 2474,
    "map": "dflesson",
    "monsters": [
      "Vultragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 2475,
    "map": "dflesson",
    "monsters": [
      "Chaos Sp-Eye"
    ]
  },
  {
    "kind": "kill",
    "questId": 2476,
    "map": "dflesson",
    "monsters": [
      "Chaorrupted Evil Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 2477,
    "map": "dflesson",
    "monsters": [
      "Lava Golem",
      "Fire Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 2478,
    "map": "dflesson",
    "monsters": [
      "Chaotic Horcboar",
      "Chaotic Chicken"
    ]
  },
  {
    "kind": "kill",
    "questId": 2479,
    "map": "dflesson",
    "monsters": [
      "Fluffy the Dracolich"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2504,
    "map": "mqlesson",
    "ids": [
      1580
    ]
  },
  {
    "kind": "kill",
    "questId": 2505,
    "map": "mqlesson",
    "monsters": [
      "Asteroid"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2506,
    "map": "mqlesson",
    "ids": [
      1581
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 2507,
    "map": "mqlesson",
    "monsters": [
      "MystRaven Student"
    ]
  },
  {
    "kind": "kill",
    "questId": 2508,
    "map": "mqlesson",
    "monsters": [
      "Training Globe"
    ]
  },
  {
    "kind": "kill",
    "questId": 2509,
    "map": "mqlesson",
    "monsters": [
      "MystRaven Student"
    ]
  },
  {
    "kind": "kill",
    "questId": 2510,
    "map": "mqlesson",
    "monsters": [
      "Chaos Shadowscythe"
    ]
  },
  {
    "kind": "plan",
    "questId": 2511,
    "actions": [
      {
        "kind": "hunt",
        "map": "mqlesson",
        "monster": "Chaos Shadowscythe",
        "item": "Truth Glasses"
      },
      {
        "kind": "hunt",
        "map": "mqlesson",
        "monster": "Chaos Shadowscythe",
        "item": "Darkness Destroyed",
        "quantity": 13
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 2512,
    "map": "mqlesson",
    "monsters": [
      "Dragonoid"
    ]
  },
  {
    "kind": "kill",
    "questId": 2513,
    "map": "deepchaos",
    "monsters": [
      "Chaotic Merdrac"
    ]
  },
  {
    "kind": "kill",
    "questId": 2515,
    "map": "deepchaos",
    "monsters": [
      "Chaos Angler"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2516,
    "map": "deepchaos",
    "ids": [
      1582
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 2517,
    "map": "deepchaos",
    "monsters": [
      "Kathool"
    ]
  },
  {
    "kind": "plan",
    "questId": 2518,
    "actions": [
      {
        "kind": "hunt",
        "map": "timespace",
        "monster": "Astral Ephemerite",
        "item": "Star Death",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2519,
    "actions": [
      {
        "kind": "hunt",
        "map": "mqlesson",
        "monster": "Dragonoid",
        "item": "Dragonoid of Hours"
      },
      {
        "kind": "hunt",
        "map": "timespace",
        "monster": "Chaos Lord Iadoa",
        "item": "Iadoa Defeated"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 2520,
    "map": "ultravoid",
    "monsters": [
      "Ultra Kathool"
    ]
  },
  {
    "kind": "kill",
    "questId": 2521,
    "map": "ultravoid",
    "monsters": [
      "Ultra Iadoa"
    ]
  },
  {
    "kind": "kill",
    "questId": 2388,
    "map": "ultracarnax",
    "monsters": [
      "Ultra-Carnax"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.lordsof-chaos.10iadoa-the-span",
    category: "Story",
    map: "thespan",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
