// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "(Darkblood) Lionfang",
  "description": "This will finish the Lionfang quest.",
  "tags": [
    "story",
    "quest",
    "chaos-saga",
    "13-lords-of-chaos",
    "darkblood",
    "lionfang",
    "lordsof",
    "chaos",
    "11lionfang"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 2612,
    "map": "blackhorn",
    "monsters": [
      "Restless Undead"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2613,
    "map": "blackhorn",
    "ids": [
      1615
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 2614,
    "map": "blackhorn",
    "monsters": [
      "Tomb Spider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2615,
    "map": "blackhorn",
    "ids": [
      1616
    ]
  },
  {
    "kind": "kill",
    "questId": 2615,
    "map": "blackhorn",
    "monsters": [
      "Restless Undead",
      "Tomb Spider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2616,
    "map": "blackhorn",
    "ids": [
      1617
    ]
  },
  {
    "kind": "kill",
    "questId": 2617,
    "map": "blackhorn",
    "monsters": [
      "Bonefeeder Spider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2618,
    "map": "blackhorn",
    "ids": [
      1618
    ]
  },
  {
    "kind": "kill",
    "questId": 2619,
    "map": "blackhorn",
    "monsters": [
      "Tomb Spider"
    ]
  },
  {
    "kind": "kill",
    "questId": 2620,
    "map": "blackhorn",
    "monsters": [
      "Restless Undead"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2621,
    "map": "blackhorn",
    "ids": [
      1619
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2622,
    "map": "onslaughttower",
    "ids": [
      1620,
      1621,
      1622,
      1623
    ]
  },
  {
    "kind": "kill",
    "questId": 2623,
    "map": "onslaughttower",
    "monsters": [
      "Golden Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 2624,
    "map": "onslaughttower",
    "monsters": [
      "Golden Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2625,
    "map": "onslaughttower",
    "ids": [
      1624
    ],
    "quantity": 8
  },
  {
    "kind": "mapItem",
    "questId": 2626,
    "map": "onslaughttower",
    "ids": [
      1625
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2627,
    "map": "onslaughttower",
    "ids": [
      1626
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 2628,
    "map": "onslaughttower",
    "monsters": [
      "Golden Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2629,
    "map": "onslaughttower",
    "ids": [
      1627
    ]
  },
  {
    "kind": "kill",
    "questId": 2630,
    "map": "onslaughttower",
    "monsters": [
      "Maximillian Lionfang"
    ]
  },
  {
    "kind": "kill",
    "questId": 2666,
    "map": "falguard",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2667,
    "map": "falguard",
    "ids": [
      1628
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 2668,
    "map": "falguard",
    "monsters": [
      "Chaonslaught Warrior",
      "Chaonslaught Cavalry"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2669,
    "map": "falguard",
    "ids": [
      1629
    ]
  },
  {
    "kind": "kill",
    "questId": 2670,
    "map": "falguard",
    "monsters": [
      "Chaonslaught Warrior"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2671,
    "map": "falguard",
    "ids": [
      1630
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2672,
    "map": "falguard",
    "ids": [
      1631
    ]
  },
  {
    "kind": "kill",
    "questId": 2673,
    "map": "falguard",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2674,
    "map": "falguard",
    "ids": [
      1632
    ]
  },
  {
    "kind": "kill",
    "questId": 2675,
    "map": "falguard",
    "monsters": [
      "Primarch"
    ]
  },
  {
    "kind": "kill",
    "questId": 2720,
    "map": "deathpits",
    "monsters": [
      "Rotting Darkblood"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2721,
    "map": "deathpits",
    "ids": [
      1691
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 2722,
    "map": "deathpits",
    "monsters": [
      "Rotting Darkblood"
    ]
  },
  {
    "kind": "kill",
    "questId": 2723,
    "map": "deathpits",
    "monsters": [
      "Rotting Darkblood"
    ]
  },
  {
    "kind": "kill",
    "questId": 2724,
    "map": "deathpits",
    "monsters": [
      "Ghastly Darkblood"
    ]
  },
  {
    "kind": "kill",
    "questId": 2725,
    "map": "deathpits",
    "monsters": [
      "Ghastly Darkblood"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2726,
    "map": "deathpits",
    "ids": [
      1692
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 2727,
    "map": "deathpits",
    "monsters": [
      "Rotting Darkblood"
    ]
  },
  {
    "kind": "kill",
    "questId": 2728,
    "map": "deathpits",
    "monsters": [
      "Ghastly Darkblood"
    ]
  },
  {
    "kind": "kill",
    "questId": 2729,
    "map": "deathpits",
    "monsters": [
      "Sundered Darkblood"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2730,
    "map": "deathpits",
    "ids": [
      1693
    ],
    "quantity": 9
  },
  {
    "kind": "plan",
    "questId": 2731,
    "actions": [
      {
        "kind": "hunt",
        "map": "deathpits",
        "monster": "Sundered Darkblood",
        "item": "Primarch Mace"
      },
      {
        "kind": "hunt",
        "map": "deathpits",
        "monster": "Rotting Darkblood",
        "item": "Primarch Trident"
      },
      {
        "kind": "hunt",
        "map": "deathpits",
        "monster": "Ghastly Darkblood",
        "item": "Primarch Spear"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2732,
    "map": "deathpits",
    "ids": [
      1694
    ],
    "quantity": 12
  },
  {
    "kind": "mapItem",
    "questId": 2740,
    "map": "deathpits",
    "ids": [
      1695
    ],
    "quantity": 1
  },
  {
    "kind": "kill",
    "questId": 2740,
    "map": "deathpits",
    "monsters": [
      "Wrathful Vestis"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2792,
    "map": "venomvaults",
    "ids": [
      1724
    ]
  },
  {
    "kind": "kill",
    "questId": 2793,
    "map": "venomvaults",
    "monsters": [
      "Chaonslaught Warrior"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2794,
    "map": "venomvaults",
    "ids": [
      1725
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2796,
    "map": "venomvaults",
    "ids": [
      1726
    ]
  },
  {
    "kind": "kill",
    "questId": 2797,
    "map": "venomvaults",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2798,
    "map": "venomvaults",
    "ids": [
      1727
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 2799,
    "map": "venomvaults",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 2800,
    "map": "venomvaults",
    "monsters": [
      "Chaonslaught Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 2801,
    "map": "venomvaults",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2802,
    "map": "venomvaults",
    "ids": [
      1728
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 2803,
    "map": "venomvaults",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 2804,
    "map": "venomvaults",
    "monsters": [
      "Manticore"
    ]
  },
  {
    "kind": "plan",
    "questId": 2805,
    "actions": [
      {
        "kind": "mapItem",
        "map": "stormtemple",
        "id": 1729,
        "quantity": 4
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2806,
    "actions": [
      {
        "kind": "hunt",
        "map": "stormtemple",
        "cell": "r1",
        "pad": "Left",
        "monster": "Chaonslaught Warrior",
        "item": "Lightning Boots"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 2807,
    "map": "stormtemple",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 2808,
    "map": "stormtemple",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2809,
    "map": "stormtemple",
    "ids": [
      1730
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 2810,
    "map": "stormtemple",
    "monsters": [
      "Chaonslaught Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2811,
    "map": "stormtemple",
    "ids": [
      1731
    ]
  },
  {
    "kind": "kill",
    "questId": 2812,
    "map": "stormtemple",
    "monsters": [
      "Chaonslaught Cavalry"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2813,
    "map": "stormtemple",
    "ids": [
      1732
    ]
  },
  {
    "kind": "kill",
    "questId": 2814,
    "map": "stormtemple",
    "monsters": [
      "Chaos Lord Lionfang"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.lordsof-chaos.11lionfang-darkblood",
    category: "Story",
    map: "blackhorn",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
