// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Ravenscar Story",
  "description": "This will finish the Ravenscar Story quests.",
  "tags": [
    "story",
    "quest",
    "legion",
    "ravenscar",
    "raven scar",
    "raven",
    "scar",
    "dage"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 2901,
    "map": "ravenscar",
    "ids": [
      1767
    ]
  },
  {
    "kind": "kill",
    "questId": 2902,
    "map": "ravenscar",
    "monsters": [
      "Restless Undead",
      "Restless Undead"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2903,
    "map": "ravenscar",
    "ids": [
      1768
    ]
  },
  {
    "kind": "kill",
    "questId": 2904,
    "map": "ravenscar",
    "monsters": [
      "Restless Undead"
    ]
  },
  {
    "kind": "kill",
    "questId": 2905,
    "map": "ravenscar",
    "monsters": [
      "Undead Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 2906,
    "map": "ravenscar",
    "monsters": [
      "Shadowman"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2907,
    "map": "ravenscar",
    "ids": [
      1769
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.legion.ravenscar",
    category: "Story",
    map: "ravenscar",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
