// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "World Soul",
  "description": "This will finish the World Soul quest.",
  "tags": [
    "story",
    "quest",
    "legion",
    "world-soul",
    "world",
    "soul"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 6238,
    "actions": [
      {
        "kind": "hunt",
        "map": "worldsoul",
        "monster": "Dwakel Infiltrator",
        "item": "Void Cortex"
      },
      {
        "kind": "hunt",
        "map": "worldsoul",
        "monster": "Dwakel Infiltrator",
        "item": "Paradox Processor"
      },
      {
        "kind": "hunt",
        "map": "worldsoul",
        "monster": "Dwakel Infiltrator",
        "item": "Thermal Vent"
      },
      {
        "kind": "hunt",
        "map": "worldsoul",
        "monster": "Dwakel Infiltrator",
        "item": "Dwakel Defeated",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 6239,
    "map": "worldsoul",
    "monsters": [
      "Divine Water Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 6240,
    "map": "worldsoul",
    "monsters": [
      "Divine Fire Elemental"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6241,
    "map": "worldsoul",
    "ids": [
      5681
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 6241,
    "map": "worldsoul",
    "monsters": [
      "Skeletal Squatter"
    ]
  },
  {
    "kind": "kill",
    "questId": 6242,
    "map": "worldsoul",
    "monsters": [
      "Radioactive Hydra"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6243,
    "map": "worldsoul",
    "ids": [
      5680
    ]
  },
  {
    "kind": "kill",
    "questId": 6243,
    "map": "worldsoul",
    "monsters": [
      "Legion Dreadmarch"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6244,
    "map": "worldsoul",
    "ids": [
      5682
    ]
  },
  {
    "kind": "kill",
    "questId": 6244,
    "map": "worldsoul",
    "monsters": [
      "Legion Dreadmarch"
    ]
  },
  {
    "kind": "kill",
    "questId": 6245,
    "map": "worldsoul",
    "monsters": [
      "Core Guardian"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.legion.world-soul",
    category: "Story",
    map: "worldsoul",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
