// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Arcangrove Story",
  "description": "This will finish the Arcangrove story.",
  "tags": [
    "story",
    "quest",
    "arcangrove",
    "13-lords-of-chaos"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 805,
    "map": "arcangrove",
    "ids": [
      139
    ]
  },
  {
    "kind": "mapItem",
    "questId": 806,
    "map": "cloister",
    "ids": [
      142
    ]
  },
  {
    "kind": "mapItem",
    "questId": 807,
    "map": "cloister",
    "ids": [
      140
    ]
  },
  {
    "kind": "kill",
    "questId": 808,
    "map": "cloister",
    "monsters": [
      "Acornent"
    ]
  },
  {
    "kind": "kill",
    "questId": 809,
    "map": "cloister",
    "monsters": [
      "Karasu"
    ]
  },
  {
    "kind": "plan",
    "questId": 810,
    "actions": [
      {
        "kind": "mapItem",
        "map": "cloister",
        "id": 141,
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 811,
    "map": "cloister",
    "monsters": [
      "Wendigo"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 813,
    "map": "mudluk",
    "ids": [
      143
    ]
  },
  {
    "kind": "kill",
    "questId": 814,
    "map": "mudluk",
    "monsters": [
      "Swamp Lurker"
    ]
  },
  {
    "kind": "kill",
    "questId": 815,
    "map": "mudluk",
    "monsters": [
      "Swamp Lurker"
    ]
  },
  {
    "kind": "kill",
    "questId": 816,
    "map": "arcangrove",
    "monsters": [
      "Gorillaphant"
    ]
  },
  {
    "kind": "kill",
    "questId": 817,
    "map": "mudluk",
    "monsters": [
      "Swamp Frogdrake"
    ]
  },
  {
    "kind": "kill",
    "questId": 818,
    "map": "mudluk",
    "monsters": [
      "Tiger Leech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 825,
    "map": "natatorium",
    "ids": [
      144
    ]
  },
  {
    "kind": "mapItem",
    "questId": 826,
    "map": "natatorium",
    "ids": [
      145
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 827,
    "map": "natatorium",
    "monsters": [
      "Anglerfish"
    ]
  },
  {
    "kind": "kill",
    "questId": 828,
    "map": "natatorium",
    "monsters": [
      "Merdraconian"
    ]
  },
  {
    "kind": "plan",
    "questId": 829,
    "actions": [
      {
        "kind": "hunt",
        "map": "arcangrove",
        "monster": "Seed Spitter",
        "item": "Brain Coral",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "cloister",
        "monster": "Acornent",
        "item": "Staghorns",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "cloister",
        "monster": "Karasu",
        "item": "Sea Fan",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "cloister",
        "monster": "Wendigo",
        "item": "Sea Whip"
      },
      {
        "kind": "hunt",
        "map": "mudluk",
        "monster": "Swamp Frogdrake",
        "item": "Anemones",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 830,
    "map": "natatorium",
    "monsters": [
      "Nessie"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 831,
    "map": "gilead",
    "ids": [
      146
    ]
  },
  {
    "kind": "plan",
    "questId": 832,
    "actions": [
      {
        "kind": "hunt",
        "map": "gilead",
        "monster": "Earth Elemental",
        "item": "Dregs Essence",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "arcangrove",
        "monster": "Seed Spitter",
        "item": "Spitter Spirit",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 833,
    "actions": [
      {
        "kind": "hunt",
        "map": "gilead",
        "monster": "Water Elemental",
        "item": "Aqueous Essence",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "natatorium",
        "monster": "Merdraconian",
        "item": "MerCore",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 834,
    "actions": [
      {
        "kind": "hunt",
        "map": "gilead",
        "monster": "Wind Elemental",
        "item": "Welkin Essence",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "cloister",
        "monster": "Karasu",
        "item": "Karasu Soul",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 835,
    "actions": [
      {
        "kind": "hunt",
        "map": "gilead",
        "monster": "Fire Elemental",
        "item": "Pyre Essence",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "mudluk",
        "monster": "Swamp Frogdrake",
        "item": "Fire Salamander",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 836,
    "map": "gilead",
    "monsters": [
      "Mana Elemental"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 838,
    "map": "mafic",
    "ids": [
      147
    ]
  },
  {
    "kind": "kill",
    "questId": 839,
    "map": "mafic",
    "monsters": [
      "Volcanic Maggot"
    ]
  },
  {
    "kind": "kill",
    "questId": 840,
    "map": "mafic",
    "monsters": [
      "Scoria Serpent"
    ]
  },
  {
    "kind": "kill",
    "questId": 841,
    "map": "mafic",
    "monsters": [
      "Living Fire"
    ]
  },
  {
    "kind": "kill",
    "questId": 842,
    "map": "mafic",
    "monsters": [
      "Mafic Dragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 843,
    "map": "elemental",
    "monsters": [
      "Mana Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 844,
    "map": "elemental",
    "monsters": [
      "Mana Falcon"
    ]
  },
  {
    "kind": "plan",
    "questId": 845,
    "actions": [
      {
        "kind": "hunt",
        "map": "mafic",
        "monster": "Mafic Dragon",
        "item": "Astral Orb of Mafic"
      },
      {
        "kind": "hunt",
        "map": "cloister",
        "monster": "Wendigo",
        "item": "Astral Orb of the Cloister"
      },
      {
        "kind": "hunt",
        "map": "mudluk",
        "monster": "Tiger Leech",
        "item": "Astral Orb of Mudluk"
      },
      {
        "kind": "hunt",
        "map": "natatorium",
        "monster": "Nessie",
        "item": "Astral Orb of Natatorium"
      },
      {
        "kind": "hunt",
        "map": "gilead",
        "monster": "Mana Elemental",
        "item": "Astral Orb of Gilead"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 846,
    "actions": [
      {
        "kind": "packet",
        "packet": "%xt%zm%updateQuest%1%847%"
      },
      {
        "kind": "hunt",
        "map": "elemental",
        "monster": "Mana Golem",
        "item": "Mana Golem Defeated"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 847,
    "map": "ledgermayne",
    "monsters": [
      "Ledgermayne"
    ]
  },
  {
    "kind": "kill",
    "questId": 245,
    "map": "mobius",
    "monsters": [
      "Chaos Sp-Eye"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 246,
    "map": "mobius",
    "ids": [
      42
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 247,
    "map": "mobius",
    "monsters": [
      "Fire Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 260,
    "map": "mobius",
    "ids": [
      44
    ]
  },
  {
    "kind": "kill",
    "questId": 248,
    "map": "mobius",
    "monsters": [
      "Cyclops Raider"
    ]
  },
  {
    "kind": "kill",
    "questId": 249,
    "map": "mobius",
    "monsters": [
      "Slugfit"
    ]
  },
  {
    "kind": "kill",
    "questId": 250,
    "map": "faerie",
    "monsters": [
      "Chainsaw Sneevil"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 251,
    "map": "faerie",
    "ids": [
      43
    ],
    "quantity": 7
  },
  {
    "kind": "kill",
    "questId": 252,
    "map": "faerie",
    "monsters": [
      "Chainsaw Sneevil"
    ]
  },
  {
    "kind": "kill",
    "questId": 255,
    "map": "faerie",
    "monsters": [
      "Cyclops Warlord"
    ]
  },
  {
    "kind": "kill",
    "questId": 256,
    "map": "faerie",
    "monsters": [
      "Aracara"
    ]
  },
  {
    "kind": "kill",
    "questId": 257,
    "map": "cornelis",
    "monsters": [
      "Gargoyle"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 261,
    "map": "cornelis",
    "ids": [
      45
    ]
  },
  {
    "kind": "kill",
    "questId": 258,
    "map": "cornelis",
    "monsters": [
      "Gargoyle"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 262,
    "map": "cornelis",
    "ids": [
      46
    ]
  },
  {
    "kind": "kill",
    "questId": 259,
    "map": "cornelis",
    "monsters": [
      "Stone Golem"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 263,
    "map": "cornelis",
    "ids": [
      47
    ]
  },
  {
    "kind": "mapItem",
    "questId": 266,
    "map": "mobius",
    "ids": [
      48
    ]
  },
  {
    "kind": "mapItem",
    "questId": 267,
    "map": "mobius",
    "ids": [
      49
    ]
  },
  {
    "kind": "kill",
    "questId": 264,
    "map": "mobius",
    "monsters": [
      "Cyclops Raider"
    ]
  },
  {
    "kind": "plan",
    "questId": 265,
    "actions": [
      {
        "kind": "hunt",
        "map": "faerie",
        "monster": "Chainsaw Sneevil",
        "item": "Cardboard Box",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 268,
    "map": "relativity",
    "monsters": [
      "Cyclops Raider"
    ]
  },
  {
    "kind": "kill",
    "questId": 269,
    "map": "relativity",
    "monsters": [
      "Fire Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 270,
    "map": "relativity",
    "monsters": [
      "Head Gargoyle"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 271,
    "map": "hydra",
    "ids": [
      50,
      51,
      52
    ]
  },
  {
    "kind": "plan",
    "questId": 272,
    "actions": []
  },
  {
    "kind": "mapItem",
    "questId": 319,
    "map": "tavern",
    "ids": [
      56
    ],
    "quantity": 7
  },
  {
    "kind": "kill",
    "questId": 320,
    "map": "pines",
    "monsters": [
      "Pine Grizzly"
    ]
  },
  {
    "kind": "kill",
    "questId": 321,
    "map": "pines",
    "monsters": [
      "Red Shell Turtle"
    ]
  },
  {
    "kind": "kill",
    "questId": 322,
    "map": "pines",
    "monsters": [
      "Twistedtooth"
    ]
  },
  {
    "kind": "kill",
    "questId": 324,
    "map": "pines",
    "monsters": [
      "Red Shell Turtle"
    ]
  },
  {
    "kind": "kill",
    "questId": 325,
    "map": "pines",
    "monsters": [
      "Pine Grizzly"
    ]
  },
  {
    "kind": "kill",
    "questId": 326,
    "map": "pines",
    "monsters": [
      "LeatherWing"
    ]
  },
  {
    "kind": "plan",
    "questId": 327,
    "actions": [
      {
        "kind": "hunt",
        "map": "pines",
        "monster": "Pine Troll",
        "item": "Pine Air Freshener"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 323
  },
  {
    "kind": "mapItem",
    "questId": 344,
    "map": "dwarfhold",
    "ids": [
      60
    ]
  },
  {
    "kind": "kill",
    "questId": 331,
    "map": "mountainpath",
    "monsters": [
      "Ore Balboa"
    ]
  },
  {
    "kind": "kill",
    "questId": 332,
    "map": "mountainpath",
    "monsters": [
      "Vultragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 333,
    "map": "dwarfhold",
    "monsters": [
      "Chaos Drow"
    ]
  },
  {
    "kind": "kill",
    "questId": 334,
    "map": "dwarfhold",
    "monsters": [
      "Glow Worm"
    ]
  },
  {
    "kind": "kill",
    "questId": 335,
    "map": "dwarfhold",
    "monsters": [
      "Albino Bat"
    ]
  },
  {
    "kind": "kill",
    "questId": 336,
    "map": "dwarfhold",
    "monsters": [
      "Chaotic Draconian"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 337,
    "map": "dwarfhold",
    "ids": [
      59
    ],
    "quantity": 7
  },
  {
    "kind": "kill",
    "questId": 338,
    "map": "dwarfhold",
    "monsters": [
      "Chaos Drow"
    ]
  },
  {
    "kind": "kill",
    "questId": 339,
    "map": "dwarfhold",
    "monsters": [
      "Chaotic Draconian"
    ]
  },
  {
    "kind": "plan",
    "questId": 340,
    "actions": [
      {
        "kind": "hunt",
        "map": "dwarfhold",
        "monster": "Albino Bat",
        "item": "Block of Talc"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 343
  },
  {
    "kind": "plan",
    "questId": 341,
    "actions": [
      {
        "kind": "hunt",
        "map": "dwarfhold",
        "monster": "Amadeus",
        "item": "Key Mold"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 346,
    "map": "uppercity",
    "ids": [
      61
    ]
  },
  {
    "kind": "kill",
    "questId": 347,
    "map": "uppercity",
    "monsters": [
      "Drow Assassin"
    ]
  },
  {
    "kind": "kill",
    "questId": 348,
    "map": "uppercity",
    "monsters": [
      "Chaotic Draconian"
    ]
  },
  {
    "kind": "kill",
    "questId": 349,
    "map": "uppercity",
    "monsters": [
      "Chaos Egg"
    ]
  },
  {
    "kind": "kill",
    "questId": 350,
    "map": "uppercity",
    "monsters": [
      "Terradactyl"
    ]
  },
  {
    "kind": "kill",
    "questId": 351,
    "map": "uppercity",
    "monsters": [
      "Rhino Beetle"
    ]
  },
  {
    "kind": "kill",
    "questId": 352,
    "map": "uppercity",
    "monsters": [
      "Cave Lizard"
    ]
  },
  {
    "kind": "plan",
    "questId": 353,
    "actions": [
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Balboa",
        "item": "Balboa Core",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Chaos Drow",
        "item": "Magnesium Flare"
      },
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Albino Bat",
        "item": "Rusted Claw",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 353,
    "actions": [
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Balboa",
        "item": "Balboa Core",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Albino Bat",
        "item": "Rusted Claw",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Chaos Drow",
        "item": "Magnesium Flare"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 354
  },
  {
    "kind": "kill",
    "questId": 355,
    "map": "dwarfprison",
    "monsters": [
      "Warden Elfis"
    ]
  },
  {
    "kind": "kill",
    "questId": 356,
    "map": "dwarfprison",
    "monsters": [
      "Albino Bat",
      "Balboa",
      "Chaos Drow"
    ]
  },
  {
    "kind": "plan",
    "questId": 356,
    "actions": [
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Albino Bat",
        "item": "Nitrate Elements",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Chaos Drow",
        "item": "Drow Shoelaces",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "dwarfprison",
        "monster": "Balboa",
        "item": "Flint Stone",
        "quantity": 2
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 357
  },
  {
    "kind": "mapItem",
    "questId": 362,
    "map": "roc",
    "ids": [
      62
    ]
  },
  {
    "kind": "mapItem",
    "questId": 363,
    "map": "stalagbite",
    "ids": [
      63
    ]
  },
  {
    "kind": "kill",
    "questId": 3371,
    "map": "arcangrove",
    "monsters": [
      "Chaos Sprites"
    ]
  },
  {
    "kind": "kill",
    "questId": 3372,
    "map": "arcangrove",
    "monsters": [
      "Gorillaphant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 3373,
    "map": "arcangrove",
    "ids": [
      2505
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 3373,
    "map": "arcangrove",
    "monsters": [
      "Seed Spitter"
    ]
  },
  {
    "kind": "kill",
    "questId": 3374,
    "map": "arcangrove",
    "monsters": [
      "Seed Spitter"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 3375,
    "map": "arcangrove",
    "ids": [
      2514,
      2515,
      2516,
      2517
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.arcangrove",
    category: "Story",
    map: "arcangrove",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
