// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Artixpointe Story",
  "description": "This will finish the Artixpointe quest.",
  "tags": [
    "story",
    "artixpointe"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 3800,
    "actions": [
      {
        "kind": "hunt",
        "map": "artixpointe",
        "monster": "Corrupted Sushi Chef",
        "item": "Find Unholy Wasabi"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 3801,
    "actions": [
      {
        "kind": "mapItem",
        "map": "artixpointe",
        "id": 2911,
        "quantity": 1
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 3802,
    "actions": [
      {
        "kind": "hunt",
        "map": "battlefowl",
        "monster": "Chickencow",
        "item": "Cursed Claw Found"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 3803,
    "actions": [
      {
        "kind": "hunt",
        "map": "graveyard",
        "monster": "Big Jack Sprat",
        "item": "Zorbak's Skull"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 3804,
    "actions": [
      {
        "kind": "hunt",
        "map": "vendorbooths",
        "monster": "Dragon Khan",
        "item": "Corrupt Scepter Found"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 3805,
    "actions": [
      {
        "kind": "hunt",
        "map": "undergroundlabb",
        "monster": "Rabid Server Hamster",
        "item": "Cursed Power Button"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 3806,
    "actions": [
      {
        "kind": "hunt",
        "map": "gravefang",
        "monster": "Gravefang",
        "item": "Gravefang Defeated"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 3807,
    "actions": [
      {
        "kind": "mapItem",
        "map": "artixpointe",
        "id": 2912,
        "quantity": 1
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.artixpointe",
    category: "Story",
    map: "artixpointe",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
