// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Battle Under Story",
  "description": "This will complete the Battle Under Story.",
  "tags": [
    "story",
    "quest",
    "battleunder",
    "battle",
    "under"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 374,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "plan",
    "questId": 375,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Skeletal Claymore",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Bony Chestplate",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 376,
    "map": "battleundera",
    "monsters": [
      "Bone Terror"
    ]
  },
  {
    "kind": "kill",
    "questId": 377,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 374,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "plan",
    "questId": 375,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Skeletal Claymore",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Bony Chestplate",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 376,
    "map": "battleundera",
    "monsters": [
      "Bone Terror"
    ]
  },
  {
    "kind": "kill",
    "questId": 377,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 689,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 690,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 691,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 692,
    "map": "battleunderb",
    "monsters": [
      "Undead Champion"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 935,
    "map": "battleunderb",
    "ids": [
      253
    ]
  },
  {
    "kind": "kill",
    "questId": 374,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "plan",
    "questId": 375,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Skeletal Claymore",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Bony Chestplate",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 376,
    "map": "battleundera",
    "monsters": [
      "Bone Terror"
    ]
  },
  {
    "kind": "kill",
    "questId": 377,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 689,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 690,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 691,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 692,
    "map": "battleunderb",
    "monsters": [
      "Undead Champion"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 935,
    "map": "battleunderb",
    "ids": [
      253
    ]
  },
  {
    "kind": "kill",
    "questId": 936,
    "map": "battleunderc",
    "monsters": [
      "Blue Crystalized Undead"
    ]
  },
  {
    "kind": "kill",
    "questId": 937,
    "map": "battleunderc",
    "monsters": [
      "Blue Crystalized Undead"
    ]
  },
  {
    "kind": "kill",
    "questId": 938,
    "map": "battleunderc",
    "monsters": [
      "Crystalized Jellyfish"
    ]
  },
  {
    "kind": "plan",
    "questId": 939,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Bone Terror",
        "item": "Bone Terror Soul"
      },
      {
        "kind": "hunt",
        "map": "battleunderb",
        "monster": "Undead Champion",
        "item": "Undead Champion Soul"
      },
      {
        "kind": "hunt",
        "map": "battleunderc",
        "monster": "Crystalized Jellyfish",
        "item": "Jellyfish Soul"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 374,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "plan",
    "questId": 375,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Skeletal Claymore",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Skeletal Warrior",
        "item": "Bony Chestplate",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 376,
    "map": "battleundera",
    "monsters": [
      "Bone Terror"
    ]
  },
  {
    "kind": "kill",
    "questId": 377,
    "map": "battleundera",
    "monsters": [
      "Skeletal Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 689,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 690,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 691,
    "map": "battleunderb",
    "monsters": [
      "Skeleton Warrior"
    ]
  },
  {
    "kind": "kill",
    "questId": 692,
    "map": "battleunderb",
    "monsters": [
      "Undead Champion"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 935,
    "map": "battleunderb",
    "ids": [
      253
    ]
  },
  {
    "kind": "kill",
    "questId": 936,
    "map": "battleunderc",
    "monsters": [
      "Blue Crystalized Undead"
    ]
  },
  {
    "kind": "kill",
    "questId": 937,
    "map": "battleunderc",
    "monsters": [
      "Blue Crystalized Undead"
    ]
  },
  {
    "kind": "kill",
    "questId": 938,
    "map": "battleunderc",
    "monsters": [
      "Crystalized Jellyfish"
    ]
  },
  {
    "kind": "plan",
    "questId": 939,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleundera",
        "monster": "Bone Terror",
        "item": "Bone Terror Soul"
      },
      {
        "kind": "hunt",
        "map": "battleunderb",
        "monster": "Undead Champion",
        "item": "Undead Champion Soul"
      },
      {
        "kind": "hunt",
        "map": "battleunderc",
        "monster": "Crystalized Jellyfish",
        "item": "Jellyfish Soul"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2211,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleunderd",
        "cell": "Enter",
        "pad": "Spawn",
        "monster": "Shivering Bones",
        "item": "Shivering Bone",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2212,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleunderd",
        "cell": "r2",
        "pad": "Left",
        "monster": "Icy Banshee",
        "item": "Banshee Slain",
        "quantity": 7
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2212,
    "map": "battleunderd",
    "ids": [
      1286
    ],
    "quantity": 8
  },
  {
    "kind": "plan",
    "questId": 2213,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleunderd",
        "cell": "r5",
        "pad": "Left",
        "monster": "Skeletal Warrior",
        "item": "Icy Pickaxe Found"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2214,
    "actions": [
      {
        "kind": "hunt",
        "map": "battleunderd",
        "cell": "r5",
        "pad": "Left",
        "monster": "Glacial Horror",
        "item": "Glacial Horror Slain"
      },
      {
        "kind": "mapItem",
        "map": "battleunderd",
        "id": 1287,
        "quantity": 4
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2215,
    "map": "battleunderd",
    "ids": [
      1288
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5927,
    "map": "battleundere",
    "ids": [
      5362
    ]
  },
  {
    "kind": "kill",
    "questId": 5927,
    "map": "battleundere",
    "monsters": [
      "Lava Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 5928,
    "map": "battleundere",
    "monsters": [
      "Hot Mama"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.battle-under",
    category: "Story",
    map: "battleundera",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
