// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Borgars Story",
  "description": "This will complete the Borgars story.",
  "tags": [
    "story",
    "quest",
    "borgars"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7510,
    "map": "extinction",
    "monsters": [
      "Lard",
      "Freezer Drone"
    ]
  },
  {
    "kind": "kill",
    "questId": 7511,
    "map": "battlefowl",
    "monsters": [
      "Chickencow"
    ]
  },
  {
    "kind": "kill",
    "questId": 7512,
    "map": "freakitiki",
    "monsters": [
      "Sugar Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 7513,
    "map": "stalagbite",
    "monsters": [
      "Balboa"
    ]
  },
  {
    "kind": "kill",
    "questId": 7514,
    "map": "pirates",
    "monsters": [
      "Fishwing"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7515,
    "map": "arcangrove",
    "ids": [
      7370
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7516,
    "map": "thespan",
    "ids": [
      7371
    ]
  },
  {
    "kind": "plan",
    "questId": 7518,
    "actions": [
      {
        "kind": "hunt",
        "map": "portalmaze",
        "monster": "Time Wraith",
        "item": "Time Fragment",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 7517
  },
  {
    "kind": "mapItem",
    "questId": 7519,
    "map": "brightfortress",
    "ids": [
      7372
    ]
  },
  {
    "kind": "plan",
    "questId": 7520,
    "actions": [
      {
        "kind": "hunt",
        "map": "brightfortress",
        "monster": "Brightscythe Reaver",
        "item": "Kale",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "brightfortress",
        "monster": "Brightscythe Reaver",
        "item": "Quinoa",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7521,
    "map": "borgars",
    "ids": [
      7373
    ]
  },
  {
    "kind": "kill",
    "questId": 7522,
    "map": "borgars",
    "monsters": [
      "Burglinster"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.borgars",
    category: "Story",
    map: "extinction",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
