// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Castle Tunnels Story",
  "description": "This will complete the Castle Tunnels story.",
  "tags": [
    "story",
    "quest",
    "castle-tunnels",
    "castle",
    "tunnels"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 5244,
    "map": "CastleTunnels",
    "ids": [
      4597
    ]
  },
  {
    "kind": "kill",
    "questId": 5244,
    "map": "CastleTunnels",
    "monsters": [
      "Vampire Bat",
      "Blood Maggot"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5245,
    "map": "CastleTunnels",
    "ids": [
      4598
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 5246,
    "map": "CastleTunnels",
    "ids": [
      4599
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 5247,
    "map": "CastleTunnels",
    "monsters": [
      "Blood Maggot"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5248,
    "map": "CastleTunnels",
    "ids": [
      4600
    ]
  },
  {
    "kind": "kill",
    "questId": 5249,
    "map": "CastleTunnels",
    "monsters": [
      "Vampire Ghoul",
      "Vampire Ghoul"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5250,
    "map": "CastleTunnels",
    "ids": [
      4601
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5251,
    "map": "CastleTunnels",
    "ids": [
      4602,
      4603
    ]
  },
  {
    "kind": "kill",
    "questId": 5252,
    "map": "CastleTunnels",
    "monsters": [
      "Blood Symbiote",
      "Blood Symbiote"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5253,
    "map": "CastleTunnels",
    "ids": [
      4604
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5254,
    "map": "CastleTunnels",
    "ids": [
      4605
    ]
  },
  {
    "kind": "kill",
    "questId": 5255,
    "map": "CastleTunnels",
    "monsters": [
      "Blood Dragon"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.castle-tunnels",
    category: "Story",
    map: "CastleTunnels",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
