// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Cornelis Story (Member)",
  "description": "This will complete the Cornelis story.",
  "tags": [
    "story",
    "quest",
    "cornelis",
    "member",
    "mem"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 1625,
    "map": "cornelis",
    "ids": [
      856
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1626,
    "map": "cornelis",
    "ids": [
      857
    ],
    "quantity": 20
  },
  {
    "kind": "kill",
    "questId": 1627,
    "map": "cornelis",
    "monsters": [
      "Gargoyle"
    ]
  },
  {
    "kind": "plan",
    "questId": 1628,
    "actions": [
      {
        "kind": "buy",
        "map": "yulgar",
        "shopId": 366,
        "item": "The Lens of Cornelis"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1629,
    "map": "cornelis",
    "ids": [
      858
    ]
  },
  {
    "kind": "kill",
    "questId": 1630,
    "map": "cornelis",
    "monsters": [
      "Gargantugoyle"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1631,
    "map": "cornelis",
    "ids": [
      859
    ]
  },
  {
    "kind": "plan",
    "questId": 1632,
    "actions": [
      {
        "kind": "hunt",
        "map": "cornelis",
        "monster": "Gargoyle",
        "item": "Gargoyle Horn",
        "quantity": 100,
        "isTemp": false
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.cornelis-mem",
    category: "Story",
    map: "cornelis",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
