// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Crux Ship Story",
  "description": "This will finish the Crux Ship story.",
  "tags": [
    "story",
    "quest",
    "crux-ship",
    "crux",
    "ship"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 4598,
    "actions": [
      {
        "kind": "hunt",
        "map": "CruxShip",
        "cell": "r2",
        "pad": "Left",
        "monster": "Shadow Locust",
        "item": "Locusts Defeated",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4599,
    "actions": [
      {
        "kind": "mapItem",
        "map": "CruxShip",
        "id": 3901,
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "CruxShip",
        "cell": "r2",
        "pad": "Left",
        "monster": "Shadow Locust",
        "item": "Locusts Defeated",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4603,
    "map": "CruxShip",
    "monsters": [
      "Treasure Hunter"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4604,
    "map": "CruxShip",
    "ids": [
      3902
    ],
    "quantity": 3
  },
  {
    "kind": "plan",
    "questId": 4606,
    "actions": [
      {
        "kind": "hunt",
        "map": "CruxShip",
        "monster": "Shadow Locust",
        "item": "Locusts Beaten",
        "quantity": 12
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4607,
    "actions": [
      {
        "kind": "hunt",
        "map": "CruxShip",
        "monster": "Nokris Plaguebringer",
        "item": "Nokris Plaguebringer Defeated"
      },
      {
        "kind": "hunt",
        "map": "CruxShip",
        "cell": "r2",
        "pad": "Left",
        "monster": "Shadow Locust",
        "item": "Locusts Defeated",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4610,
    "actions": [
      {
        "kind": "hunt",
        "map": "CruxShip",
        "monster": "Ancient Mummy",
        "item": "Mummy Defeated",
        "quantity": 12
      },
      {
        "kind": "hunt",
        "map": "CruxShip",
        "monster": "Treasure Hunter",
        "item": "Treasure Hunter Defeated",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4611,
    "actions": [
      {
        "kind": "hunt",
        "map": "CruxShip",
        "monster": "Treasure Hunter Captain",
        "item": "Captain Defeated"
      },
      {
        "kind": "hunt",
        "map": "CruxShip",
        "monster": "Treasure Hunter",
        "item": "Treasure Hunter Defeated",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4613,
    "actions": [
      {
        "kind": "hunt",
        "map": "CruxShip",
        "monster": "Apephryx",
        "item": "Apephryx Defeated"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4616,
    "actions": [
      {
        "kind": "hunt",
        "map": "Mummies",
        "monster": "Mummy",
        "item": "Mummy Defeated",
        "quantity": 100
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.crux-ship",
    category: "Story",
    map: "CruxShip",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
