// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "DarkDungeon",
  "description": "This script finish all dark dungeon quests storyline in /darkdungeon",
  "tags": [
    "story",
    "dark",
    "dungeon",
    "line",
    "mirror",
    "drakath"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 3538,
    "map": "darkdungeon",
    "ids": [
      2671,
      2672,
      2673
    ]
  },
  {
    "kind": "kill",
    "questId": 3539,
    "map": "darkdungeon",
    "monsters": [
      "Dungeon Minion"
    ]
  },
  {
    "kind": "kill",
    "questId": 3540,
    "map": "darkdungeon",
    "monsters": [
      "Dungeon Paladin"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 3541,
    "map": "darkdungeon",
    "ids": [
      2674
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 3541,
    "map": "darkdungeon",
    "monsters": [
      "Shadow Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 3542,
    "map": "darkdungeon",
    "ids": [
      2679
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 3543,
    "map": "darkdungeon",
    "monsters": [
      "Cockatrice"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.dark-dungeon",
    category: "Story",
    map: "darkdungeon",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
