// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Dream Palace Story",
  "description": "This will finish the Dream Palace Story.",
  "tags": [
    "story",
    "quest",
    "dream-palace",
    "dream",
    "palace"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7869,
    "map": "dreampalace",
    "monsters": [
      "Flaming Harpy",
      "Golmoth"
    ]
  },
  {
    "kind": "kill",
    "questId": 7870,
    "map": "dreampalace",
    "monsters": [
      "Zelkur",
      "Lotus Spider"
    ]
  },
  {
    "kind": "kill",
    "questId": 7871,
    "map": "dreampalace",
    "monsters": [
      "Palace Hound",
      "Gazeroth"
    ]
  },
  {
    "kind": "kill",
    "questId": 7872,
    "map": "dreampalace",
    "monsters": [
      "Zal",
      "Ethereal Harpy"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7873,
    "map": "dreampalace",
    "ids": [
      7944
    ]
  },
  {
    "kind": "kill",
    "questId": 7874,
    "map": "dreampalace",
    "monsters": [
      "Guardian Hound",
      "Zahad"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.dream-palace",
    category: "Story",
    map: "dreampalace",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
