// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Gamehaven Story",
  "description": "This will finish the Gamehaven Story.",
  "tags": [
    "story",
    "quest",
    "gamehaven",
    "game",
    "haven"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "chain",
    "questId": 940
  },
  {
    "kind": "mapItem",
    "questId": 941,
    "map": "gamehaven",
    "ids": [
      267
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 942,
    "map": "gamehaven",
    "monsters": [
      "Evil Arcade Machine"
    ]
  },
  {
    "kind": "kill",
    "questId": 943,
    "map": "gamehaven",
    "monsters": [
      "Evil Console Machine"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 944,
    "map": "gamehaven",
    "ids": [
      269
    ]
  },
  {
    "kind": "mapItem",
    "questId": 945,
    "map": "warehouse",
    "ids": [
      270
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 946,
    "map": "warehouse",
    "monsters": [
      "Delivery Sneevil"
    ]
  },
  {
    "kind": "kill",
    "questId": 947,
    "map": "warehouse",
    "monsters": [
      "Snapper Shrub"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 948,
    "map": "warehouse",
    "ids": [
      272
    ]
  },
  {
    "kind": "mapItem",
    "questId": 950,
    "map": "arcadion",
    "ids": [
      271
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 951,
    "map": "arcadion",
    "monsters": [
      "Megadude"
    ]
  },
  {
    "kind": "kill",
    "questId": 952,
    "map": "arcadion",
    "monsters": [
      "Blue Hedgehog"
    ]
  },
  {
    "kind": "kill",
    "questId": 953,
    "map": "arcadion",
    "monsters": [
      "Orc Plumber"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.game-haven",
    category: "Story",
    map: "gamehaven",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
