// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Giant Tale Story",
  "description": "This will finish the Giant Tale Story.",
  "tags": [
    "story",
    "quest",
    "giant-tale",
    "giant",
    "tale"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 717,
    "map": "giant",
    "ids": [
      119
    ]
  },
  {
    "kind": "kill",
    "questId": 718,
    "map": "giant",
    "monsters": [
      "Red Ant"
    ]
  },
  {
    "kind": "kill",
    "questId": 719,
    "map": "giant",
    "monsters": [
      "Dust Bunny"
    ]
  },
  {
    "kind": "kill",
    "questId": 720,
    "map": "giant",
    "monsters": [
      "Giant Cat"
    ]
  },
  {
    "kind": "kill",
    "questId": 721,
    "map": "smuurvil",
    "monsters": [
      "Smuurvil"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 722,
    "map": "smuurvil",
    "ids": [
      122
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 723,
    "map": "smuurvil",
    "monsters": [
      "Smuurvil"
    ]
  },
  {
    "kind": "kill",
    "questId": 724,
    "map": "smuurvil",
    "monsters": [
      "Smuurvilette"
    ]
  },
  {
    "kind": "kill",
    "questId": 725,
    "map": "smuurvil",
    "monsters": [
      "Papa Smuurvil"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 737,
    "map": "table",
    "ids": [
      123,
      124,
      125,
      126,
      127,
      128
    ]
  },
  {
    "kind": "chain",
    "questId": 743
  },
  {
    "kind": "kill",
    "questId": 747,
    "map": "andre",
    "monsters": [
      "Giant Foot"
    ]
  },
  {
    "kind": "kill",
    "questId": 748,
    "map": "andre",
    "monsters": [
      "Giant Flea"
    ]
  },
  {
    "kind": "kill",
    "questId": 749,
    "map": "andre",
    "monsters": [
      "Giant Necklace"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.giant-tale-story",
    category: "Story",
    map: "giant",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
