// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "J6 Saga Story",
  "description": "This will finish the J6 Saga Story.",
  "tags": [
    "story",
    "quest",
    "j6-saga",
    "j6saga"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "chain",
    "questId": 674
  },
  {
    "kind": "chain",
    "questId": 693
  },
  {
    "kind": "mapItem",
    "questId": 694,
    "map": "zephyrus",
    "ids": [
      116,
      117
    ]
  },
  {
    "kind": "kill",
    "questId": 698,
    "map": "forest",
    "monsters": [
      "Zardman Grunt"
    ]
  },
  {
    "kind": "kill",
    "questId": 699,
    "map": "boxes",
    "monsters": [
      "Sneeviltron"
    ]
  },
  {
    "kind": "kill",
    "questId": 1171,
    "map": "moonyard",
    "monsters": [
      "Junkyard Wall"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1172,
    "map": "moonyard",
    "ids": [
      495
    ]
  },
  {
    "kind": "kill",
    "questId": 1173,
    "map": "moonyardb",
    "monsters": [
      "Robo Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 1177,
    "map": "marsh2",
    "monsters": [
      "Lesser Shadow Serpent"
    ]
  },
  {
    "kind": "kill",
    "questId": 1178,
    "map": "marsh2",
    "monsters": [
      "Lesser Groglurk"
    ]
  },
  {
    "kind": "chain",
    "questId": 2168
  },
  {
    "kind": "chain",
    "questId": 2169
  },
  {
    "kind": "chain",
    "questId": 2170
  },
  {
    "kind": "chain",
    "questId": 2171
  },
  {
    "kind": "kill",
    "questId": 2173,
    "map": "djinn",
    "monsters": [
      "Harpy"
    ]
  },
  {
    "kind": "plan",
    "questId": 2830,
    "actions": [
      {
        "kind": "hunt",
        "map": "xantown",
        "cell": "Enter",
        "pad": "Spawn",
        "monster": "*",
        "item": "Flare Artifact"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2831,
    "actions": [
      {
        "kind": "packet",
        "packet": "%xt%zm%updateQuest%1%811%"
      },
      {
        "kind": "hunt",
        "map": "sandsea",
        "monster": "Cactus Creeper",
        "item": "Cactus Creeper Oil",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "cloister",
        "cell": "r2",
        "pad": "Right",
        "monster": "*",
        "item": "Acornent Oil",
        "quantity": 3
      },
      {
        "kind": "packet",
        "packet": "%xt%zm%updateQuest%1%1176%"
      },
      {
        "kind": "hunt",
        "map": "moonyardb",
        "cell": "r4",
        "pad": "Left",
        "monster": "*",
        "item": "Robo Dog Oil",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "farm",
        "cell": "Crop1",
        "pad": "Left",
        "monster": "*",
        "item": "Scarecrow Canola Oil",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2832,
    "actions": [
      {
        "kind": "hunt",
        "map": "arcangrove",
        "cell": "LeftBack",
        "pad": "Left",
        "monster": "Gorillaphant",
        "item": "Bag of Peanuts",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "earthstorm",
        "cell": "r9",
        "pad": "Left",
        "monster": "Amethite",
        "item": "Stick of Rock Candy",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "palooza",
        "cell": "Act1",
        "pad": "Left",
        "monster": "Tune-a-Fish",
        "item": "Tune-A-Fish Tuna Can",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "giant",
        "cell": "r1",
        "pad": "Left",
        "monster": "*",
        "item": "Bag of Pretzels",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2833,
    "actions": [
      {
        "kind": "hunt",
        "map": "bamboo",
        "cell": "r3",
        "pad": "Left",
        "monster": "Tanuki",
        "item": "Umeboshi Plum",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "yokaigrave",
        "cell": "Enter2",
        "pad": "Right",
        "monster": "*",
        "item": "Ginger"
      },
      {
        "kind": "hunt",
        "map": "guru",
        "cell": "Field2",
        "pad": "Left",
        "monster": "*",
        "item": "Peppermint Leaf",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2833,
    "actions": [
      {
        "kind": "buy",
        "map": "yulgar",
        "shopId": 16,
        "item": "Absorbent Mop"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 2833
  },
  {
    "kind": "plan",
    "questId": 2834,
    "actions": [
      {
        "kind": "buy",
        "map": "thespan",
        "shopId": 439,
        "item": "Comfy Pillow"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2837,
    "map": "hyperspace",
    "ids": [
      1742
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2838,
    "map": "hyperspace",
    "ids": [
      1743
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2839,
    "map": "hyperspace",
    "ids": [
      1744
    ]
  },
  {
    "kind": "chain",
    "questId": 2856
  },
  {
    "kind": "mapItem",
    "questId": 2840,
    "map": "hyperspace",
    "ids": [
      1745
    ]
  },
  {
    "kind": "kill",
    "questId": 2841,
    "map": "alley",
    "monsters": [
      "Trash Can"
    ]
  },
  {
    "kind": "kill",
    "questId": 2842,
    "map": "alley",
    "monsters": [
      "Thug Bully"
    ]
  },
  {
    "kind": "kill",
    "questId": 2843,
    "map": "alley",
    "monsters": [
      "Thug Bully"
    ]
  },
  {
    "kind": "kill",
    "questId": 2849,
    "map": "alley",
    "monsters": [
      "Thug Boss"
    ]
  },
  {
    "kind": "kill",
    "questId": 2844,
    "map": "alley",
    "monsters": [
      "Security Cam",
      " Guard Robot"
    ]
  },
  {
    "kind": "kill",
    "questId": 2845,
    "map": "alley",
    "monsters": [
      "Guard Dog Robot"
    ]
  },
  {
    "kind": "kill",
    "questId": 2846,
    "map": "alley",
    "monsters": [
      "Guard Dog Robot"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2850,
    "map": "hyperspace",
    "ids": [
      1751
    ]
  },
  {
    "kind": "kill",
    "questId": 2851,
    "map": "alley",
    "monsters": [
      "Thug Minion"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2852,
    "map": "hyperspace",
    "ids": [
      1749
    ]
  },
  {
    "kind": "chain",
    "questId": 2858
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.j6saga",
    category: "Story",
    map: "zephyrus",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
