// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Lae Wedding Story",
  "description": "This will finish the Lae Wedding Story.",
  "tags": [
    "story",
    "quest",
    "lae-wedding",
    "they",
    "lae",
    "wedding",
    "laewed"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 9944,
    "map": "laewed",
    "ids": [
      13769,
      13770
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9946,
    "map": "laewed",
    "ids": [
      13771,
      13772
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9948,
    "map": "laewed",
    "ids": [
      13773,
      13774
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9949,
    "map": "laewed",
    "ids": [
      13775
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9950,
    "map": "laewed",
    "ids": [
      13776
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.lae-wedding",
    category: "Story",
    map: "laewed",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
