// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Lightovia Cave Story",
  "description": "This will finish the Lightovia Cave Story.",
  "tags": [
    "story",
    "quest",
    "lightovia-cave",
    "lightovia",
    "cave"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7123,
    "map": "ShadowVoid",
    "monsters": [
      "Light Matter"
    ]
  },
  {
    "kind": "kill",
    "questId": 7124,
    "map": "ShadowVoid",
    "monsters": [
      "Shadowsprite"
    ]
  },
  {
    "kind": "kill",
    "questId": 7125,
    "map": "ShadowVoid",
    "monsters": [
      "Light Matter"
    ]
  },
  {
    "kind": "kill",
    "questId": 7126,
    "map": "ShadowVoid",
    "monsters": [
      "Shadowfiend"
    ]
  },
  {
    "kind": "kill",
    "questId": 7127,
    "map": "ShadowVoid",
    "monsters": [
      "Shadowfiend"
    ]
  },
  {
    "kind": "kill",
    "questId": 7128,
    "map": "ShadowVoid",
    "monsters": [
      "Shadowfiend",
      "Light Matter"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7129,
    "map": "ShadowVoid",
    "ids": [
      6765
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7130,
    "map": "ShadowVoid",
    "ids": [
      6766
    ]
  },
  {
    "kind": "kill",
    "questId": 7130,
    "map": "ShadowVoid",
    "monsters": [
      "Light Matter"
    ]
  },
  {
    "kind": "kill",
    "questId": 7131,
    "map": "ShadowVoid",
    "monsters": [
      "Fragment of Doom"
    ]
  },
  {
    "kind": "kill",
    "questId": 7132,
    "map": "LightoviaCave",
    "monsters": [
      "Imbalanced Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7133,
    "map": "LightoviaCave",
    "ids": [
      6767
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7133,
    "map": "LightoviaCave",
    "monsters": [
      "Imbalanced Mage"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7134,
    "map": "LightoviaCave",
    "ids": [
      6768
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7135,
    "map": "LightoviaCave",
    "monsters": [
      "Imbalanced Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 7136,
    "map": "LightoviaCave",
    "monsters": [
      "Evil ArchMage Brentan"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.lightovia-cave",
    category: "Story",
    map: "ShadowVoid",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
