// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Magic Thief Story",
  "description": "This will finish the Magic Thief Story.",
  "tags": [
    "story",
    "quest",
    "magic-thief",
    "magic",
    "thief"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 1908,
    "map": "twilightslums",
    "ids": [
      952
    ]
  },
  {
    "kind": "kill",
    "questId": 1909,
    "map": "twilightslums",
    "monsters": [
      "Subrysa"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1910,
    "map": "twilightslums",
    "ids": [
      954
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1911,
    "map": "palace",
    "ids": [
      955
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1912,
    "map": "palace",
    "ids": [
      956
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1913,
    "map": "twilightslums",
    "ids": [
      957
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1914,
    "map": "twilightslums",
    "ids": [
      958
    ]
  },
  {
    "kind": "plan",
    "questId": 1915,
    "actions": [
      {
        "kind": "hunt",
        "map": "palace",
        "monster": "Deorysa",
        "item": "Deorysa Slain",
        "quantity": 15
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 1916
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.magic-thief",
    category: "Story",
    map: "twilightslums",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
