// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Musty Cave Story",
  "description": "This will finish the Musty Cave Story.",
  "tags": [
    "story",
    "quest",
    "musty-cave",
    "musty",
    "cave"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7034,
    "map": "redfurvalley",
    "monsters": [
      "Guard Drone"
    ]
  },
  {
    "kind": "kill",
    "questId": 7035,
    "map": "redfurvalley",
    "monsters": [
      "Harvester Drone"
    ]
  },
  {
    "kind": "kill",
    "questId": 7036,
    "map": "redfurvalley",
    "monsters": [
      "Spy Drone"
    ]
  },
  {
    "kind": "plan",
    "questId": 7037,
    "actions": [
      {
        "kind": "buy",
        "map": "nibbleon",
        "shopId": 1553,
        "item": "Makai-Sun"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7038,
    "map": "mustycave",
    "ids": [
      6588
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7039,
    "map": "mustycave",
    "ids": [
      6589
    ]
  },
  {
    "kind": "kill",
    "questId": 7039,
    "map": "mustycave",
    "monsters": [
      "Guard Drone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7040,
    "map": "mustycave",
    "ids": [
      6590
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7041,
    "map": "mustycave",
    "monsters": [
      "Harvester Drone"
    ]
  },
  {
    "kind": "kill",
    "questId": 7042,
    "map": "mustycave",
    "monsters": [
      "Spy Drone"
    ]
  },
  {
    "kind": "kill",
    "questId": 7043,
    "map": "nibbleon",
    "monsters": [
      "Void Mage"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7044,
    "map": "mustycave",
    "ids": [
      6591,
      6592,
      6593,
      6594
    ]
  },
  {
    "kind": "kill",
    "questId": 7045,
    "map": "mustycave",
    "monsters": [
      "Guard Drone"
    ]
  },
  {
    "kind": "kill",
    "questId": 7046,
    "map": "mustycave",
    "monsters": [
      "Guard Drone"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7047,
    "map": "mustycave",
    "ids": [
      6595
    ]
  },
  {
    "kind": "kill",
    "questId": 7048,
    "map": "mustycave",
    "monsters": [
      "Mogdring"
    ]
  },
  {
    "kind": "plan",
    "questId": 7049,
    "actions": [
      {
        "kind": "hunt",
        "map": "mustycave",
        "monster": "Mogdring",
        "item": "Golden Gear",
        "quantity": 5,
        "isTemp": false
      },
      {
        "kind": "hunt",
        "map": "mustycave",
        "monster": "Spy Drone",
        "item": "Aura Core",
        "quantity": 25,
        "isTemp": false
      },
      {
        "kind": "hunt",
        "map": "mustycave",
        "monster": "Guard Drone",
        "item": "Dimension Stabilizer",
        "quantity": 35,
        "isTemp": false
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.musty-cave",
    category: "Story",
    map: "redfurvalley",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
