// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Poison Forest Story",
  "description": "This will finish the Poison Forest Story.",
  "tags": [
    "story",
    "quest",
    "poison-forest",
    "poison",
    "forest"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 1058,
    "map": "Manor",
    "monsters": [
      "Amethyst Golem"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1059,
    "map": "Manor",
    "ids": [
      403
    ],
    "quantity": 10
  },
  {
    "kind": "mapItem",
    "questId": 1060,
    "map": "Manor",
    "ids": [
      402
    ]
  },
  {
    "kind": "kill",
    "questId": 1060,
    "map": "Manor",
    "monsters": [
      "Frigid Frogdrake"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1061,
    "map": "Manor",
    "ids": [
      404
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 1062,
    "map": "Manor",
    "monsters": [
      "Bird of Paradise"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1948,
    "map": "PoisonForest",
    "ids": [
      964
    ],
    "quantity": 3
  },
  {
    "kind": "mapItem",
    "questId": 1948,
    "map": "PoisonForest",
    "ids": [
      965
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 1948,
    "map": "PoisonForest",
    "monsters": [
      "Marsh Lurker",
      "Traitor Knight"
    ]
  },
  {
    "kind": "plan",
    "questId": 1949,
    "actions": [
      {
        "kind": "mapItem",
        "map": "PoisonForest",
        "id": 963,
        "quantity": 9
      },
      {
        "kind": "mapItem",
        "map": "PoisonForest",
        "id": 971,
        "quantity": 1
      },
      {
        "kind": "hunt",
        "map": "PoisonForest",
        "monster": "Marsh Lurker",
        "item": "Toxic Gallstones"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 1950,
    "actions": [
      {
        "kind": "mapItem",
        "map": "PoisonForest",
        "id": 966,
        "quantity": 1
      },
      {
        "kind": "hunt",
        "map": "PoisonForest",
        "monster": "Traitor Knight",
        "item": "Unbent Nail",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "PoisonForest",
        "monster": "Treeant",
        "item": "Sturdy Vine",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 1951,
    "actions": [
      {
        "kind": "mapItem",
        "map": "PoisonForest",
        "id": 967,
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "PoisonForest",
        "monster": "Burning Loyalist",
        "item": "Burning Loyalist Ember",
        "quantity": 15
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 1952,
    "map": "PoisonForest",
    "monsters": [
      "Burning Loyalist"
    ]
  },
  {
    "kind": "plan",
    "questId": 1953,
    "actions": [
      {
        "kind": "mapItem",
        "map": "PoisonForest",
        "id": 968,
        "quantity": 1
      },
      {
        "kind": "hunt",
        "map": "PoisonForest",
        "monster": "Traitor Knight",
        "item": "Guard Slain",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1954,
    "map": "PoisonForest",
    "ids": [
      970
    ]
  },
  {
    "kind": "kill",
    "questId": 1954,
    "map": "PoisonForest",
    "monsters": [
      "Traitor Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1955,
    "map": "PoisonForest",
    "ids": [
      969
    ],
    "quantity": 11
  },
  {
    "kind": "kill",
    "questId": 1955,
    "map": "PoisonForest",
    "monsters": [
      "Xavier Lionfang"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.poison-forest",
    category: "Story",
    map: "Manor",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
