// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "SkyGuard Saga Story",
  "description": "This will finish the SkyGuard Saga Story.",
  "tags": [
    "story",
    "quest",
    "skyguard-saga",
    "sky",
    "guard",
    "saga"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 883,
    "map": "airship",
    "monsters": [
      "Sky Pirate Draconian"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 884,
    "map": "airship",
    "ids": [
      217
    ],
    "quantity": 10
  },
  {
    "kind": "chain",
    "questId": 889
  },
  {
    "kind": "chain",
    "questId": 884
  },
  {
    "kind": "kill",
    "questId": 885,
    "map": "airship",
    "monsters": [
      "Rehydrated Gell Oh No"
    ]
  },
  {
    "kind": "kill",
    "questId": 886,
    "map": "airship",
    "monsters": [
      "Sky Pirate Dragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 887,
    "map": "airship",
    "monsters": [
      "Sky Pirate Draconian",
      "Rehydrated Gell Oh No",
      "Sky Pirate Dragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 888,
    "map": "airship",
    "monsters": [
      "Gladius"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1038,
    "map": "academy",
    "ids": [
      399
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1039,
    "map": "academy",
    "ids": [
      400
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 1039,
    "map": "academy",
    "monsters": [
      "Chaobold",
      "Bronze Sky Pirate"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1040,
    "map": "academy",
    "ids": [
      401
    ],
    "quantity": 15
  },
  {
    "kind": "kill",
    "questId": 1041,
    "map": "academy",
    "monsters": [
      "Inbunche"
    ]
  },
  {
    "kind": "kill",
    "questId": 1104,
    "map": "anders",
    "monsters": [
      "Dravir",
      "Copper Sky Pirate"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1105,
    "map": "anders",
    "ids": [
      439
    ],
    "quantity": 10
  },
  {
    "kind": "mapItem",
    "questId": 1105,
    "map": "anders",
    "ids": [
      440
    ],
    "quantity": 2
  },
  {
    "kind": "kill",
    "questId": 1105,
    "map": "anders",
    "monsters": [
      "Dravir",
      "Copper Sky Pirate"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1106,
    "map": "anders",
    "ids": [
      441
    ]
  },
  {
    "kind": "kill",
    "questId": 1106,
    "map": "anders",
    "monsters": [
      "Copper Sky Pirate",
      "Copper Sky Pirate",
      "Dravir"
    ]
  },
  {
    "kind": "kill",
    "questId": 1107,
    "map": "anders",
    "monsters": [
      "Iron Hoof"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1215,
    "map": "dreammaze",
    "ids": [
      519
    ]
  },
  {
    "kind": "kill",
    "questId": 1222,
    "map": "dreammaze",
    "monsters": [
      "Nightmare Lieutenant"
    ]
  },
  {
    "kind": "kill",
    "questId": 1286,
    "map": "strategy",
    "monsters": [
      "Dravir Pirate"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1287,
    "map": "strategy",
    "ids": [
      558
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1288,
    "map": "strategy",
    "ids": [
      559
    ]
  },
  {
    "kind": "kill",
    "questId": 1289,
    "map": "strategy",
    "monsters": [
      "Dravir Pirate Captain"
    ]
  },
  {
    "kind": "kill",
    "questId": 1290,
    "map": "strategy",
    "monsters": [
      "Dravir Pirate",
      "Dravir Pirate",
      "Dravir Pirate",
      "Dravir Pirate",
      "Dravir Pirate"
    ]
  },
  {
    "kind": "plan",
    "questId": 1696,
    "actions": [
      {
        "kind": "hunt",
        "map": "lair",
        "monster": "Golden Draconian",
        "item": "SkyPirate Base Key"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1697,
    "map": "piratebase",
    "ids": [
      896
    ],
    "quantity": 14
  },
  {
    "kind": "mapItem",
    "questId": 1697,
    "map": "piratebase",
    "ids": [
      895
    ]
  },
  {
    "kind": "kill",
    "questId": 1697,
    "map": "piratebase",
    "monsters": [
      "Security Sky Pirate"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1698,
    "map": "piratebase",
    "ids": [
      897
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 1698,
    "map": "piratebase",
    "monsters": [
      "Chaorrupted Sky Pirate"
    ]
  },
  {
    "kind": "kill",
    "questId": 1699,
    "map": "piratebase",
    "monsters": [
      "Chaorrupted Sky Pirate"
    ]
  },
  {
    "kind": "kill",
    "questId": 1700,
    "map": "piratebase",
    "monsters": [
      "Chaorrupted SkyGeneral"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2038,
    "map": "highcommand",
    "ids": [
      997
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 2038,
    "map": "highcommand",
    "monsters": [
      "Storagebox",
      "Bronze Sky Pirate"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2039,
    "map": "highcommand",
    "ids": [
      1000
    ]
  },
  {
    "kind": "kill",
    "questId": 2040,
    "map": "highcommand",
    "monsters": [
      "Bronze Sky Pirate",
      "Chaorrupted Invader"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2043,
    "map": "highcommand",
    "ids": [
      996
    ],
    "quantity": 10
  },
  {
    "kind": "mapItem",
    "questId": 2043,
    "map": "highcommand",
    "ids": [
      998,
      999
    ]
  },
  {
    "kind": "kill",
    "questId": 2041,
    "map": "piratebase",
    "monsters": [
      "Chaorrupted Sky Pirate",
      "Chaorrupted Sky Pirate"
    ]
  },
  {
    "kind": "kill",
    "questId": 2042,
    "map": "highcommand",
    "monsters": [
      "M3CH4-D34TH"
    ]
  },
  {
    "kind": "plan",
    "questId": 2248,
    "actions": [
      {
        "kind": "mapItem",
        "map": "bunker",
        "id": 1410,
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "bunker",
        "monster": "Subrysa",
        "item": "Subrysa Skin",
        "quantity": 5
      },
      {
        "kind": "hunt",
        "map": "bunker",
        "monster": "Hootbear",
        "item": "Hootbeak",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2249,
    "actions": [
      {
        "kind": "mapItem",
        "map": "bunker",
        "id": 1411,
        "quantity": 7
      },
      {
        "kind": "mapItem",
        "map": "bunker",
        "id": 1412,
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "bunker",
        "monster": "Tainted Emu",
        "item": "Emu Spine",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "bunker",
        "monster": "Koalion",
        "item": "Koalion Claw",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2250,
    "actions": [
      {
        "kind": "hunt",
        "map": "bloodtusk",
        "monster": "Rhison",
        "item": "Rhison Hoof",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2251,
    "actions": [
      {
        "kind": "hunt",
        "map": "palace",
        "monster": "Subrysa",
        "item": "Subrysa Corpse",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "bunker",
        "monster": "Koalion",
        "item": "Koalion Corpse",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "bunker",
        "monster": "Tainted Emu",
        "item": "Tainted Emu Corpse",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "bunker",
        "monster": "Hootbear",
        "item": "Hootbear Corpse",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 2252,
    "map": "bunker",
    "monsters": [
      "Chaos Beast Attempt"
    ]
  },
  {
    "kind": "plan",
    "questId": 2484,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosguard",
        "monster": "Chaos Skylord",
        "item": "Defeated SkyLord",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "chaosguard",
        "monster": "Chaos Commander",
        "item": "Defeated Commander",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2486,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosguard",
        "monster": "Sky Spy-Eye",
        "item": "Defeated Sky Spy-Eye",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 2489,
    "actions": [
      {
        "kind": "mapItem",
        "map": "chaosguard",
        "id": 1553,
        "quantity": 1
      },
      {
        "kind": "hunt",
        "map": "chaosguard",
        "monster": "Chaos Skywatcher",
        "item": "SkyWatcher Defeated"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 2482
  },
  {
    "kind": "kill",
    "questId": 2487,
    "map": "chaosguard",
    "monsters": [
      "Exos"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.sky-guard-saga",
    category: "Story",
    map: "airship",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
