// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Spire Past Story",
  "description": "This will finish the Spire Past Story.",
  "tags": [
    "story",
    "quest",
    "spirepast",
    "spire",
    "past"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 6824,
    "map": "dreadrock",
    "monsters": [
      "Azal the Infernal"
    ]
  },
  {
    "kind": "kill",
    "questId": 6825,
    "map": "spirepast",
    "monsters": [
      "Infernal Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 6826,
    "map": "spirepast",
    "monsters": [
      "Infernal Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 6827,
    "map": "spirepast",
    "monsters": [
      "Rookie Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 6828,
    "map": "spirepast",
    "monsters": [
      "Infernal Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 6829,
    "map": "spirepast",
    "monsters": [
      "Celestial Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6830,
    "map": "spirepast",
    "monsters": [
      "Celestial Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6831,
    "map": "spirepast",
    "monsters": [
      "Infernal Guard",
      "Infernal Hound"
    ]
  },
  {
    "kind": "kill",
    "questId": 6832,
    "map": "spirepast",
    "monsters": [
      "Infernal Hound"
    ]
  },
  {
    "kind": "kill",
    "questId": 6833,
    "map": "spirepast",
    "monsters": [
      "Celestial Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6834,
    "map": "spirepast",
    "monsters": [
      "Infernal Guard Captain"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.spire-past",
    category: "Story",
    map: "dreadrock",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
