// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Tavern",
  "description": "Quest from `Ulfgar Geirsson` in /tavern",
  "tags": [
    "story",
    "tavern",
    "ulfgar geirsson"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 3176,
    "map": "sandport",
    "monsters": [
      "Tomb Robber"
    ]
  },
  {
    "kind": "kill",
    "questId": 3177,
    "map": "mythsong",
    "monsters": [
      "French Horned Toadragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 3178,
    "map": "crashsite",
    "monsters": [
      "Barrier Bot"
    ]
  },
  {
    "kind": "kill",
    "questId": 3179,
    "map": "natatorium",
    "monsters": [
      "Anglerfish"
    ]
  },
  {
    "kind": "kill",
    "questId": 3180,
    "map": "battleundera",
    "monsters": [
      "Bone Terror"
    ]
  },
  {
    "kind": "kill",
    "questId": 3181,
    "map": "kingcoal",
    "monsters": [
      "Frost King"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.tavern",
    category: "Story",
    map: "sandport",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
