// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Third Spell Story",
  "description": "This will finish the Third Spell Story.",
  "tags": [
    "story",
    "quest",
    "thirdspell",
    "third",
    "spell"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 4474,
    "actions": [
      {
        "kind": "hunt",
        "map": "doomwood",
        "monster": "Doomwood Treeant",
        "item": "Braaaainz",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4475,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Mana Phoenix",
        "item": "Mana Plane Monster Defeated",
        "quantity": 12
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4476,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Mana Phoenix",
        "item": "Proxy Eggs",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4477,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3668,
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4478,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Mana Phoenix",
        "item": "Elemental Pathway Cleared",
        "quantity": 20
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4479,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Mana Phoenix",
        "item": "Green Eye",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4480,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3671
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4481,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3675
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4482,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Mana Phoenix",
        "item": "Abducted Mana Phoenix"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4483,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3672
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4484,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Great Solar Elemental",
        "item": "Great Solar Elemental Defeated"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4485,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Mana Phoenix",
        "item": "Mana Phoenix Egg",
        "quantity": 7
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4486,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Great Solar Elemental",
        "item": "Great Solar Elemental Defeated Again"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4487,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3673,
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4488,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "cell": "r12",
        "pad": "Left",
        "monster": "Living Fire",
        "item": "Sun Monster Ember",
        "quantity": 15
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4489,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Sun Flare",
        "item": "Sun Flare Defeated",
        "quantity": 10
      },
      {
        "kind": "hunt",
        "map": "thirdspell",
        "cell": "r12",
        "pad": "Left",
        "monster": "Living Fire",
        "item": "Living Fire Defeated",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4490,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3674
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4491,
    "actions": [
      {
        "kind": "hunt",
        "map": "thirdspell",
        "monster": "Solar Incarnation ",
        "item": "Heart of the Sun Received"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4492,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3676
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4493,
    "actions": [
      {
        "kind": "mapItem",
        "map": "thirdspell",
        "id": 3677
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.third-spell",
    category: "Story",
    map: "doomwood",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
