// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Tournament Story",
  "description": "This will finish the Tournament Story.",
  "tags": [
    "story",
    "quest",
    "tournament"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 2708,
    "map": "tournament",
    "ids": [
      1682
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 2708,
    "map": "tournament",
    "monsters": [
      "Suspicious Spy Bot"
    ]
  },
  {
    "kind": "kill",
    "questId": 2709,
    "map": "tournament",
    "monsters": [
      "Mercenary",
      "SandStalker"
    ]
  },
  {
    "kind": "kill",
    "questId": 2710,
    "map": "tournament",
    "monsters": [
      "Greenguard Bandit"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2711,
    "map": "tournament",
    "ids": [
      1683
    ]
  },
  {
    "kind": "kill",
    "questId": 2711,
    "map": "tournament",
    "monsters": [
      "Princess Tara"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 2712,
    "map": "tournament",
    "ids": [
      1684
    ]
  },
  {
    "kind": "kill",
    "questId": 2713,
    "map": "tournament",
    "monsters": [
      "Khai Khaldun"
    ]
  },
  {
    "kind": "kill",
    "questId": 2714,
    "map": "tournament",
    "monsters": [
      "Johann Wryce"
    ]
  },
  {
    "kind": "kill",
    "questId": 2715,
    "map": "tournament",
    "monsters": [
      "Knight of Thorns"
    ]
  },
  {
    "kind": "kill",
    "questId": 2716,
    "map": "tournament",
    "monsters": [
      "Roderick"
    ]
  },
  {
    "kind": "kill",
    "questId": 2717,
    "map": "tournament",
    "monsters": [
      "Lord Brentan"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.tournament",
    category: "Story",
    map: "tournament",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
