// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Tower Story (Member)",
  "description": "This will finish the Tower Story.",
  "tags": [
    "story",
    "quest",
    "tower",
    "member",
    "mem"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 1603,
    "map": "trunk",
    "monsters": [
      "GreenGuard Basilisk"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1604,
    "map": "tower",
    "ids": [
      836
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 1605,
    "map": "tower",
    "ids": [
      837
    ]
  },
  {
    "kind": "kill",
    "questId": 1606,
    "map": "greenguardeast",
    "monsters": [
      "Spider"
    ]
  },
  {
    "kind": "kill",
    "questId": 1607,
    "map": "tower",
    "monsters": [
      "Strange Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1608,
    "map": "tower",
    "ids": [
      838
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1609,
    "map": "tower",
    "ids": [
      839
    ],
    "quantity": 12
  },
  {
    "kind": "plan",
    "questId": 1610,
    "actions": [
      {
        "kind": "hunt",
        "map": "tower",
        "monster": 6,
        "item": "Baxter Defeated!"
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.tower-mem",
    category: "Story",
    map: "trunk",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
