// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Tower of Doom Story",
  "description": "This will finish the Tower of Doom Story.",
  "tags": [
    "story",
    "quest",
    "tower-of-doom",
    "tower",
    "of",
    "doom"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 3475,
    "map": "towerofdoom",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3476,
    "map": "towerofdoom2",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3477,
    "map": "towerofdoom3",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3478,
    "map": "towerofdoom4",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3479,
    "map": "towerofdoom5",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3480,
    "map": "towerofdoom6",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3481,
    "map": "towerofdoom7",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3482,
    "map": "towerofdoom8",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3483,
    "map": "towerofdoom9",
    "monsters": [
      "*"
    ]
  },
  {
    "kind": "kill",
    "questId": 3484,
    "map": "towerofdoom10",
    "monsters": [
      "*"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.tower-of-doom",
    category: "Story",
    map: "towerofdoom",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
