// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Tutorial Story",
  "description": "This will finish the Tutorial Story.",
  "tags": [
    "story",
    "quest",
    "tutorial"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "achievements",
    "map": "oaklore",
    "ids": [
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31
    ],
    "labels": [
      "Combat",
      "Interact",
      "Quest",
      "Skill",
      "Shop",
      "Enhance",
      "Rest",
      "World",
      "Emotes",
      "Travel"
    ],
    "stopIfHas": 31
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.tutorial",
    category: "Story",
    map: "oaklore",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
