// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Vasalkar Lair War Story",
  "description": "This will finish the Vasalkar Lair War Story.",
  "tags": [
    "story",
    "quest",
    "vasalkar",
    "lair",
    "war"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 6687,
    "map": "lairdefend",
    "monsters": [
      "Soul Wyvern"
    ]
  },
  {
    "kind": "plan",
    "questId": 6688,
    "actions": [
      {
        "kind": "hunt",
        "map": "lairdefend",
        "monster": "Dragon Summoner",
        "item": "Dragon Claw",
        "quantity": 3,
        "isTemp": true
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 6689,
    "map": "lairdefend",
    "monsters": [
      "Flame Dragon General"
    ]
  },
  {
    "kind": "kill",
    "questId": 6692,
    "map": "lairattack",
    "monsters": [
      "Dracomancer"
    ]
  },
  {
    "kind": "kill",
    "questId": 6693,
    "map": "lairattack",
    "monsters": [
      "Dragon Defender"
    ]
  },
  {
    "kind": "kill",
    "questId": 6694,
    "map": "lairattack",
    "monsters": [
      "Flame Dragon General"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.vasalkar-lair-war",
    category: "Story",
    map: "lairdefend",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
