// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "./runner.js";

export const meta = {
  "name": "Victor Matsuri",
  "description": "This script will complete the Empress Ai No Miko's questline in /victormatsuri.",
  "tags": [
    "story",
    "victor matsuri",
    "victormatsuri",
    "empress ai no miko",
    "ai no miko",
    "matsuri",
    "victor",
    "rite of ascension",
    "rite",
    "victor of the festival",
    "eclipse"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 10290,
    "map": "victormatsuri",
    "monsters": [
      "Kitsune Himawari"
    ]
  },
  {
    "kind": "kill",
    "questId": 10291,
    "map": "victormatsuri",
    "monsters": [
      "NeOni"
    ]
  },
  {
    "kind": "kill",
    "questId": 10292,
    "map": "victormatsuri",
    "monsters": [
      "Narcis Arrhythmia"
    ]
  },
  {
    "kind": "kill",
    "questId": 10293,
    "map": "victormatsuri",
    "monsters": [
      "Haruki Matsuoka"
    ]
  },
  {
    "kind": "kill",
    "questId": 10294,
    "map": "victormatsuri",
    "monsters": [
      "Lady Laidronette"
    ]
  },
  {
    "kind": "plan",
    "questId": 10295,
    "actions": []
  },
  {
    "kind": "chain",
    "questId": 10295
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.victor-matsuri",
    category: "Story",
    map: "victormatsuri",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
