// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Feverfew",
  "description": "This will finish the Feverfew quest.",
  "tags": [
    "story",
    "quest",
    "fire-island",
    "feverfew",
    "fireisland",
    "03feverfew"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 4054,
    "map": "Embersea",
    "monsters": [
      "Flame Soldier",
      "Storm Scout"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4055,
    "map": "Embersea",
    "ids": [
      3153
    ],
    "quantity": 22
  },
  {
    "kind": "kill",
    "questId": 4055,
    "map": "Embersea",
    "monsters": [
      "Living Lava"
    ]
  },
  {
    "kind": "kill",
    "questId": 4056,
    "map": "Embersea",
    "monsters": [
      "Coal Creeper",
      "Pyradon",
      "Fyresyn"
    ]
  },
  {
    "kind": "kill",
    "questId": 4070,
    "map": "pyrewatch",
    "monsters": [
      "Lavazard",
      "Fyreborn Tiger",
      "Caustocrush"
    ]
  },
  {
    "kind": "kill",
    "questId": 4071,
    "map": "pyrewatch",
    "monsters": [
      "Fire Pikeman"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4072,
    "map": "pyrewatch",
    "ids": [
      3159
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 4073,
    "map": "pyrewatch",
    "monsters": [
      "Firestorm Knight",
      "Firestorm Knight"
    ]
  },
  {
    "kind": "plan",
    "questId": 4074,
    "actions": [
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Fire Pikeman",
        "item": "Pikeman Slain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Fire Pikeman",
        "item": "Firestorm Helm",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Flame Soldier",
        "item": "Flame Soldier Slain",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Caustocrush",
        "item": "Caustocrush Slain",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4075,
    "map": "pyrewatch",
    "ids": [
      3160
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 4075,
    "map": "pyrewatch",
    "monsters": [
      "Lavazard"
    ]
  },
  {
    "kind": "plan",
    "questId": 4076,
    "actions": [
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Lavazard",
        "item": "Kindling",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Caustocrush",
        "item": "Flint and Steel"
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Coal Creeper",
        "item": "Coal",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4077,
    "actions": [
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Lavazard",
        "item": "Wickskin Root",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Lavazard",
        "item": "Zard Marrow",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Living Lava",
        "item": "Living Lava Blood",
        "quantity": 2
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4077,
    "map": "Pyrewatch",
    "ids": [
      3161
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 4078,
    "map": "Pyrewatch",
    "monsters": [
      "Storm Scout"
    ]
  },
  {
    "kind": "plan",
    "questId": 4079,
    "actions": [
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Storm Scout",
        "item": "Polish"
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Flame Soldier",
        "item": "Cloth"
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Flame Soldier",
        "item": "Stand Legs",
        "quantity": 8
      },
      {
        "kind": "hunt",
        "map": "Pyrewatch",
        "monster": "Fyreborn Tiger",
        "item": "Reflectors",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4080,
    "map": "Pyrewatch",
    "ids": [
      3162
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 4081,
    "map": "Pyrewatch",
    "monsters": [
      "Storm Scout"
    ]
  },
  {
    "kind": "kill",
    "questId": 4128,
    "map": "feverfew",
    "monsters": [
      "Firestorm Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 4129,
    "map": "feverfew",
    "monsters": [
      "Locked Chest"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4130,
    "map": "feverfew",
    "ids": [
      3246,
      3247
    ]
  },
  {
    "kind": "chain",
    "questId": 4130
  },
  {
    "kind": "mapItem",
    "questId": 4131,
    "map": "feverfew",
    "ids": [
      3245
    ]
  },
  {
    "kind": "kill",
    "questId": 4131,
    "map": "feverfew",
    "monsters": [
      "Firestorm Knight",
      "Firestorm Major",
      "Firestorm Knight",
      "Firestorm Major"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4132,
    "map": "feverfew",
    "ids": [
      3244
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 4133,
    "map": "feverfew",
    "ids": [
      3243
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 4133,
    "map": "feverfew",
    "monsters": [
      "Twisted Undine"
    ]
  },
  {
    "kind": "plan",
    "questId": 4134,
    "actions": [
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Salamander",
        "item": "Salamander Tongue",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Feverfew Vase",
        "item": "Adderoot Powder",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Twisted Undine",
        "item": "Shadowbane Brine",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Coral Creeper",
        "item": "Charred Claw",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Firestorm Knight",
        "item": "Whispered Regret"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4135,
    "map": "feverfew",
    "ids": [
      3248
    ]
  },
  {
    "kind": "kill",
    "questId": 4136,
    "map": "feverfew",
    "monsters": [
      "Blazebinder"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4137,
    "map": "feverfew",
    "ids": [
      3242
    ],
    "quantity": 10
  },
  {
    "kind": "plan",
    "questId": 4138,
    "actions": []
  },
  {
    "kind": "plan",
    "questId": 4138,
    "actions": [
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Salamander",
        "item": "Burning Ember",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Coral Creeper",
        "item": "Stoneskin Shard",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Firestorm Knight",
        "item": "Last Breath",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "feverfew",
        "monster": "Twisted Undine",
        "item": "Undine's Tear",
        "quantity": 3
      },
      {
        "kind": "jump",
        "cell": "Cut2",
        "pad": "Left"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4139,
    "map": "feverfew",
    "monsters": [
      "Feverfew Vase",
      "Twisted Undine",
      "Locked Chest"
    ]
  },
  {
    "kind": "kill",
    "questId": 4140,
    "map": "feverfew",
    "monsters": [
      "Coral Creeper",
      "Twisted Undine",
      "Salamander"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4141,
    "map": "feverfew",
    "ids": [
      3241
    ]
  },
  {
    "kind": "kill",
    "questId": 4142,
    "map": "feverfew",
    "monsters": [
      "Major Thermas"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.fireisland.03feverfew",
    category: "Story",
    map: "Embersea",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
