// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Nightmare",
  "description": "This will finish the Nightmare quest.",
  "tags": [
    "story",
    "quest",
    "fire-island",
    "nightmare",
    "member",
    "fireisland",
    "08nightmare"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 4143,
    "map": "Nightmare",
    "monsters": [
      "Bobble Clown"
    ]
  },
  {
    "kind": "kill",
    "questId": 4144,
    "map": "Nightmare",
    "monsters": [
      "Crazy Clown"
    ]
  },
  {
    "kind": "kill",
    "questId": 4145,
    "map": "Nightmare",
    "monsters": [
      "Castle Spider"
    ]
  },
  {
    "kind": "plan",
    "questId": 4146,
    "actions": [
      {
        "kind": "hunt",
        "map": "Nightmare",
        "monster": "Wrasp",
        "item": "Grappling Hook"
      },
      {
        "kind": "hunt",
        "map": "Nightmare",
        "monster": "Wrasp",
        "item": "Rope"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4147,
    "map": "Nightmare",
    "ids": [
      3262
    ]
  },
  {
    "kind": "kill",
    "questId": 4148,
    "map": "Nightmare",
    "monsters": [
      "Germs"
    ]
  },
  {
    "kind": "kill",
    "questId": 4149,
    "map": "Nightmare",
    "monsters": [
      "Needle"
    ]
  },
  {
    "kind": "kill",
    "questId": 4150,
    "map": "Nightmare",
    "monsters": [
      "Broken Toy"
    ]
  },
  {
    "kind": "plan",
    "questId": 4151,
    "actions": [
      {
        "kind": "hunt",
        "map": "Nightmare",
        "monster": "Unearthed Skeleton",
        "item": "Skeleton Deboned",
        "quantity": 8
      },
      {
        "kind": "hunt",
        "map": "Nightmare",
        "monster": "Rotfeeder Worm",
        "item": "Rotfeeder squished",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4152,
    "map": "Nightmare",
    "monsters": [
      "Fire Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 4153,
    "map": "Nightmare",
    "monsters": [
      "Flame Elemental"
    ]
  },
  {
    "kind": "plan",
    "questId": 4154,
    "actions": [
      {
        "kind": "hunt",
        "map": "Nightmare",
        "monster": "Anglerfish",
        "item": "Anglerfish Defeated",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "Nightmare",
        "monster": "Merdraconian",
        "item": "Merdraconian Defeated",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "Nightmare",
        "monster": "Deep Dweller",
        "item": "Deep Dweller defeated"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4155,
    "map": "Nightmare",
    "monsters": [
      "Unearthed Skeleton"
    ]
  },
  {
    "kind": "kill",
    "questId": 4156,
    "map": "Nightmare",
    "monsters": [
      "Nothing"
    ]
  },
  {
    "kind": "kill",
    "questId": 4157,
    "map": "Nightmare",
    "monsters": [
      "Devourax"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.fireisland.08nightmare-member",
    category: "Story",
    map: "Nightmare",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
