// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Story5[Place Holder]",
  "description": "Runs the Story5[Place Holder] story route.",
  "tags": [
    "story",
    "shadowsof",
    "doom",
    "oct",
    "13th",
    "story5",
    "place",
    "holder"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [];

export const definition = defineGeneratedStory(
  {
    id: "story.shadowsof-doom-oct-13th.story5-place-holder",
    category: "Story",
    map: "holder",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
