// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../../runner.js";

export const meta = {
  "name": "Temple of the Light",
  "description": "This will finish the Temple of the Light quest.",
  "tags": [
    "story",
    "quest",
    "doomwood",
    "temple-of-the-light",
    "part1",
    "5temple",
    "of",
    "light"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 1123,
    "actions": [
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r2",
        "pad": "Up",
        "monster": "SlimeSkull",
        "item": "Slimeskull Trophy",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r2",
        "pad": "Up",
        "monster": "Doomwood Bonemuncher",
        "item": "Munched Boneshard",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r2",
        "pad": "Up",
        "monster": "Shelleton",
        "item": "Shelleton Shrapnel",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 1124,
    "actions": [
      {
        "kind": "mapItem",
        "map": "temple",
        "id": 456,
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r3",
        "pad": "Up",
        "monster": "Undead Mage",
        "item": "Necrotic Rune",
        "quantity": 3
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r3",
        "pad": "Up",
        "monster": "Doomwood Ectomancer",
        "item": "Ecto-Covered Rune",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 1125,
    "actions": [
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r4",
        "pad": "Up",
        "monster": "Ghoul",
        "item": "Ghoulish Gear"
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r4",
        "pad": "Up",
        "monster": "Lich",
        "item": "Haunted Habiliment"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 1126,
    "actions": [
      {
        "kind": "mapItem",
        "map": "temple",
        "id": 457,
        "quantity": 8
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r5",
        "pad": "Up",
        "monster": "Skeletal Fire Mage",
        "item": "Flame Extinguished",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 1127,
    "map": "temple",
    "monsters": [
      "Doomwood Ectomancer"
    ]
  },
  {
    "kind": "plan",
    "questId": 1128,
    "actions": [
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r2",
        "pad": "Up",
        "monster": "Doomwood Bonemuncher",
        "item": "Masticated Mandible",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r7",
        "pad": "Up",
        "monster": "Sanguine Souleater",
        "item": "Freed Soul",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1129,
    "map": "temple",
    "ids": [
      458
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 1130,
    "map": "temple",
    "monsters": [
      "Doomwood Ectomancer",
      "Skeletal Fire Mage"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1131,
    "map": "temple",
    "ids": [
      459
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 1131,
    "map": "temple",
    "monsters": [
      "Ghoul"
    ]
  },
  {
    "kind": "kill",
    "questId": 1132,
    "map": "temple",
    "monsters": [
      "Doomwood Ectomancer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1133,
    "map": "temple",
    "ids": [
      460
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 1133,
    "map": "temple",
    "monsters": [
      "Sanguine Souleater"
    ]
  },
  {
    "kind": "kill",
    "questId": 1134,
    "map": "temple",
    "monsters": [
      "SlimeSkull",
      "Doomwood Ectomancer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1135,
    "map": "temple",
    "ids": [
      461
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 1137,
    "map": "temple",
    "monsters": [
      "Doomwood Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 1138,
    "map": "temple",
    "monsters": [
      "Ghoul"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1139,
    "map": "temple",
    "ids": [
      462
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 1140,
    "map": "temple",
    "monsters": [
      "Doomwood Bonemuncher",
      "Skeleton"
    ]
  },
  {
    "kind": "kill",
    "questId": 1141,
    "map": "temple",
    "monsters": [
      "Undead Mage",
      "Skeletal Fire Mage"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1142,
    "map": "temple",
    "ids": [
      463
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 1142,
    "map": "temple",
    "monsters": [
      "Shelleton",
      "Skeleton"
    ]
  },
  {
    "kind": "kill",
    "questId": 1143,
    "map": "temple",
    "monsters": [
      "Lich"
    ]
  },
  {
    "kind": "kill",
    "questId": 1144,
    "map": "temple",
    "monsters": [
      "Dracolich"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1145,
    "map": "temple",
    "ids": [
      464
    ],
    "quantity": 10
  },
  {
    "kind": "kill",
    "questId": 1146,
    "map": "temple",
    "monsters": [
      "Doomwood Bonemuncher"
    ]
  },
  {
    "kind": "kill",
    "questId": 1147,
    "map": "temple",
    "monsters": [
      "Cryptkeeper Lich"
    ]
  },
  {
    "kind": "plan",
    "questId": 1148,
    "actions": [
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r2",
        "pad": "Up",
        "monster": "Shelleton",
        "item": "Basilisk's Scale"
      },
      {
        "kind": "hunt",
        "map": "temple",
        "cell": "r2",
        "pad": "Up",
        "monster": "Shelleton",
        "item": "Scroll of Magic Inversion"
      },
      {
        "kind": "jump",
        "cell": "Enter",
        "pad": "Spawn"
      },
      {
        "kind": "buy",
        "map": "temple",
        "shopId": 287,
        "item": "Scroll of Cure Petrification"
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.doomwood.part1.5temple-of-light",
    category: "Story",
    map: "temple",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
