// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../../runner.js";

export const meta = {
  "name": "Mad Scientist Lab",
  "description": "This will finish the Mad Scientist Lab quest.",
  "tags": [
    "story",
    "quest",
    "doomwood",
    "mad-scientist-lab",
    "part1",
    "6mad",
    "scientist",
    "lab"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 1155,
    "map": "lab",
    "ids": [
      488
    ]
  },
  {
    "kind": "kill",
    "questId": 1156,
    "map": "lab",
    "monsters": [
      "Ant Giant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1157,
    "map": "lab",
    "ids": [
      489
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 1157,
    "map": "lab",
    "monsters": [
      "Ant Giant"
    ]
  },
  {
    "kind": "kill",
    "questId": 1158,
    "map": "lab",
    "monsters": [
      "Ant Giant"
    ]
  },
  {
    "kind": "kill",
    "questId": 1159,
    "map": "lab",
    "monsters": [
      "Ant Giant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1160,
    "map": "lab",
    "ids": [
      490
    ],
    "quantity": 6
  },
  {
    "kind": "mapItem",
    "questId": 1161,
    "map": "lab",
    "ids": [
      491
    ],
    "quantity": 7
  },
  {
    "kind": "kill",
    "questId": 1161,
    "map": "lab",
    "monsters": [
      "Giant Scorpion"
    ]
  },
  {
    "kind": "kill",
    "questId": 1162,
    "map": "lab",
    "monsters": [
      "Ant Giant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1163,
    "map": "lab",
    "ids": [
      492
    ],
    "quantity": 10
  },
  {
    "kind": "mapItem",
    "questId": 1164,
    "map": "mountain",
    "ids": [
      493
    ]
  },
  {
    "kind": "mapItem",
    "questId": 1169,
    "map": "mountain",
    "ids": [
      494
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.doomwood.part1.6mad-scientist-lab",
    category: "Story",
    map: "lab",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
