// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../../runner.js";

export const meta = {
  "name": "Dark Fortress",
  "description": "This will finish the Dark Fortress quest.",
  "tags": [
    "story",
    "quest",
    "legion",
    "dage-the-evil-island",
    "dark-fortress",
    "dage",
    "the",
    "evil",
    "island",
    "01dark",
    "fortress"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 4084,
    "map": "DarkFortress",
    "monsters": [
      "Dark Makai",
      "Cloaked Fiend"
    ]
  },
  {
    "kind": "plan",
    "questId": 4085,
    "actions": [
      {
        "kind": "hunt",
        "map": "DarkFortress",
        "monster": "Ninja Spy",
        "item": "Spy Slain",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "DarkFortress",
        "monster": "Cloaked Fiend",
        "item": "Elemental Slain",
        "quantity": 6
      },
      {
        "kind": "hunt",
        "map": "DarkFortress",
        "monster": "Cloaked Fiend",
        "item": "Cloaked Fiend Slain",
        "quantity": 6
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4086,
    "actions": [
      {
        "kind": "hunt",
        "map": "DarkFortress",
        "monster": "Infernalfiend",
        "item": "Ultra Dark Mystery Stone"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4088,
    "map": "DarkFortress",
    "monsters": [
      "Cloaked Fiend"
    ]
  },
  {
    "kind": "kill",
    "questId": 4089,
    "map": "DarkFortress",
    "monsters": [
      "Dark Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 4090,
    "map": "DarkFortress",
    "monsters": [
      "Dark Elemental",
      "Cloaked Fiend"
    ]
  },
  {
    "kind": "kill",
    "questId": 4091,
    "map": "DarkFortress",
    "monsters": [
      "Wilhelm"
    ]
  },
  {
    "kind": "kill",
    "questId": 4092,
    "map": "DarkFortress",
    "monsters": [
      "Dage The Evil"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.legion.dage-the-evil-island.01dark-fortress",
    category: "Story",
    map: "DarkFortress",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
