// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Complete 7 Deadly Dragons",
  "description": "This will complete the 7 Deadly Dragons story.",
  "tags": [
    "story",
    "quest",
    "7-deadly-dragons",
    "complete",
    "all",
    "7deadly",
    "dragons",
    "00seven",
    "deadly"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 5903,
    "map": "Gluttony",
    "monsters": [
      "Glutus"
    ]
  },
  {
    "kind": "kill",
    "questId": 5904,
    "map": "Gluttony",
    "monsters": [
      "Mucus"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5905,
    "map": "Gluttony",
    "ids": [
      5346
    ],
    "quantity": 2
  },
  {
    "kind": "kill",
    "questId": 5905,
    "map": "Gluttony",
    "monsters": [
      "Skeletal Slayer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5906,
    "map": "Gluttony",
    "ids": [
      5344
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5907,
    "map": "Gluttony",
    "ids": [
      5345
    ]
  },
  {
    "kind": "plan",
    "questId": 5908,
    "actions": [
      {
        "kind": "mapItem",
        "map": "Gluttony",
        "id": 5347,
        "quantity": 10
      },
      {
        "kind": "hunt",
        "map": "Gluttony",
        "cell": "r7",
        "pad": "Left",
        "monster": "Bowel Worm",
        "item": "Agitated Bowel Worm",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 5909,
    "actions": [
      {
        "kind": "hunt",
        "map": "Gluttony",
        "cell": "r6",
        "pad": "Left",
        "monster": "Bile",
        "item": "Falgar's Bones",
        "quantity": 9
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5910,
    "map": "Gluttony",
    "ids": [
      5348
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 5910,
    "map": "Gluttony",
    "monsters": [
      "Skeletal Slayer"
    ]
  },
  {
    "kind": "kill",
    "questId": 5911,
    "map": "Gluttony",
    "monsters": [
      "Bowel Worm",
      "Bile"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5912,
    "map": "Gluttony",
    "ids": [
      5349
    ]
  },
  {
    "kind": "kill",
    "questId": 5913,
    "map": "Gluttony",
    "monsters": [
      "Giant Tapeworm"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5914,
    "map": "Gluttony",
    "ids": [
      5350
    ]
  },
  {
    "kind": "kill",
    "questId": 5915,
    "map": "Gluttony",
    "monsters": [
      "Deflated Glutus"
    ]
  },
  {
    "kind": "kill",
    "questId": 5917,
    "map": "Pride",
    "monsters": [
      "Storm Drakel"
    ]
  },
  {
    "kind": "kill",
    "questId": 5918,
    "map": "Pride",
    "monsters": [
      "Ball Lightning"
    ]
  },
  {
    "kind": "kill",
    "questId": 5919,
    "map": "Pride",
    "monsters": [
      "Rubber Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 5920,
    "map": "Pride",
    "monsters": [
      "Cellar Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5921,
    "map": "Pride",
    "ids": [
      5351
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5921,
    "map": "Pride",
    "ids": [
      5352
    ],
    "quantity": 6
  },
  {
    "kind": "mapItem",
    "questId": 5922,
    "map": "Pride",
    "ids": [
      5353
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 5922,
    "map": "Pride",
    "monsters": [
      "Storm Drakel"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5923,
    "map": "Pride",
    "ids": [
      5354
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 5923,
    "map": "Pride",
    "monsters": [
      "Drakel Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5924,
    "map": "Pride",
    "ids": [
      5355
    ]
  },
  {
    "kind": "kill",
    "questId": 5924,
    "map": "Pride",
    "monsters": [
      "Elite Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5925,
    "map": "Pride",
    "ids": [
      5356
    ]
  },
  {
    "kind": "kill",
    "questId": 5925,
    "map": "Pride",
    "monsters": [
      "Storm Drakel"
    ]
  },
  {
    "kind": "kill",
    "questId": 5926,
    "map": "Pride",
    "monsters": [
      "Valsarian"
    ]
  },
  {
    "kind": "kill",
    "questId": 5934,
    "map": "Greed",
    "monsters": [
      "Sneevil Looter"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5935,
    "map": "Greed",
    "ids": [
      5372
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5936,
    "map": "Greed",
    "ids": [
      5373
    ]
  },
  {
    "kind": "kill",
    "questId": 5937,
    "map": "Greed",
    "monsters": [
      "Jelly-Like Cube"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5938,
    "map": "Greed",
    "ids": [
      5374
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 5939,
    "map": "Greed",
    "ids": [
      5377,
      5378
    ]
  },
  {
    "kind": "kill",
    "questId": 5940,
    "map": "Greed",
    "monsters": [
      "Ice Crystal",
      "Glacial Horror"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5941,
    "map": "Greed",
    "ids": [
      5375
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 5941,
    "map": "Greed",
    "monsters": [
      "Kobold"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5942,
    "map": "Greed",
    "ids": [
      5376
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 5943,
    "map": "Greed",
    "monsters": [
      "Goregold"
    ]
  },
  {
    "kind": "plan",
    "questId": 5944,
    "actions": []
  },
  {
    "kind": "mapItem",
    "questId": 5945,
    "map": "Sloth",
    "ids": [
      5382
    ]
  },
  {
    "kind": "kill",
    "questId": 5945,
    "map": "Sloth",
    "monsters": [
      "Plague Zombie"
    ]
  },
  {
    "kind": "kill",
    "questId": 5946,
    "map": "Sloth",
    "monsters": [
      "Snotgoblin",
      "Wandering Plague"
    ]
  },
  {
    "kind": "kill",
    "questId": 5947,
    "map": "Sloth",
    "monsters": [
      "Plague Zombie"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5948,
    "map": "Sloth",
    "ids": [
      5387
    ]
  },
  {
    "kind": "kill",
    "questId": 5949,
    "map": "Sloth",
    "monsters": [
      "Marsh Thing"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5950,
    "map": "Sloth",
    "ids": [
      5383
    ],
    "quantity": 8
  },
  {
    "kind": "mapItem",
    "questId": 5951,
    "map": "Sloth",
    "ids": [
      5389
    ]
  },
  {
    "kind": "plan",
    "questId": 5952,
    "actions": [
      {
        "kind": "buy",
        "map": "Dragonhame",
        "shopId": 865,
        "item": "Airther Vitae"
      },
      {
        "kind": "buy",
        "map": "embersea",
        "shopId": 1100,
        "item": 1749
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5953,
    "map": "Sloth",
    "ids": [
      5391
    ]
  },
  {
    "kind": "kill",
    "questId": 5954,
    "map": "Sloth",
    "monsters": [
      "Plague Zombie"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5955,
    "map": "Sloth",
    "ids": [
      5384
    ],
    "quantity": 10
  },
  {
    "kind": "mapItem",
    "questId": 5956,
    "map": "Sloth",
    "ids": [
      5385
    ]
  },
  {
    "kind": "kill",
    "questId": 5956,
    "map": "Sloth",
    "monsters": [
      "SnotGoblin Prime"
    ]
  },
  {
    "kind": "kill",
    "questId": 5957,
    "map": "Sloth",
    "monsters": [
      "Phlegnn"
    ]
  },
  {
    "kind": "kill",
    "questId": 5958,
    "map": "Sloth",
    "monsters": [
      "Cured Phlegnn"
    ]
  },
  {
    "kind": "kill",
    "questId": 5960,
    "map": "Sloth",
    "monsters": [
      "Actual Sloth Dragon"
    ]
  },
  {
    "kind": "kill",
    "questId": 5959,
    "map": "Sloth",
    "monsters": [
      "Mutated Plague"
    ]
  },
  {
    "kind": "kill",
    "questId": 5961,
    "map": "Lust",
    "monsters": [
      "Devoted Admirer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5962,
    "map": "Lust",
    "ids": [
      5405,
      5406,
      5407,
      5408,
      5409
    ]
  },
  {
    "kind": "kill",
    "questId": 5963,
    "map": "Lust",
    "monsters": [
      "Golden Vase"
    ]
  },
  {
    "kind": "kill",
    "questId": 5964,
    "map": "Lust",
    "monsters": [
      "Enamored Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5965,
    "map": "Lust",
    "ids": [
      5410,
      5411
    ]
  },
  {
    "kind": "kill",
    "questId": 5965,
    "map": "Lust",
    "monsters": [
      "Devoted Admirer"
    ]
  },
  {
    "kind": "kill",
    "questId": 5966,
    "map": "Lust",
    "monsters": [
      "Enamored Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5967,
    "map": "Lust",
    "ids": [
      5412
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 5968,
    "map": "Lust",
    "ids": [
      5413
    ]
  },
  {
    "kind": "kill",
    "questId": 5968,
    "map": "Lust",
    "monsters": [
      "Elite Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5969,
    "map": "Lust",
    "ids": [
      5414
    ]
  },
  {
    "kind": "kill",
    "questId": 5969,
    "map": "Lust",
    "monsters": [
      "Viscyra"
    ]
  },
  {
    "kind": "kill",
    "questId": 5970,
    "map": "Lust",
    "monsters": [
      "Lascivia"
    ]
  },
  {
    "kind": "kill",
    "questId": 5971,
    "map": "Lust",
    "monsters": [
      "Elite Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 5972,
    "map": "Lust",
    "monsters": [
      "Golden Vase",
      "Golden Vase"
    ]
  },
  {
    "kind": "kill",
    "questId": 5973,
    "map": "Lust",
    "monsters": [
      "Devoted Admirer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5974,
    "map": "Lust",
    "ids": [
      5415
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 5974,
    "map": "Lust",
    "monsters": [
      "Elite Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5975,
    "map": "Lust",
    "ids": [
      5416,
      5417
    ]
  },
  {
    "kind": "kill",
    "questId": 5976,
    "map": "Lust",
    "monsters": [
      "Killek Deadchewer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5983,
    "map": "DragonCrown",
    "ids": [
      5420
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5984,
    "map": "DragonCrown",
    "ids": [
      5421
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5985,
    "map": "DragonCrown",
    "ids": [
      5422
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 5985,
    "map": "DragonCrown",
    "monsters": [
      "Fire Sprite"
    ]
  },
  {
    "kind": "kill",
    "questId": 5986,
    "map": "DragonCrown",
    "monsters": [
      "Llama",
      "Rampaging Boar"
    ]
  },
  {
    "kind": "kill",
    "questId": 5987,
    "map": "DragonCrown",
    "monsters": [
      "Rock Elemental",
      "Earth Elemental"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5988,
    "map": "DragonCrown",
    "ids": [
      5423
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5989,
    "map": "DragonCrown",
    "ids": [
      5424
    ]
  },
  {
    "kind": "kill",
    "questId": 5990,
    "map": "DragonCrown",
    "monsters": [
      "Torgat"
    ]
  },
  {
    "kind": "kill",
    "questId": 5991,
    "map": "DragonCrown",
    "monsters": [
      "Fressa"
    ]
  },
  {
    "kind": "kill",
    "questId": 5992,
    "map": "DragonCrown",
    "monsters": [
      "Radroth"
    ]
  },
  {
    "kind": "kill",
    "questId": 5993,
    "map": "DragonCrown",
    "monsters": [
      "Nizex"
    ]
  },
  {
    "kind": "kill",
    "questId": 5994,
    "map": "DragonCrown",
    "monsters": [
      "Tathu"
    ]
  },
  {
    "kind": "kill",
    "questId": 5995,
    "map": "DragonCrown",
    "monsters": [
      "Lanshen"
    ]
  },
  {
    "kind": "kill",
    "questId": 5996,
    "map": "DragonCrown",
    "monsters": [
      "Ashax"
    ]
  },
  {
    "kind": "kill",
    "questId": 5997,
    "map": "DragonCrown",
    "monsters": [
      "Letori"
    ]
  },
  {
    "kind": "kill",
    "questId": 5998,
    "map": "DragonCrown",
    "monsters": [
      "Nayzol"
    ]
  },
  {
    "kind": "kill",
    "questId": 5999,
    "map": "DragonCrown",
    "monsters": [
      "Zathas"
    ]
  },
  {
    "kind": "kill",
    "questId": 6000,
    "map": "DragonCrown",
    "monsters": [
      "Argo"
    ]
  },
  {
    "kind": "kill",
    "questId": 6001,
    "map": "Maloth",
    "monsters": [
      "Ukki"
    ]
  },
  {
    "kind": "kill",
    "questId": 6002,
    "map": "Maloth",
    "monsters": [
      "Kagan"
    ]
  },
  {
    "kind": "kill",
    "questId": 6003,
    "map": "Maloth",
    "monsters": [
      "Golgar"
    ]
  },
  {
    "kind": "kill",
    "questId": 6004,
    "map": "Maloth",
    "monsters": [
      "Golgar",
      "Castle Guard",
      "Scroll Keeper",
      "Nervous Serf",
      "Locked Chest"
    ]
  },
  {
    "kind": "kill",
    "questId": 6005,
    "map": "Maloth",
    "monsters": [
      "Maloth"
    ]
  },
  {
    "kind": "kill",
    "questId": 6110,
    "map": "Wrath",
    "monsters": [
      "Fishbones",
      "Bone Terror"
    ]
  },
  {
    "kind": "kill",
    "questId": 6111,
    "map": "Wrath",
    "monsters": [
      "Dark Fire"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6112,
    "map": "Wrath",
    "ids": [
      5541
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 6112,
    "map": "Wrath",
    "monsters": [
      "Bone Terror"
    ]
  },
  {
    "kind": "plan",
    "questId": 1075,
    "actions": [
      {
        "kind": "hunt",
        "map": "doomwood",
        "monster": "Doomwood Ectomancer",
        "item": "Dried Wasabi Powder",
        "quantity": 4
      },
      {
        "kind": "mapItem",
        "map": "lightguard",
        "id": 428,
        "quantity": 1
      },
      {
        "kind": "join",
        "map": "lightguard"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 6113
  },
  {
    "kind": "mapItem",
    "questId": 6114,
    "map": "Wrath",
    "ids": [
      5542
    ],
    "quantity": 6
  },
  {
    "kind": "mapItem",
    "questId": 6115,
    "map": "Wrath",
    "ids": [
      5540
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6116,
    "map": "Wrath",
    "ids": [
      5544
    ]
  },
  {
    "kind": "kill",
    "questId": 6116,
    "map": "Wrath",
    "monsters": [
      "Undead Pirate"
    ]
  },
  {
    "kind": "kill",
    "questId": 6117,
    "map": "Wrath",
    "monsters": [
      "Mutineer",
      "Mutineer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6118,
    "map": "Wrath",
    "ids": [
      5545
    ]
  },
  {
    "kind": "kill",
    "questId": 6119,
    "map": "Wrath",
    "monsters": [
      "Droghor"
    ]
  },
  {
    "kind": "kill",
    "questId": 6120,
    "map": "Wrath",
    "monsters": [
      "Gorgorath"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6163,
    "map": "Dragonbone",
    "ids": [
      5587
    ]
  },
  {
    "kind": "kill",
    "questId": 6163,
    "map": "Dragonbone",
    "monsters": [
      "Bone Dragonling",
      "Dark Fire"
    ]
  },
  {
    "kind": "kill",
    "questId": 6164,
    "map": "Dragonbone",
    "monsters": [
      "Bone Terror"
    ]
  },
  {
    "kind": "kill",
    "questId": 6165,
    "map": "Dragonbone",
    "monsters": [
      "Bone Wyvern"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6166,
    "map": "Dragonbone",
    "ids": [
      5588
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6167,
    "map": "Dragonbone",
    "ids": [
      5589
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6168,
    "map": "Dragonbone",
    "ids": [
      5590
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6169,
    "map": "Dragonbone",
    "ids": [
      5591
    ]
  },
  {
    "kind": "kill",
    "questId": 6169,
    "map": "Dragonbone",
    "monsters": [
      "Dragonshade"
    ]
  },
  {
    "kind": "kill",
    "questId": 6170,
    "map": "Dragonbone",
    "monsters": [
      "Gorgorath"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.7deadly-dragons.00seven-deadly-dragons",
    category: "Story",
    map: "Gluttony",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
