// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Envy",
  "description": "This will finish the Envy quest.",
  "tags": [
    "story",
    "quest",
    "7-deadly-dragons",
    "envy",
    "7deadly",
    "dragons",
    "06envy"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 5983,
    "map": "DragonCrown",
    "ids": [
      5420
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5984,
    "map": "DragonCrown",
    "ids": [
      5421
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5985,
    "map": "DragonCrown",
    "ids": [
      5422
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 5985,
    "map": "DragonCrown",
    "monsters": [
      "Fire Sprite"
    ]
  },
  {
    "kind": "kill",
    "questId": 5986,
    "map": "DragonCrown",
    "monsters": [
      "Llama",
      "Rampaging Boar"
    ]
  },
  {
    "kind": "kill",
    "questId": 5987,
    "map": "DragonCrown",
    "monsters": [
      "Rock Elemental",
      "Earth Elemental"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5988,
    "map": "DragonCrown",
    "ids": [
      5423
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5989,
    "map": "DragonCrown",
    "ids": [
      5424
    ]
  },
  {
    "kind": "kill",
    "questId": 5990,
    "map": "DragonCrown",
    "monsters": [
      "Torgat"
    ]
  },
  {
    "kind": "kill",
    "questId": 5991,
    "map": "DragonCrown",
    "monsters": [
      "Fressa"
    ]
  },
  {
    "kind": "kill",
    "questId": 5992,
    "map": "DragonCrown",
    "monsters": [
      "Radroth"
    ]
  },
  {
    "kind": "kill",
    "questId": 5993,
    "map": "DragonCrown",
    "monsters": [
      "Nizex"
    ]
  },
  {
    "kind": "kill",
    "questId": 5994,
    "map": "DragonCrown",
    "monsters": [
      "Tathu"
    ]
  },
  {
    "kind": "kill",
    "questId": 5995,
    "map": "DragonCrown",
    "monsters": [
      "Lanshen"
    ]
  },
  {
    "kind": "kill",
    "questId": 5996,
    "map": "DragonCrown",
    "monsters": [
      "Ashax"
    ]
  },
  {
    "kind": "kill",
    "questId": 5997,
    "map": "DragonCrown",
    "monsters": [
      "Letori"
    ]
  },
  {
    "kind": "kill",
    "questId": 5998,
    "map": "DragonCrown",
    "monsters": [
      "Nayzol"
    ]
  },
  {
    "kind": "kill",
    "questId": 5999,
    "map": "DragonCrown",
    "monsters": [
      "Zathas"
    ]
  },
  {
    "kind": "kill",
    "questId": 6000,
    "map": "DragonCrown",
    "monsters": [
      "Argo"
    ]
  },
  {
    "kind": "kill",
    "questId": 6001,
    "map": "Maloth",
    "monsters": [
      "Ukki"
    ]
  },
  {
    "kind": "kill",
    "questId": 6002,
    "map": "Maloth",
    "monsters": [
      "Kagan"
    ]
  },
  {
    "kind": "kill",
    "questId": 6003,
    "map": "Maloth",
    "monsters": [
      "Golgar"
    ]
  },
  {
    "kind": "kill",
    "questId": 6004,
    "map": "Maloth",
    "monsters": [
      "Golgar",
      "Castle Guard",
      "Scroll Keeper",
      "Nervous Serf",
      "Locked Chest"
    ]
  },
  {
    "kind": "kill",
    "questId": 6005,
    "map": "Maloth",
    "monsters": [
      "Maloth"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.7deadly-dragons.06envy",
    category: "Story",
    map: "DragonCrown",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
