// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Bamboozle",
  "description": "This will finish the Bamboozle quest line.",
  "tags": [
    "story",
    "quest",
    "bamboozle",
    "nation"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 7277,
    "actions": [
      {
        "kind": "hunt",
        "map": "wanders",
        "cell": "r2",
        "pad": "Down",
        "monster": "Kalestri Worshiper",
        "item": "Star of the Sandsea"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7278,
    "actions": []
  },
  {
    "kind": "plan",
    "questId": 7279,
    "actions": [
      {
        "kind": "hunt",
        "map": "kingcoal",
        "cell": "r1",
        "pad": "Left",
        "monster": "*",
        "item": "Frozen Coal",
        "quantity": 10,
        "isTemp": false
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 7278
  },
  {
    "kind": "chain",
    "questId": 7281
  },
  {
    "kind": "chain",
    "questId": 7280
  },
  {
    "kind": "kill",
    "questId": 7282,
    "map": "brightfall",
    "monsters": [
      "Painadin Overlord"
    ]
  },
  {
    "kind": "kill",
    "questId": 7283,
    "map": "timevoid",
    "monsters": [
      "Unending Avatar"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7284,
    "map": "downward",
    "ids": [
      6908
    ]
  },
  {
    "kind": "chain",
    "questId": 7297
  },
  {
    "kind": "chain",
    "questId": 7285
  },
  {
    "kind": "plan",
    "questId": 7286,
    "actions": []
  },
  {
    "kind": "plan",
    "questId": 7287,
    "actions": [
      {
        "kind": "hunt",
        "map": "bloodtusk",
        "monster": "Trollola Plant",
        "item": "Butterfly Bloom",
        "quantity": 15
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 7286
  },
  {
    "kind": "plan",
    "questId": 7289,
    "actions": [
      {
        "kind": "packet",
        "packet": "%xt%zm%updateQuest%1%935%"
      },
      {
        "kind": "hunt",
        "map": "battleunderc",
        "cell": "Enter",
        "pad": "Spawn",
        "monster": "*",
        "item": "Fluorite Shard",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 7288
  },
  {
    "kind": "plan",
    "questId": 7290,
    "actions": []
  },
  {
    "kind": "plan",
    "questId": 7291,
    "actions": [
      {
        "kind": "hunt",
        "map": "earthstorm",
        "monster": "Sapphire Golem",
        "item": "Chip of Sapphire"
      },
      {
        "kind": "hunt",
        "map": "earthstorm",
        "monster": "Ruby Golem",
        "item": "Chip of Ruby"
      },
      {
        "kind": "hunt",
        "map": "earthstorm",
        "monster": "Emerald Golem",
        "item": "Chip of Emerald"
      },
      {
        "kind": "hunt",
        "map": "earthstorm",
        "monster": "Diamond Golem",
        "item": "Chip of Diamond"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 7290
  },
  {
    "kind": "mapItem",
    "questId": 7292,
    "map": "thespan",
    "ids": [
      6910
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.nation.bamboozle",
    category: "Story",
    map: "wanders",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
