// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Oblivion Tundra Story",
  "description": "This script will complete the storyline in /obliviontundra.",
  "tags": [
    "story",
    "obliviontundra",
    "oblivion",
    "tundra",
    "nation",
    "nulgath",
    "the hushed"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 9522,
    "map": "voidrefuge",
    "monsters": [
      "Lightguard Paladin"
    ]
  },
  {
    "kind": "kill",
    "questId": 9523,
    "map": "voidrefuge",
    "monsters": [
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9524,
    "map": "voidrefuge",
    "ids": [
      12572
    ]
  },
  {
    "kind": "kill",
    "questId": 9524,
    "map": "voidrefuge",
    "monsters": [
      "Nation Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 9525,
    "map": "voidrefuge",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9526,
    "map": "voidrefuge",
    "ids": [
      12573
    ]
  },
  {
    "kind": "kill",
    "questId": 9526,
    "map": "voidrefuge",
    "monsters": [
      "Lightguard Paladin",
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9527,
    "map": "voidrefuge",
    "ids": [
      12574
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 9527,
    "map": "voidrefuge",
    "monsters": [
      "Nation Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 9528,
    "map": "voidrefuge",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9529,
    "map": "voidrefuge",
    "ids": [
      12575,
      12576,
      12577
    ]
  },
  {
    "kind": "kill",
    "questId": 9530,
    "map": "voidrefuge",
    "monsters": [
      "Paladin Ascendant",
      "Nation Outrider"
    ]
  },
  {
    "kind": "kill",
    "questId": 9531,
    "map": "voidrefuge",
    "monsters": [
      "Carnage"
    ]
  },
  {
    "kind": "kill",
    "questId": 9543,
    "map": "voidchasm",
    "monsters": [
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "kill",
    "questId": 9544,
    "map": "voidchasm",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9545,
    "map": "voidchasm",
    "ids": [
      12619
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 9545,
    "map": "voidchasm",
    "monsters": [
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9546,
    "map": "voidchasm",
    "ids": [
      12620,
      12621
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9547,
    "map": "voidchasm",
    "ids": [
      12622
    ]
  },
  {
    "kind": "kill",
    "questId": 9547,
    "map": "voidchasm",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "kill",
    "questId": 9548,
    "map": "voidchasm",
    "monsters": [
      "Void Fang"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9549,
    "map": "voidchasm",
    "ids": [
      12623,
      12627,
      12628
    ]
  },
  {
    "kind": "kill",
    "questId": 9549,
    "map": "voidchasm",
    "monsters": [
      "The Hushed"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9550,
    "map": "voidchasm",
    "ids": [
      12624
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 9550,
    "map": "voidchasm",
    "monsters": [
      "The Hushed",
      "Void Fang"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9551,
    "map": "voidchasm",
    "ids": [
      12625,
      12626
    ]
  },
  {
    "kind": "kill",
    "questId": 9551,
    "map": "voidchasm",
    "monsters": [
      "Carnage"
    ]
  },
  {
    "kind": "kill",
    "questId": 9552,
    "map": "voidchasm",
    "monsters": [
      "Carcano"
    ]
  },
  {
    "kind": "kill",
    "questId": 10023,
    "map": "deleuzetundra",
    "monsters": [
      "Empty Creature"
    ]
  },
  {
    "kind": "kill",
    "questId": 10024,
    "map": "deleuzetundra",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "plan",
    "questId": 10025,
    "actions": []
  },
  {
    "kind": "mapItem",
    "questId": 10025,
    "map": "deleuzetundra",
    "ids": [
      14048
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 10025,
    "map": "deleuzetundra",
    "ids": [
      14049
    ]
  },
  {
    "kind": "kill",
    "questId": 10026,
    "map": "deleuzetundra",
    "monsters": [
      "Oblivion Magus"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 10027,
    "map": "deleuzetundra",
    "ids": [
      14050,
      14051
    ]
  },
  {
    "kind": "mapItem",
    "questId": 10028,
    "map": "deleuzetundra",
    "ids": [
      14052
    ]
  },
  {
    "kind": "kill",
    "questId": 10028,
    "map": "deleuzetundra",
    "monsters": [
      "Empty Creature"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 10029,
    "map": "deleuzetundra",
    "ids": [
      14053
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 10029,
    "map": "deleuzetundra",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 10030,
    "map": "deleuzetundra",
    "ids": [
      14054
    ]
  },
  {
    "kind": "kill",
    "questId": 10030,
    "map": "deleuzetundra",
    "monsters": [
      "Oblivion Magus"
    ]
  },
  {
    "kind": "kill",
    "questId": 10031,
    "map": "deleuzetundra",
    "monsters": [
      "Oblivion's Herald"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 10036,
    "map": "obliviontundra",
    "ids": [
      14064
    ]
  },
  {
    "kind": "kill",
    "questId": 10036,
    "map": "obliviontundra",
    "monsters": [
      "Empty Creature"
    ]
  },
  {
    "kind": "kill",
    "questId": 10038,
    "map": "obliviontundra",
    "monsters": [
      "Hushed"
    ]
  },
  {
    "kind": "kill",
    "questId": 10040,
    "map": "obliviontundra",
    "monsters": [
      "Withered Archfiend"
    ]
  },
  {
    "kind": "kill",
    "questId": 10042,
    "map": "obliviontundra",
    "monsters": [
      "Oblivion Magus "
    ]
  },
  {
    "kind": "kill",
    "questId": 10043,
    "map": "obliviontundra",
    "monsters": [
      "Ettin Fiend"
    ]
  },
  {
    "kind": "kill",
    "questId": 10045,
    "map": "obliviontundra",
    "monsters": [
      "Archfiend Oblivion"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.nation.oblivion-tundra",
    category: "Story",
    map: "voidrefuge",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
