// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Void Chasm Story",
  "description": "This script will complete the storyline in /voidchasm.",
  "tags": [
    "story",
    "voidchasm",
    "chasm",
    "nation",
    "nulgath",
    "ana di carcano",
    "gravelyn",
    "jadzia",
    "void"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 9522,
    "map": "voidrefuge",
    "monsters": [
      "Lightguard Paladin"
    ]
  },
  {
    "kind": "kill",
    "questId": 9523,
    "map": "voidrefuge",
    "monsters": [
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9524,
    "map": "voidrefuge",
    "ids": [
      12572
    ]
  },
  {
    "kind": "kill",
    "questId": 9524,
    "map": "voidrefuge",
    "monsters": [
      "Nation Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 9525,
    "map": "voidrefuge",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9526,
    "map": "voidrefuge",
    "ids": [
      12573
    ]
  },
  {
    "kind": "kill",
    "questId": 9526,
    "map": "voidrefuge",
    "monsters": [
      "Lightguard Paladin",
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9527,
    "map": "voidrefuge",
    "ids": [
      12574
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 9527,
    "map": "voidrefuge",
    "monsters": [
      "Nation Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 9528,
    "map": "voidrefuge",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9529,
    "map": "voidrefuge",
    "ids": [
      12575,
      12576,
      12577
    ]
  },
  {
    "kind": "kill",
    "questId": 9530,
    "map": "voidrefuge",
    "monsters": [
      "Paladin Ascendant",
      "Nation Outrider"
    ]
  },
  {
    "kind": "kill",
    "questId": 9531,
    "map": "voidrefuge",
    "monsters": [
      "Carnage"
    ]
  },
  {
    "kind": "kill",
    "questId": 9543,
    "map": "voidchasm",
    "monsters": [
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "kill",
    "questId": 9544,
    "map": "voidchasm",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9545,
    "map": "voidchasm",
    "ids": [
      12619
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 9545,
    "map": "voidchasm",
    "monsters": [
      "Paladin Ascendant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9546,
    "map": "voidchasm",
    "ids": [
      12620,
      12621
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9547,
    "map": "voidchasm",
    "ids": [
      12622
    ]
  },
  {
    "kind": "kill",
    "questId": 9547,
    "map": "voidchasm",
    "monsters": [
      "Nation Outrider"
    ]
  },
  {
    "kind": "kill",
    "questId": 9548,
    "map": "voidchasm",
    "monsters": [
      "Void Fang"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9549,
    "map": "voidchasm",
    "ids": [
      12623,
      12627,
      12628
    ]
  },
  {
    "kind": "kill",
    "questId": 9549,
    "map": "voidchasm",
    "monsters": [
      "The Hushed"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9550,
    "map": "voidchasm",
    "ids": [
      12624
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 9550,
    "map": "voidchasm",
    "monsters": [
      "The Hushed",
      "Void Fang"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9551,
    "map": "voidchasm",
    "ids": [
      12625,
      12626
    ]
  },
  {
    "kind": "kill",
    "questId": 9551,
    "map": "voidchasm",
    "monsters": [
      "Carnage"
    ]
  },
  {
    "kind": "kill",
    "questId": 9552,
    "map": "voidchasm",
    "monsters": [
      "Carcano"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.nation.void-chasm",
    category: "Story",
    map: "voidrefuge",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
