// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Neo Tower",
  "description": "This script will complete the Lae's storyline in /neotower.",
  "tags": [
    "story",
    "hollowborn",
    "saga",
    "lae",
    "neotower",
    "neo tower",
    "quest",
    "04neo",
    "tower"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 8289,
    "map": "trygve",
    "monsters": [
      "Vindicator Recruit"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8290,
    "map": "trygve",
    "ids": [
      9036
    ]
  },
  {
    "kind": "kill",
    "questId": 8290,
    "map": "trygve",
    "monsters": [
      "Blood Eagle"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8291,
    "map": "trygve",
    "ids": [
      9037
    ]
  },
  {
    "kind": "kill",
    "questId": 8291,
    "map": "trygve",
    "monsters": [
      "Vindicator Recruit"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8292,
    "map": "trygve",
    "ids": [
      9038
    ]
  },
  {
    "kind": "kill",
    "questId": 8292,
    "map": "trygve",
    "monsters": [
      "Rune Boar"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8293,
    "map": "trygve",
    "ids": [
      9039
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 8293,
    "map": "trygve",
    "monsters": [
      "Vindicator Recruit"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8294,
    "map": "trygve",
    "ids": [
      9040
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 8295,
    "map": "trygve",
    "monsters": [
      "Blood Eagle",
      "Rune Boar"
    ]
  },
  {
    "kind": "kill",
    "questId": 8296,
    "map": "trygve",
    "monsters": [
      "Vindicator Recruit"
    ]
  },
  {
    "kind": "kill",
    "questId": 8297,
    "map": "trygve",
    "monsters": [
      "Blood Eagle",
      "Vindicator Recruit"
    ]
  },
  {
    "kind": "kill",
    "questId": 8298,
    "map": "trygve",
    "monsters": [
      "Gramiel"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9281,
    "map": "neofortress",
    "ids": [
      11806
    ],
    "quantity": 9
  },
  {
    "kind": "kill",
    "questId": 9282,
    "map": "neofortress",
    "monsters": [
      "Vindicator Recruit"
    ]
  },
  {
    "kind": "kill",
    "questId": 9283,
    "map": "neofortress",
    "monsters": [
      "Vindicator Hound"
    ]
  },
  {
    "kind": "kill",
    "questId": 9284,
    "map": "neofortress",
    "monsters": [
      "Vindicator Beast"
    ]
  },
  {
    "kind": "kill",
    "questId": 9285,
    "map": "neofortress",
    "monsters": [
      "Vindicator Soldier"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9286,
    "map": "neofortress",
    "ids": [
      11807
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 9287,
    "map": "neofortress",
    "monsters": [
      "Vindicator General"
    ]
  },
  {
    "kind": "kill",
    "questId": 9288,
    "map": "neofortress",
    "monsters": [
      "Vindicator Recruit"
    ]
  },
  {
    "kind": "kill",
    "questId": 9289,
    "map": "neofortress",
    "monsters": [
      "Vindicator General"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9290,
    "map": "neofortress",
    "ids": [
      11808
    ]
  },
  {
    "kind": "kill",
    "questId": 9855,
    "map": "neotower",
    "monsters": [
      "Dawn Vindicator Soldier "
    ]
  },
  {
    "kind": "kill",
    "questId": 9856,
    "map": "neotower",
    "monsters": [
      "Vindicator Beast"
    ]
  },
  {
    "kind": "kill",
    "questId": 9857,
    "map": "neotower",
    "monsters": [
      "Vindicator Draconian"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 9858,
    "map": "neotower",
    "ids": [
      13581
    ]
  },
  {
    "kind": "kill",
    "questId": 9858,
    "map": "neotower",
    "monsters": [
      "Vindicator Draconian"
    ]
  },
  {
    "kind": "kill",
    "questId": 9859,
    "map": "neotower",
    "monsters": [
      "Vindicator Assassin"
    ]
  },
  {
    "kind": "kill",
    "questId": 9860,
    "map": "neotower",
    "monsters": [
      "Vindicator BeastTamer"
    ]
  },
  {
    "kind": "kill",
    "questId": 9861,
    "map": "neotower",
    "monsters": [
      "Vindicator Beast"
    ]
  },
  {
    "kind": "kill",
    "questId": 9862,
    "map": "neotower",
    "monsters": [
      "Dawn Vindicator Soldier "
    ]
  },
  {
    "kind": "kill",
    "questId": 9864,
    "map": "neotower",
    "monsters": [
      "Vindicator Priest"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.hollowborn.04neo-tower",
    category: "Story",
    map: "trygve",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
