// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Chaos Amulet",
  "description": "This will finish the Chaos Amulet quest.",
  "tags": [
    "story",
    "quest",
    "shadow-chaos",
    "chaos-amulet",
    "shadows",
    "of",
    "chaos",
    "02chaos",
    "amulet"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7561,
    "map": "dualplane",
    "monsters": [
      "Terrarsite"
    ]
  },
  {
    "kind": "kill",
    "questId": 7562,
    "map": "dualplane",
    "monsters": [
      "Droognax"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7563,
    "map": "dualplane",
    "ids": [
      7459
    ]
  },
  {
    "kind": "kill",
    "questId": 7564,
    "map": "dualplane",
    "monsters": [
      "Terrarsite"
    ]
  },
  {
    "kind": "kill",
    "questId": 7565,
    "map": "dualplane",
    "monsters": [
      "SpiderWing",
      "Terrarsite"
    ]
  },
  {
    "kind": "kill",
    "questId": 7566,
    "map": "dualplane",
    "monsters": [
      "Droognax"
    ]
  },
  {
    "kind": "kill",
    "questId": 7567,
    "map": "dualplane",
    "monsters": [
      "Netherpit Lackey"
    ]
  },
  {
    "kind": "kill",
    "questId": 7568,
    "map": "dualplane",
    "monsters": [
      "Netherpit Bruiser"
    ]
  },
  {
    "kind": "kill",
    "questId": 7569,
    "map": "dualplane",
    "monsters": [
      "Terrarsite",
      "Netherpit Lackey"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7570,
    "map": "dualplane",
    "ids": [
      7460
    ]
  },
  {
    "kind": "kill",
    "questId": 7571,
    "map": "dualplane",
    "monsters": [
      "Xiang"
    ]
  },
  {
    "kind": "plan",
    "questId": 7685,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosamulet",
        "monster": "Shadowflame Scout",
        "item": "Shadow Medal",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7686,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosamulet",
        "monster": "Shadowflame Scout",
        "item": "Mega Shadow Medal",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7687,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosamulet",
        "monster": "Goldun",
        "item": "Goldun Defeated"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7688,
    "map": "chaosamulet",
    "monsters": [
      "Goldun",
      "Shadowflame Berserker"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.shadows-of-chaos.02chaos-amulet",
    category: "Story",
    map: "dualplane",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
