// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Bright Shadow",
  "description": "This will finish the Bright Shadow quest.",
  "tags": [
    "story",
    "quest",
    "shadow-chaos",
    "bright-shadow",
    "shadows",
    "of",
    "chaos",
    "06bright",
    "shadow"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7561,
    "map": "dualplane",
    "monsters": [
      "Terrarsite"
    ]
  },
  {
    "kind": "kill",
    "questId": 7562,
    "map": "dualplane",
    "monsters": [
      "Droognax"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7563,
    "map": "dualplane",
    "ids": [
      7459
    ]
  },
  {
    "kind": "kill",
    "questId": 7564,
    "map": "dualplane",
    "monsters": [
      "Terrarsite"
    ]
  },
  {
    "kind": "kill",
    "questId": 7565,
    "map": "dualplane",
    "monsters": [
      "SpiderWing",
      "Terrarsite"
    ]
  },
  {
    "kind": "kill",
    "questId": 7566,
    "map": "dualplane",
    "monsters": [
      "Droognax"
    ]
  },
  {
    "kind": "kill",
    "questId": 7567,
    "map": "dualplane",
    "monsters": [
      "Netherpit Lackey"
    ]
  },
  {
    "kind": "kill",
    "questId": 7568,
    "map": "dualplane",
    "monsters": [
      "Netherpit Bruiser"
    ]
  },
  {
    "kind": "kill",
    "questId": 7569,
    "map": "dualplane",
    "monsters": [
      "Terrarsite",
      "Netherpit Lackey"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7570,
    "map": "dualplane",
    "ids": [
      7460
    ]
  },
  {
    "kind": "kill",
    "questId": 7571,
    "map": "dualplane",
    "monsters": [
      "Xiang"
    ]
  },
  {
    "kind": "plan",
    "questId": 7685,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosamulet",
        "monster": "Shadowflame Scout",
        "item": "Shadow Medal",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7686,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosamulet",
        "monster": "Shadowflame Scout",
        "item": "Mega Shadow Medal",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7687,
    "actions": [
      {
        "kind": "hunt",
        "map": "chaosamulet",
        "monster": "Goldun",
        "item": "Goldun Defeated"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7688,
    "map": "chaosamulet",
    "monsters": [
      "Goldun",
      "Shadowflame Berserker"
    ]
  },
  {
    "kind": "kill",
    "questId": 7690,
    "map": "lagunabeach",
    "monsters": [
      "Flying Fisheye"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7691,
    "map": "lagunabeach",
    "ids": [
      7636
    ]
  },
  {
    "kind": "kill",
    "questId": 7692,
    "map": "lagunabeach",
    "monsters": [
      "ShadowChaos Brigand"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7693,
    "map": "lagunabeach",
    "ids": [
      7637
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7693,
    "map": "lagunabeach",
    "monsters": [
      "Chaos Kelp"
    ]
  },
  {
    "kind": "kill",
    "questId": 7694,
    "map": "lagunabeach",
    "monsters": [
      "ShadowChaos Brigand"
    ]
  },
  {
    "kind": "kill",
    "questId": 7695,
    "map": "lagunabeach",
    "monsters": [
      "Flying Fisheye"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7696,
    "map": "lagunabeach",
    "ids": [
      7638
    ],
    "quantity": 3
  },
  {
    "kind": "mapItem",
    "questId": 7696,
    "map": "lagunabeach",
    "ids": [
      7639
    ]
  },
  {
    "kind": "kill",
    "questId": 7697,
    "map": "lagunabeach",
    "monsters": [
      "ShadowChaos Brigand"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7698,
    "map": "lagunabeach",
    "ids": [
      7640
    ]
  },
  {
    "kind": "kill",
    "questId": 7698,
    "map": "lagunabeach",
    "monsters": [
      "ShadowChaos Gunner"
    ]
  },
  {
    "kind": "kill",
    "questId": 7699,
    "map": "lagunabeach",
    "monsters": [
      "Heart of Chaos"
    ]
  },
  {
    "kind": "kill",
    "questId": 7700,
    "map": "lagunabeach",
    "monsters": [
      "Flying Fisheye"
    ]
  },
  {
    "kind": "kill",
    "questId": 7702,
    "map": "laguna",
    "monsters": [
      "ShadowChaos Brigand"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7703,
    "map": "laguna",
    "ids": [
      7675
    ]
  },
  {
    "kind": "kill",
    "questId": 7704,
    "map": "laguna",
    "monsters": [
      "ShadowChaos Gunner"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7705,
    "map": "laguna",
    "ids": [
      7676
    ]
  },
  {
    "kind": "kill",
    "questId": 7705,
    "map": "laguna",
    "monsters": [
      "ShadowChaos Gunner"
    ]
  },
  {
    "kind": "kill",
    "questId": 7706,
    "map": "laguna",
    "monsters": [
      "Captain Laguna"
    ]
  },
  {
    "kind": "kill",
    "questId": 7707,
    "map": "laguna",
    "monsters": [
      "ShadowChaos Brigand"
    ]
  },
  {
    "kind": "kill",
    "questId": 7708,
    "map": "laguna",
    "monsters": [
      "Chaos Roe"
    ]
  },
  {
    "kind": "kill",
    "questId": 7709,
    "map": "laguna",
    "monsters": [
      "Chaos Burrower"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7710,
    "map": "laguna",
    "ids": [
      7678
    ]
  },
  {
    "kind": "kill",
    "questId": 7710,
    "map": "laguna",
    "monsters": [
      "ShadowChaos Brigand"
    ]
  },
  {
    "kind": "kill",
    "questId": 7711,
    "map": "laguna",
    "monsters": [
      "Writhing Chaos"
    ]
  },
  {
    "kind": "kill",
    "questId": 7712,
    "map": "laguna",
    "monsters": [
      "Chaos Roe"
    ]
  },
  {
    "kind": "kill",
    "questId": 7728,
    "map": "Shadowoff",
    "monsters": [
      "Shadowflame Militia",
      "Shadowflame Paladin",
      "Shadowflame Scout",
      "Shadowflame Sorcerer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7729,
    "map": "Shadowoff",
    "ids": [
      7699
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7729,
    "map": "Shadowoff",
    "monsters": [
      "Shadowflame Sorcerer"
    ]
  },
  {
    "kind": "kill",
    "questId": 7730,
    "map": "Shadowoff",
    "monsters": [
      "Shadowflame Militia"
    ]
  },
  {
    "kind": "kill",
    "questId": 7731,
    "map": "Shadowoff",
    "monsters": [
      "Shadowflame Militia",
      "Shadowflame Scout",
      "Shadowflame Sorcerer"
    ]
  },
  {
    "kind": "kill",
    "questId": 7732,
    "map": "Shadowoff",
    "monsters": [
      "Shadowflame Paladin"
    ]
  },
  {
    "kind": "kill",
    "questId": 7733,
    "map": "BrightShadow",
    "monsters": [
      "BrightFall light"
    ]
  },
  {
    "kind": "kill",
    "questId": 7734,
    "map": "BrightShadow",
    "monsters": [
      "BrightFall Guard",
      "ShadowFlame Paladin"
    ]
  },
  {
    "kind": "kill",
    "questId": 7735,
    "map": "BrightShadow",
    "monsters": [
      "BrightFall Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7736,
    "map": "BrightShadow",
    "ids": [
      7701
    ]
  },
  {
    "kind": "kill",
    "questId": 7737,
    "map": "BrightShadow",
    "monsters": [
      "Gravelyn the Good"
    ]
  },
  {
    "kind": "kill",
    "questId": 7738,
    "map": "BrightShadow",
    "monsters": [
      "Brightfall light",
      "Brightfall Guard",
      "Shadowflame Paladin"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.shadows-of-chaos.06bright-shadow",
    category: "Story",
    map: "dualplane",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
