// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Sepulchure Saga / Core Sepulchure",
  "description": "Runs the Sepulchure Saga / Core Sepulchure story route.",
  "tags": [
    "story",
    "sepulchure",
    "saga",
    "core"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 6332,
    "map": "scarsgarde",
    "ids": [
      5860
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6333,
    "map": "scarsgarde",
    "ids": [
      5864
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 6333,
    "map": "scarsgarde",
    "monsters": [
      "VenomWing"
    ]
  },
  {
    "kind": "kill",
    "questId": 6334,
    "map": "scarsgarde",
    "monsters": [
      "Garde Grif"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6335,
    "map": "scarsgarde",
    "ids": [
      5865
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 6335,
    "map": "scarsgarde",
    "monsters": [
      "Tree"
    ]
  },
  {
    "kind": "kill",
    "questId": 6336,
    "map": "scarsgarde",
    "monsters": [
      "Garde Watch",
      "Garde Pikeman"
    ]
  },
  {
    "kind": "plan",
    "questId": 6338,
    "actions": [
      {
        "kind": "hunt",
        "map": "scarsgarde",
        "cell": "r35",
        "pad": "Left",
        "monster": "Garde Knight",
        "item": "Passcode A"
      },
      {
        "kind": "hunt",
        "map": "scarsgarde",
        "cell": "r35",
        "pad": "Left",
        "monster": "Garde Knight",
        "item": "Passcode C"
      },
      {
        "kind": "hunt",
        "map": "scarsgarde",
        "cell": "r35",
        "pad": "Left",
        "monster": "Garde Pikeman",
        "item": "Passcode B"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6338,
    "map": "scarsgarde",
    "ids": [
      5866,
      5867
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6339,
    "map": "scarsgarde",
    "ids": [
      5868
    ],
    "quantity": 8
  },
  {
    "kind": "mapItem",
    "questId": 6339,
    "map": "scarsgarde",
    "ids": [
      5869
    ]
  },
  {
    "kind": "kill",
    "questId": 6340,
    "map": "scarsgarde",
    "monsters": [
      "Garde Knight",
      "Garde Pikeman"
    ]
  },
  {
    "kind": "kill",
    "questId": 6341,
    "map": "scarsgarde",
    "monsters": [
      "Garde Captain"
    ]
  },
  {
    "kind": "kill",
    "questId": 6342,
    "map": "scarsgarde",
    "monsters": [
      "Garde Knight",
      "Garde Watch",
      "Garde Pikeman"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6343,
    "map": "scarsgarde",
    "ids": [
      5861
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6344,
    "map": "scarsgarde",
    "ids": [
      5864
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 6344,
    "map": "scarsgarde",
    "monsters": [
      "VenomWing"
    ]
  },
  {
    "kind": "kill",
    "questId": 6345,
    "map": "scarsgarde",
    "monsters": [
      "Garde Grif"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6346,
    "map": "scarsgarde",
    "ids": [
      5865
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 6346,
    "map": "scarsgarde",
    "monsters": [
      "Tree"
    ]
  },
  {
    "kind": "kill",
    "questId": 6347,
    "map": "scarsgarde",
    "monsters": [
      "Garde Watch",
      "Garde Pikeman"
    ]
  },
  {
    "kind": "kill",
    "questId": 6348,
    "map": "scarsgarde",
    "monsters": [
      "Garde Watch",
      "Garde Watch",
      "Garde Watch",
      "Garde Watch",
      "Garde Watch",
      "Garde Watch",
      "Garde Watch"
    ]
  },
  {
    "kind": "plan",
    "questId": 6349,
    "actions": [
      {
        "kind": "hunt",
        "map": "scarsgarde",
        "cell": "r35",
        "pad": "Left",
        "monster": "Garde Knight",
        "item": "Passcode A"
      },
      {
        "kind": "hunt",
        "map": "scarsgarde",
        "cell": "r35",
        "pad": "Left",
        "monster": "Garde Knight",
        "item": "Passcode C"
      },
      {
        "kind": "hunt",
        "map": "scarsgarde",
        "cell": "r35",
        "pad": "Left",
        "monster": "Garde Pikeman",
        "item": "Passcode B"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6349,
    "map": "scarsgarde",
    "ids": [
      5866,
      5867
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6350,
    "map": "scarsgarde",
    "ids": [
      5868
    ],
    "quantity": 8
  },
  {
    "kind": "mapItem",
    "questId": 6350,
    "map": "scarsgarde",
    "ids": [
      5869
    ]
  },
  {
    "kind": "kill",
    "questId": 6351,
    "map": "scarsgarde",
    "monsters": [
      "Garde Knight",
      "Garde Pikeman"
    ]
  },
  {
    "kind": "kill",
    "questId": 6352,
    "map": "scarsgarde",
    "monsters": [
      "Garde Captain"
    ]
  },
  {
    "kind": "kill",
    "questId": 6353,
    "map": "scarsgarde",
    "monsters": [
      "Garde Knight",
      "Garde Watch",
      "Garde Pikeman"
    ]
  },
  {
    "kind": "plan",
    "questId": 6356,
    "actions": [
      {
        "kind": "buy",
        "map": "valleyofdoom",
        "shopId": 1599,
        "item": "Valen Gear",
        "quantity": 1
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 6357,
    "map": "valleyofdoom",
    "monsters": [
      "Shadow Imp"
    ]
  },
  {
    "kind": "kill",
    "questId": 6358,
    "map": "valleyofdoom",
    "monsters": [
      "Shadow Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6359,
    "map": "valleyofdoom",
    "ids": [
      5873
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 6360,
    "map": "valleyofdoom",
    "monsters": [
      "Shadow Beast",
      "Shadow Person"
    ]
  },
  {
    "kind": "kill",
    "questId": 6361,
    "map": "valleyofdoom",
    "monsters": [
      "Doom Guardian"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6362,
    "map": "valleyofdoom",
    "ids": [
      5872
    ]
  },
  {
    "kind": "plan",
    "questId": 6363,
    "actions": [
      {
        "kind": "hunt",
        "map": "valleyofdoom",
        "cell": "r7",
        "pad": "Left",
        "monster": "Doom Star",
        "item": "Doomstar Destroyed"
      },
      {
        "kind": "hunt",
        "map": "valleyofdoom",
        "cell": "r7",
        "pad": "Left",
        "monster": "Doom Scythe",
        "item": "Doomscythe Destroyed"
      },
      {
        "kind": "hunt",
        "map": "valleyofdoom",
        "cell": "r7",
        "pad": "Left",
        "monster": "Doom Axe",
        "item": "Doomaxe Destroyed"
      },
      {
        "kind": "hunt",
        "map": "valleyofdoom",
        "cell": "r8",
        "pad": "Left",
        "monster": "Doom Blade",
        "item": "Doom Blade Destroyed"
      },
      {
        "kind": "hunt",
        "map": "valleyofdoom",
        "cell": "r8",
        "pad": "Left",
        "monster": "Doom Knight Armor",
        "item": "Doom Knight Armor Destroyed"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 6364,
    "actions": [
      {
        "kind": "hunt",
        "map": "valleyofdoom",
        "monster": 25,
        "item": "Doomknight Armor Defeated"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6365,
    "map": "guardiantower",
    "ids": [
      5871
    ]
  },
  {
    "kind": "kill",
    "questId": 6366,
    "map": "guardiantower",
    "monsters": [
      "Slime"
    ]
  },
  {
    "kind": "kill",
    "questId": 6367,
    "map": "guardiantower",
    "monsters": [
      "Yargol Magebane"
    ]
  },
  {
    "kind": "kill",
    "questId": 6369,
    "map": "valleyofdoom",
    "monsters": [
      "Shadow Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6370,
    "map": "ebonslate",
    "ids": [
      5895
    ]
  },
  {
    "kind": "kill",
    "questId": 6371,
    "map": "ebonslate",
    "monsters": [
      "Mind Con-Troll"
    ]
  },
  {
    "kind": "kill",
    "questId": 6372,
    "map": "ebonslate",
    "monsters": [
      "Sp-Eye"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6373,
    "map": "ebonslate",
    "ids": [
      5896
    ]
  },
  {
    "kind": "kill",
    "questId": 6373,
    "map": "ebonslate",
    "monsters": [
      "Ebonslate Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6374,
    "map": "ebonslate",
    "ids": [
      5897
    ]
  },
  {
    "kind": "kill",
    "questId": 6374,
    "map": "ebonslate",
    "monsters": [
      "Lycan Brute",
      "Lycan Brute"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6375,
    "map": "ebonslate",
    "ids": [
      5898
    ]
  },
  {
    "kind": "kill",
    "questId": 6376,
    "map": "ebonslate",
    "monsters": [
      "Ebonslate Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6377,
    "map": "ebonslate",
    "monsters": [
      "Mind Con-Troll"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6378,
    "map": "ebonslate",
    "ids": [
      5899
    ]
  },
  {
    "kind": "kill",
    "questId": 6379,
    "map": "ebonslate",
    "monsters": [
      "Ebonslate Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6380,
    "map": "ebonslate",
    "monsters": [
      "Ebonslate Bruiser"
    ]
  },
  {
    "kind": "plan",
    "questId": 6381,
    "actions": [
      {
        "kind": "join",
        "map": "ebonslate",
        "cell": "r11",
        "pad": "Left"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 6382,
    "map": "guardiantowerb",
    "monsters": [
      "Slime"
    ]
  },
  {
    "kind": "kill",
    "questId": 6383,
    "map": "guardiantowerb",
    "monsters": [
      "Slime"
    ]
  },
  {
    "kind": "kill",
    "questId": 6384,
    "map": "guardiantowerb",
    "monsters": [
      "Yargol Magebane"
    ]
  },
  {
    "kind": "kill",
    "questId": 6385,
    "map": "guardiantowerb",
    "monsters": [
      "Slime"
    ]
  },
  {
    "kind": "kill",
    "questId": 6386,
    "map": "guardiantowerb",
    "monsters": [
      "Guardian Selby",
      "Guardian Garen"
    ]
  },
  {
    "kind": "kill",
    "questId": 6387,
    "map": "guardiantowerb",
    "monsters": [
      "Guardian Garen",
      "Guardian Selby"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6388,
    "map": "guardiantowerb",
    "ids": [
      5901
    ]
  },
  {
    "kind": "kill",
    "questId": 6388,
    "map": "guardiantowerb",
    "monsters": [
      "Guardian Bolton"
    ]
  },
  {
    "kind": "kill",
    "questId": 6389,
    "map": "ebondungeon",
    "monsters": [
      "Ebonslate Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6390,
    "map": "ebondungeon",
    "ids": [
      5902
    ]
  },
  {
    "kind": "kill",
    "questId": 6391,
    "map": "ebondungeon",
    "monsters": [
      "Ebon Dungeon Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 6392,
    "map": "ebondungeon",
    "monsters": [
      "Elite Dungeon Guard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6393,
    "map": "ebondungeon",
    "ids": [
      5903,
      5904
    ]
  },
  {
    "kind": "kill",
    "questId": 6394,
    "map": "ebondungeon",
    "monsters": [
      "Dethrix"
    ]
  },
  {
    "kind": "kill",
    "questId": 6395,
    "map": "ebondungeon",
    "monsters": [
      "Ebon Dungeon Guard"
    ]
  },
  {
    "kind": "kill",
    "questId": 6399,
    "map": "alteonfight",
    "monsters": [
      "King Alteon"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6400,
    "map": "alteonfight",
    "ids": [
      5910
    ]
  },
  {
    "kind": "kill",
    "questId": 6401,
    "map": "darkplane",
    "monsters": [
      "Shadow Beast"
    ]
  },
  {
    "kind": "kill",
    "questId": 6402,
    "map": "darkplane",
    "monsters": [
      "Guardian Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6403,
    "map": "darkplane",
    "monsters": [
      "Light Spirit"
    ]
  },
  {
    "kind": "kill",
    "questId": 6404,
    "map": "darkplane",
    "monsters": [
      "Shadow Beast"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6405,
    "map": "darkplane",
    "ids": [
      5911
    ]
  },
  {
    "kind": "kill",
    "questId": 6406,
    "map": "darkplane",
    "monsters": [
      "Guardian Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 6407,
    "map": "darkplane",
    "monsters": [
      "Victorious"
    ]
  },
  {
    "kind": "kill",
    "questId": 6408,
    "map": "darkplane",
    "monsters": [
      "Shadow Beast"
    ]
  },
  {
    "kind": "kill",
    "questId": 6539,
    "map": "noxustower",
    "monsters": [
      "Slimeskull"
    ]
  },
  {
    "kind": "kill",
    "questId": 6540,
    "map": "noxustower",
    "monsters": [
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 6541,
    "map": "noxustower",
    "monsters": [
      "Sanguine Souleater"
    ]
  },
  {
    "kind": "kill",
    "questId": 6542,
    "map": "noxustower",
    "monsters": [
      "Lightguard Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 6543,
    "map": "noxustower",
    "monsters": [
      "Lightguard Caster"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6544,
    "map": "noxustower",
    "ids": [
      6018
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 6544,
    "map": "noxustower",
    "monsters": [
      "Lightguard Caster"
    ]
  },
  {
    "kind": "kill",
    "questId": 6545,
    "map": "noxustower",
    "monsters": [
      "Lightguard Wolf"
    ]
  },
  {
    "kind": "kill",
    "questId": 6546,
    "map": "noxustower",
    "monsters": [
      "Lightguard Paladin"
    ]
  },
  {
    "kind": "kill",
    "questId": 6547,
    "map": "noxustower",
    "monsters": [
      "Slimeskull",
      "Lightguard Caster",
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6548,
    "map": "noxustower",
    "ids": [
      6019
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6549,
    "map": "noxustower",
    "ids": [
      6020
    ]
  },
  {
    "kind": "kill",
    "questId": 6550,
    "map": "noxustower",
    "monsters": [
      "General Goldhammer"
    ]
  },
  {
    "kind": "kill",
    "questId": 6560,
    "map": "lightguardwar",
    "monsters": [
      "Citadel Crusader"
    ]
  },
  {
    "kind": "kill",
    "questId": 6561,
    "map": "lightguardwar",
    "monsters": [
      "Citadel Crusader"
    ]
  },
  {
    "kind": "kill",
    "questId": 6562,
    "map": "lightguardwar",
    "monsters": [
      "Citadel Crusader"
    ]
  },
  {
    "kind": "kill",
    "questId": 6563,
    "map": "lightguardwar",
    "monsters": [
      "Slimeskull"
    ]
  },
  {
    "kind": "kill",
    "questId": 6564,
    "map": "lightguardwar",
    "monsters": [
      "Lightguard Engine"
    ]
  },
  {
    "kind": "kill",
    "questId": 6565,
    "map": "lightguardwar",
    "monsters": [
      "Scorching Flame"
    ]
  },
  {
    "kind": "kill",
    "questId": 6566,
    "map": "lightguardwar",
    "monsters": [
      "Citadel Crusader"
    ]
  },
  {
    "kind": "kill",
    "questId": 6567,
    "map": "lightguardwar",
    "monsters": [
      "Sigrid Sunshield"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6581,
    "map": "lumafortress",
    "ids": [
      6098
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 6581,
    "map": "lumafortress",
    "monsters": [
      "Invasive Shadow"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6582,
    "map": "lumafortress",
    "ids": [
      6099
    ],
    "quantity": 7
  },
  {
    "kind": "kill",
    "questId": 6582,
    "map": "lumafortress",
    "monsters": [
      "Light Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 6583,
    "map": "lumafortress",
    "monsters": [
      "Light Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 6584,
    "map": "lumafortress",
    "monsters": [
      "Hapless Skeleton"
    ]
  },
  {
    "kind": "kill",
    "questId": 6585,
    "map": "lumafortress",
    "monsters": [
      "Light Treeant"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6586,
    "map": "lumafortress",
    "ids": [
      6100
    ]
  },
  {
    "kind": "kill",
    "questId": 6586,
    "map": "lumafortress",
    "monsters": [
      "Lightwing"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 6587,
    "map": "lumafortress",
    "ids": [
      6101
    ]
  },
  {
    "kind": "kill",
    "questId": 6588,
    "map": "lumafortress",
    "monsters": [
      "Light Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 6589,
    "map": "lumafortress",
    "monsters": [
      "Living Shadow"
    ]
  },
  {
    "kind": "kill",
    "questId": 6590,
    "map": "lumafortress",
    "monsters": [
      "Skeleton Minion"
    ]
  },
  {
    "kind": "plan",
    "questId": 6591,
    "actions": [
      {
        "kind": "hunt",
        "map": "lumafortress",
        "cell": "r4",
        "pad": "Left",
        "monster": "Corrupted Luma",
        "item": "Luma Defeated"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 6592,
    "map": "lumafortress",
    "monsters": [
      "Light Elemental"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.sepulchure-saga.core-sepulchure",
    category: "Story",
    map: "scarsgarde",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
