// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "(Dread Space) Summer 2015 Adventure Map Story",
  "description": "This will finish the Dread Space story.",
  "tags": [
    "story",
    "dread",
    "space",
    "summer",
    "2015",
    "adventure",
    "map",
    "farm",
    "summer2015adventure",
    "1dread"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "chain",
    "questId": 4263
  },
  {
    "kind": "plan",
    "questId": 4264,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreadspace",
        "cell": "r4",
        "pad": "Left",
        "monster": "*",
        "item": "Proof of Undead"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4265,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreadspace",
        "cell": "r4",
        "pad": "Left",
        "monster": "*",
        "item": "Space Zombie Gun",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4266,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreadspace",
        "cell": "r4",
        "pad": "Left",
        "monster": "*",
        "item": "Troopers Interrogated",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4267,
    "map": "dreadspace",
    "monsters": [
      "Defense Turret",
      "Vaderix"
    ]
  },
  {
    "kind": "kill",
    "questId": 4268,
    "map": "dreadspace",
    "monsters": [
      "Cyber Horg"
    ]
  },
  {
    "kind": "plan",
    "questId": 4269,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Undead Space Warrior",
        "item": "Holodeck Force Field",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Undead Star Ranger",
        "item": "Holodeck EbilCorp AI"
      },
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Undead Space Marine",
        "item": "Holodeck Projector",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Cyber Horg",
        "item": "Holodeck Power Source"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4270,
    "map": "dreadspace",
    "monsters": [
      "Dra'gorn",
      "Dra'gorn",
      "Dra'gorn"
    ]
  },
  {
    "kind": "plan",
    "questId": 4271,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Red Trobble",
        "item": "Red Space Fabric",
        "quantity": 6,
        "isTemp": false
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4273,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Holo Gunslinger",
        "item": "Cowboy defeated",
        "quantity": 5,
        "isTemp": false
      },
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Vaderix",
        "item": "Alien defeated",
        "quantity": 5,
        "isTemp": false
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 4272,
    "actions": [
      {
        "kind": "hunt",
        "map": "dreadspace",
        "monster": "Holo Gunslinger",
        "item": "J6's Helmet"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 4274,
    "map": "dreadspace",
    "monsters": [
      "Jack"
    ]
  },
  {
    "kind": "kill",
    "questId": 4275,
    "map": "dreadspace",
    "monsters": [
      "Old Twilly"
    ]
  },
  {
    "kind": "kill",
    "questId": 4276,
    "map": "dreadspace",
    "monsters": [
      "Hologram Turret"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 4277,
    "map": "dreadspace",
    "ids": [
      3423
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 4278,
    "map": "dreadspace",
    "monsters": [
      "Trobble"
    ]
  },
  {
    "kind": "kill",
    "questId": 4279,
    "map": "dreadspace",
    "monsters": [
      "Defense Turret"
    ]
  },
  {
    "kind": "kill",
    "questId": 4280,
    "map": "dreadspace",
    "monsters": [
      "Vaderix"
    ]
  },
  {
    "kind": "kill",
    "questId": 4281,
    "map": "dreadspace",
    "monsters": [
      "Undead Space Marine"
    ]
  },
  {
    "kind": "kill",
    "questId": 4282,
    "map": "dreadspace",
    "monsters": [
      "Undead Space Marine"
    ]
  },
  {
    "kind": "kill",
    "questId": 4283,
    "map": "dreadspace",
    "monsters": [
      "Undead Space Marine",
      "Undead Space Warrior",
      "Cyber Horg",
      "Vaderix"
    ]
  },
  {
    "kind": "kill",
    "questId": 4284,
    "map": "dreadspace",
    "monsters": [
      "Cyber Horg"
    ]
  },
  {
    "kind": "kill",
    "questId": 4285,
    "map": "dreadspace",
    "monsters": [
      "Dread Space"
    ]
  },
  {
    "kind": "kill",
    "questId": 4286,
    "map": "dreadspace",
    "monsters": [
      "Cyborg Beast Core"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.summer2015adventure-map.1dread-space",
    category: "Story",
    map: "dreadspace",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
