// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "(Scarletta) Shatter Glass Maze Story",
  "description": "This will finish the Shatter Glass Maze story.",
  "tags": [
    "story",
    "shatter",
    "glass",
    "maze",
    "farm",
    "scarletta",
    "throne",
    "darkness",
    "throneof",
    "06a"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 5298,
    "map": "hedgemaze",
    "ids": [
      4678
    ]
  },
  {
    "kind": "kill",
    "questId": 5298,
    "map": "hedgemaze",
    "monsters": [
      "Knight's Reflection"
    ]
  },
  {
    "kind": "plan",
    "questId": 5299,
    "actions": [
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "monster": "Mirrored Shard",
        "item": "Mirror Shard Slain",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "monster": 48,
        "item": "Hedge Goblin Slain",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "monster": 20,
        "item": "Minotaur Slain",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5299,
    "map": "hedgemaze",
    "ids": [
      4679
    ]
  },
  {
    "kind": "kill",
    "questId": 5300,
    "map": "hedgemaze",
    "monsters": [
      "Knight's Reflection"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5301,
    "map": "hedgemaze",
    "ids": [
      4680
    ]
  },
  {
    "kind": "kill",
    "questId": 5302,
    "map": "hedgemaze",
    "monsters": [
      "Hedge Goblin"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5303,
    "map": "hedgemaze",
    "ids": [
      4681
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 5304,
    "map": "hedgemaze",
    "monsters": [
      "Mirrored Shard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5305,
    "map": "hedgemaze",
    "ids": [
      4682
    ]
  },
  {
    "kind": "kill",
    "questId": 5306,
    "map": "hedgemaze",
    "monsters": [
      "Minotaur Prime"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5307,
    "map": "hedgemaze",
    "ids": [
      4683
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5308,
    "map": "hedgemaze",
    "ids": [
      4684
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5309,
    "map": "hedgemaze",
    "ids": [
      4685
    ],
    "quantity": 5
  },
  {
    "kind": "plan",
    "questId": 5310,
    "actions": [
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "cell": "r21",
        "pad": "Right",
        "monster": "*",
        "item": "Maze Monster Killed",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5311,
    "map": "hedgemaze",
    "ids": [
      4686
    ]
  },
  {
    "kind": "kill",
    "questId": 5312,
    "map": "hedgemaze",
    "monsters": [
      "Shattered Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 5313,
    "map": "hedgemaze",
    "monsters": [
      "Resurrected Minotaur"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.throneof-darkness.06a-scarletta-shatter-glass-maze",
    category: "Story",
    map: "hedgemaze",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
