// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "(Scarletta) Tower of Mirrors Story",
  "description": "This will finish the Tower of Mirrors story.",
  "tags": [
    "story",
    "tower",
    "mirrors",
    "farm",
    "scarletta",
    "throne",
    "darkness",
    "throneof",
    "06b",
    "towerof"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 5298,
    "map": "hedgemaze",
    "ids": [
      4678
    ]
  },
  {
    "kind": "kill",
    "questId": 5298,
    "map": "hedgemaze",
    "monsters": [
      "Knight's Reflection"
    ]
  },
  {
    "kind": "plan",
    "questId": 5299,
    "actions": [
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "monster": "Mirrored Shard",
        "item": "Mirror Shard Slain",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "monster": 48,
        "item": "Hedge Goblin Slain",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "monster": 20,
        "item": "Minotaur Slain",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5299,
    "map": "hedgemaze",
    "ids": [
      4679
    ]
  },
  {
    "kind": "kill",
    "questId": 5300,
    "map": "hedgemaze",
    "monsters": [
      "Knight's Reflection"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5301,
    "map": "hedgemaze",
    "ids": [
      4680
    ]
  },
  {
    "kind": "kill",
    "questId": 5302,
    "map": "hedgemaze",
    "monsters": [
      "Hedge Goblin"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5303,
    "map": "hedgemaze",
    "ids": [
      4681
    ],
    "quantity": 12
  },
  {
    "kind": "kill",
    "questId": 5304,
    "map": "hedgemaze",
    "monsters": [
      "Mirrored Shard"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5305,
    "map": "hedgemaze",
    "ids": [
      4682
    ]
  },
  {
    "kind": "kill",
    "questId": 5306,
    "map": "hedgemaze",
    "monsters": [
      "Minotaur Prime"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5307,
    "map": "hedgemaze",
    "ids": [
      4683
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5308,
    "map": "hedgemaze",
    "ids": [
      4684
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5309,
    "map": "hedgemaze",
    "ids": [
      4685
    ],
    "quantity": 5
  },
  {
    "kind": "plan",
    "questId": 5310,
    "actions": [
      {
        "kind": "hunt",
        "map": "hedgemaze",
        "cell": "r21",
        "pad": "Right",
        "monster": "*",
        "item": "Maze Monster Killed",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5311,
    "map": "hedgemaze",
    "ids": [
      4686
    ]
  },
  {
    "kind": "kill",
    "questId": 5312,
    "map": "hedgemaze",
    "monsters": [
      "Shattered Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 5313,
    "map": "hedgemaze",
    "monsters": [
      "Resurrected Minotaur"
    ]
  },
  {
    "kind": "kill",
    "questId": 5314,
    "map": "towerofmirrors",
    "monsters": [
      "Glassgoyle",
      "Glass Serpent"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5315,
    "map": "towerofmirrors",
    "ids": [
      4691,
      4692
    ]
  },
  {
    "kind": "kill",
    "questId": 5315,
    "map": "towerofmirrors",
    "monsters": [
      "Silver Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 5316,
    "map": "towerofmirrors",
    "monsters": [
      "Phans",
      "Phans"
    ]
  },
  {
    "kind": "plan",
    "questId": 5317,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": 36,
        "item": "Lathannos the Reversed Defeated"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5318,
    "map": "towerofmirrors",
    "ids": [
      4687,
      4693
    ]
  },
  {
    "kind": "kill",
    "questId": 5318,
    "map": "towerofmirrors",
    "monsters": [
      "Silver Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 5319,
    "map": "towerofmirrors",
    "monsters": [
      "Runway Wraith",
      "Runway Wraith",
      "Runway Wraith",
      "Runway Wraith"
    ]
  },
  {
    "kind": "plan",
    "questId": 5320,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": 40,
        "item": "Lukrisio the Buffed Defeated"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5321,
    "map": "towerofmirrors",
    "ids": [
      4688,
      4694
    ]
  },
  {
    "kind": "kill",
    "questId": 5321,
    "map": "towerofmirrors",
    "monsters": [
      "Silver Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 5322,
    "map": "towerofmirrors",
    "monsters": [
      "Pageant Mom",
      "Pageant Mom"
    ]
  },
  {
    "kind": "plan",
    "questId": 5323,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": 45,
        "item": "Mendeskar the Smudged Defeated"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5324,
    "map": "towerofmirrors",
    "ids": [
      4689,
      4695
    ]
  },
  {
    "kind": "kill",
    "questId": 5324,
    "map": "towerofmirrors",
    "monsters": [
      "Silver Elemental"
    ]
  },
  {
    "kind": "plan",
    "questId": 5325,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": "Stage Tech",
        "item": "Stage Tech Defeated",
        "quantity": 9
      },
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": "Stage Tech",
        "item": "Rope Ladder"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 5326,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": 49,
        "item": "Atticus the Warped Defeated"
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5327,
    "map": "towerofmirrors",
    "ids": [
      4690,
      4696
    ]
  },
  {
    "kind": "kill",
    "questId": 5327,
    "map": "towerofmirrors",
    "monsters": [
      "Silver Elemental"
    ]
  },
  {
    "kind": "plan",
    "questId": 5328,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": "Sasquatch",
        "item": "Sasquatches Defeated",
        "quantity": 10
      },
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": "Sasquatch",
        "item": "Tracking Tag",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 5329,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": 52,
        "item": "Leofire the Shattered Defeated"
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 5330,
    "map": "towerofmirrors",
    "monsters": [
      "Fervent Suitor"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5331,
    "map": "towerofmirrors",
    "ids": [
      4697
    ]
  },
  {
    "kind": "plan",
    "questId": 5332,
    "actions": [
      {
        "kind": "hunt",
        "map": "towerofmirrors",
        "monster": 32,
        "item": "Defeat the Groglurk"
      }
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.throneof-darkness.06b-scarletta-towerof-mirrors",
    category: "Story",
    map: "hedgemaze",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
