// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "(Stranger) Mysterious Dungeon Story",
  "description": "This will finish the Mysterious Dungeon story.",
  "tags": [
    "story",
    "mysterious",
    "dungeon",
    "farm",
    "throne",
    "darkness",
    "stranger",
    "throneof",
    "07b"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 5428,
    "map": "cursedshop",
    "ids": [
      4803
    ]
  },
  {
    "kind": "kill",
    "questId": 5429,
    "map": "cursedshop",
    "monsters": [
      "Antique Chair"
    ]
  },
  {
    "kind": "kill",
    "questId": 5430,
    "map": "cursedshop",
    "monsters": [
      "UnDresser"
    ]
  },
  {
    "kind": "kill",
    "questId": 5431,
    "map": "cursedshop",
    "monsters": [
      "Writing Desk"
    ]
  },
  {
    "kind": "kill",
    "questId": 5432,
    "map": "cursedshop",
    "monsters": [
      "Grandfather Clock"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5433,
    "map": "cursedshop",
    "ids": [
      4804,
      4805
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5434,
    "map": "cursedshop",
    "ids": [
      4806
    ]
  },
  {
    "kind": "kill",
    "questId": 5434,
    "map": "cursedshop",
    "monsters": [
      "Arcane Sentinel"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5428,
    "map": "cursedshop",
    "ids": [
      4803
    ]
  },
  {
    "kind": "kill",
    "questId": 5429,
    "map": "cursedshop",
    "monsters": [
      "Antique Chair"
    ]
  },
  {
    "kind": "kill",
    "questId": 5430,
    "map": "cursedshop",
    "monsters": [
      "UnDresser"
    ]
  },
  {
    "kind": "kill",
    "questId": 5431,
    "map": "cursedshop",
    "monsters": [
      "Writing Desk"
    ]
  },
  {
    "kind": "kill",
    "questId": 5432,
    "map": "cursedshop",
    "monsters": [
      "Grandfather Clock"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5433,
    "map": "cursedshop",
    "ids": [
      4804,
      4805
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5434,
    "map": "cursedshop",
    "ids": [
      4806
    ]
  },
  {
    "kind": "kill",
    "questId": 5434,
    "map": "cursedshop",
    "monsters": [
      "Arcane Sentinel"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5438,
    "map": "MysteriousDungeon",
    "ids": [
      4818
    ]
  },
  {
    "kind": "kill",
    "questId": 5439,
    "map": "MysteriousDungeon",
    "monsters": [
      "Skudly"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5440,
    "map": "MysteriousDungeon",
    "ids": [
      4808
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5441,
    "map": "MysteriousDungeon",
    "ids": [
      4809
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5442,
    "map": "MysteriousDungeon",
    "ids": [
      4810,
      4811,
      4812,
      4813,
      4814,
      4815,
      4816
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5443,
    "map": "MysteriousDungeon",
    "ids": [
      4817
    ]
  },
  {
    "kind": "kill",
    "questId": 5444,
    "map": "MysteriousDungeon",
    "monsters": [
      "Skudly"
    ]
  },
  {
    "kind": "kill",
    "questId": 5445,
    "map": "MysteriousDungeon",
    "monsters": [
      "Mysterious Stranger"
    ]
  },
  {
    "kind": "kill",
    "questId": 5446,
    "map": "MysteriousDungeon",
    "monsters": [
      "Vaden"
    ]
  },
  {
    "kind": "kill",
    "questId": 5447,
    "map": "MysteriousDungeon",
    "monsters": [
      "Xeight"
    ]
  },
  {
    "kind": "kill",
    "questId": 5448,
    "map": "MysteriousDungeon",
    "monsters": [
      "Ziri"
    ]
  },
  {
    "kind": "kill",
    "questId": 5449,
    "map": "MysteriousDungeon",
    "monsters": [
      "Pax"
    ]
  },
  {
    "kind": "kill",
    "questId": 5450,
    "map": "MysteriousDungeon",
    "monsters": [
      "Sekt"
    ]
  },
  {
    "kind": "kill",
    "questId": 5451,
    "map": "MysteriousDungeon",
    "monsters": [
      "Scarletta"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.throneof-darkness.07b-stranger-mysterious-dungeon",
    category: "Story",
    map: "cursedshop",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
