// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../../runner.js";

export const meta = {
  "name": "Infernal Paradise",
  "description": "This will finish the Aranx' quests in /infernalparadise.",
  "tags": [
    "story",
    "quest",
    "queen of monster",
    "celestial realm",
    "infernalparadise",
    "aranx",
    "extra",
    "qom",
    "queenof",
    "monsters",
    "infernal",
    "paradise"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 7674,
    "map": "CelestialPast",
    "monsters": [
      "Blessed Deer",
      "Blessed Bear",
      "Blessed Centaur",
      "Blessed Hydra"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7675,
    "map": "CelestialPast",
    "ids": [
      7592
    ]
  },
  {
    "kind": "kill",
    "questId": 7675,
    "map": "CelestialPast",
    "monsters": [
      "Blessed Deer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7676,
    "map": "CelestialPast",
    "ids": [
      7593
    ]
  },
  {
    "kind": "kill",
    "questId": 7676,
    "map": "CelestialPast",
    "monsters": [
      "Blessed Deer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7677,
    "map": "CelestialPast",
    "ids": [
      7594
    ]
  },
  {
    "kind": "kill",
    "questId": 7677,
    "map": "CelestialPast",
    "monsters": [
      "Blessed Deer",
      "Blessed Centaur",
      "Blessed Hydra",
      "Blessed Bear"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7678,
    "map": "CelestialPast",
    "ids": [
      7595
    ]
  },
  {
    "kind": "kill",
    "questId": 7678,
    "map": "CelestialPast",
    "monsters": [
      "Well Guardian"
    ]
  },
  {
    "kind": "kill",
    "questId": 7679,
    "map": "CelestialPast",
    "monsters": [
      "Infernal Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 7680,
    "map": "CelestialPast",
    "monsters": [
      "Infernal Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 7681,
    "map": "CelestialPast",
    "monsters": [
      "Azalith"
    ]
  },
  {
    "kind": "kill",
    "questId": 10073,
    "map": "infernalparadise",
    "monsters": [
      "Infernal Mage"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 10074,
    "map": "infernalparadise",
    "ids": [
      14158
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 10075,
    "map": "infernalparadise",
    "monsters": [
      "Infernal Malxas"
    ]
  },
  {
    "kind": "kill",
    "questId": 10076,
    "map": "infernalparadise",
    "monsters": [
      "Infernal Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 10077,
    "map": "infernalparadise",
    "ids": [
      14159
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 10079,
    "map": "infernalparadise",
    "ids": [
      14160
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 10080,
    "map": "infernalparadise",
    "monsters": [
      "Infernal Mage"
    ]
  },
  {
    "kind": "kill",
    "questId": 10083,
    "map": "infernalparadise",
    "monsters": [
      "Infernal Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 10081,
    "map": "infernalparadise",
    "monsters": [
      "Azalith"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.queenof-monsters.extra.infernal-paradise",
    category: "Story",
    map: "CelestialPast",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
