// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Shadow Grove",
  "description": "This will finish the Shadowgrove quest.",
  "tags": [
    "story",
    "quest",
    "shadow-war",
    "shadowgrove",
    "shadows",
    "of",
    "war",
    "08shadowgrove"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 6993,
    "map": "shadowgrove",
    "monsters": [
      "Shadow Dragonlord"
    ]
  },
  {
    "kind": "kill",
    "questId": 6994,
    "map": "shadowgrove",
    "monsters": [
      "Shadow Wyvern"
    ]
  },
  {
    "kind": "kill",
    "questId": 6995,
    "map": "shadowgrove",
    "monsters": [
      "Shadow Dragonlord"
    ]
  },
  {
    "kind": "kill",
    "questId": 6996,
    "map": "shadowgrove",
    "monsters": [
      "Shadow Wyvern"
    ]
  },
  {
    "kind": "kill",
    "questId": 6997,
    "map": "shadowgrove",
    "monsters": [
      "Mutant Shadow Dragon"
    ]
  },
  {
    "kind": "plan",
    "questId": 6998,
    "actions": [
      {
        "kind": "hunt",
        "map": "shadowgrove",
        "cell": "r9",
        "pad": "Left",
        "monster": "Mutant Shadow Dragon",
        "item": "Mutant Dragon Oil",
        "quantity": 3
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 6999,
    "map": "shadowgrove",
    "monsters": [
      "Titan Shadow Dragonlord"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.shadows-of-war.08shadowgrove",
    category: "Story",
    map: "shadowgrove",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
