// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Aozora Hills",
  "description": "This will finish the Aozora Hills quest.",
  "tags": [
    "story",
    "quest",
    "shadow-war",
    "aozora-hills",
    "shadows",
    "of",
    "war",
    "09aozora",
    "hills"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 7050,
    "map": "aozorahills",
    "ids": [
      6643
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 7050,
    "map": "aozorahills",
    "ids": [
      6644
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7050,
    "map": "aozorahills",
    "monsters": [
      "Reishi"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7051,
    "map": "aozorahills",
    "ids": [
      6645
    ]
  },
  {
    "kind": "kill",
    "questId": 7052,
    "map": "aozorahills",
    "monsters": [
      "Aozora Kijimuna"
    ]
  },
  {
    "kind": "kill",
    "questId": 7053,
    "map": "aozorahills",
    "monsters": [
      "Osanshouo"
    ]
  },
  {
    "kind": "kill",
    "questId": 7054,
    "map": "aozorahills",
    "monsters": [
      "Kosenjobi"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7055,
    "map": "aozorahills",
    "ids": [
      6646
    ]
  },
  {
    "kind": "kill",
    "questId": 7055,
    "map": "aozorahills",
    "monsters": [
      "Fuyurei"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7056,
    "map": "aozorahills",
    "ids": [
      6647
    ],
    "quantity": 3
  },
  {
    "kind": "mapItem",
    "questId": 7057,
    "map": "aozorahills",
    "ids": [
      6648
    ]
  },
  {
    "kind": "kill",
    "questId": 7057,
    "map": "aozorahills",
    "monsters": [
      "Aozora Kijimuna"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7058,
    "map": "aozorahills",
    "ids": [
      6649
    ],
    "quantity": 3
  },
  {
    "kind": "mapItem",
    "questId": 7059,
    "map": "aozorahills",
    "ids": [
      6650
    ]
  },
  {
    "kind": "kill",
    "questId": 7059,
    "map": "aozorahills",
    "monsters": [
      "Reishi"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7060,
    "map": "aozorahills",
    "ids": [
      6651
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 7061,
    "map": "aozorahills",
    "monsters": [
      "Kosenjobi"
    ]
  },
  {
    "kind": "kill",
    "questId": 7062,
    "map": "aozorahills",
    "monsters": [
      "Ghostly Hasu"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.shadows-of-war.09aozora-hills",
    category: "Story",
    map: "aozorahills",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
