// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Tyndarius",
  "description": "This will finish the Tyndarius quest.",
  "tags": [
    "story",
    "quest",
    "shadow-war",
    "tyndarius",
    "shadows",
    "of",
    "war",
    "15tyndarius"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 7419,
    "map": "darkally",
    "ids": [
      7179
    ],
    "quantity": 6
  },
  {
    "kind": "chain",
    "questId": 7419
  },
  {
    "kind": "kill",
    "questId": 7420,
    "map": "darkally",
    "monsters": [
      "Underworld Golem",
      "Underworld Golem"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7421,
    "map": "darkally",
    "ids": [
      7180
    ],
    "quantity": 1
  },
  {
    "kind": "mapItem",
    "questId": 7421,
    "map": "darkally",
    "ids": [
      7181
    ],
    "quantity": 8
  },
  {
    "kind": "plan",
    "questId": 7422,
    "actions": [
      {
        "kind": "join",
        "map": "Darkally",
        "cell": "r2",
        "pad": "Left"
      },
      {
        "kind": "hunt",
        "map": "Darkally",
        "cell": "r2",
        "pad": "Left",
        "monster": "Dark Makai"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7423,
    "actions": [
      {
        "kind": "hunt",
        "map": "Darkally",
        "cell": "r2",
        "pad": "Left",
        "monster": 4452,
        "item": "Shredded Shadow",
        "quantity": 9
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 7424,
    "actions": [
      {
        "kind": "hunt",
        "map": "Darkally",
        "monster": "Legion Defector",
        "item": "Defectors Slain",
        "quantity": 10
      },
      {
        "kind": "hunt",
        "map": "Darkally",
        "monster": "Legion Defector",
        "item": "Legion Soul",
        "quantity": 5
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 7425,
    "map": "darkally",
    "monsters": [
      "Frozen Pyromancer"
    ]
  },
  {
    "kind": "kill",
    "questId": 7426,
    "map": "darkally",
    "monsters": [
      "Underworld Golem"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7427,
    "map": "darkally",
    "ids": [
      7182
    ],
    "quantity": 1
  },
  {
    "kind": "kill",
    "questId": 7428,
    "map": "darkally",
    "monsters": [
      "Underfiend"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7446,
    "map": "darkalliance",
    "ids": [
      7224
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 7446,
    "map": "darkalliance",
    "monsters": [
      "Shadow"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7447,
    "map": "darkalliance",
    "ids": [
      7225
    ],
    "quantity": 1
  },
  {
    "kind": "kill",
    "questId": 7447,
    "map": "darkalliance",
    "monsters": [
      "Shadowblade"
    ]
  },
  {
    "kind": "kill",
    "questId": 7448,
    "map": "darkalliance",
    "monsters": [
      "Shadow Void"
    ]
  },
  {
    "kind": "kill",
    "questId": 7449,
    "map": "darkalliance",
    "monsters": [
      "Shadow Makai"
    ]
  },
  {
    "kind": "kill",
    "questId": 7450,
    "map": "darkalliance",
    "monsters": [
      "Shadow Void"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7451,
    "map": "darkalliance",
    "ids": [
      7226
    ],
    "quantity": 8
  },
  {
    "kind": "mapItem",
    "questId": 7452,
    "map": "darkalliance",
    "ids": [
      7227
    ],
    "quantity": 1
  },
  {
    "kind": "kill",
    "questId": 7453,
    "map": "darkalliance",
    "monsters": [
      "Underlava"
    ]
  },
  {
    "kind": "kill",
    "questId": 7454,
    "map": "darkalliance",
    "monsters": [
      "Underworld Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7455,
    "map": "darkalliance",
    "ids": [
      7228
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 7456,
    "map": "darkalliance",
    "monsters": [
      "Underflame Guardian"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7457,
    "map": "darkalliance",
    "ids": [
      7229
    ],
    "quantity": 1
  },
  {
    "kind": "kill",
    "questId": 7458,
    "map": "darkalliance",
    "monsters": [
      "Shadow"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7459,
    "map": "darkalliance",
    "ids": [
      7230
    ],
    "quantity": 1
  },
  {
    "kind": "kill",
    "questId": 7460,
    "map": "darkalliance",
    "monsters": [
      "ShadowFlame Nulgath"
    ]
  },
  {
    "kind": "kill",
    "questId": 7461,
    "map": "innershadows",
    "monsters": [
      "Infected Minion"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7462,
    "map": "innershadows",
    "ids": [
      7271
    ]
  },
  {
    "kind": "kill",
    "questId": 7462,
    "map": "innershadows",
    "monsters": [
      "Infected Minion"
    ]
  },
  {
    "kind": "kill",
    "questId": 7463,
    "map": "innershadows",
    "monsters": [
      "Infected Minion"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7464,
    "map": "innershadows",
    "ids": [
      7272
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7465,
    "map": "innershadows",
    "ids": [
      7273
    ],
    "quantity": 8
  },
  {
    "kind": "kill",
    "questId": 7466,
    "map": "innershadows",
    "monsters": [
      "Shadowcrow"
    ]
  },
  {
    "kind": "kill",
    "questId": 7467,
    "map": "innershadows",
    "monsters": [
      "Shadow ShadowScythe"
    ]
  },
  {
    "kind": "kill",
    "questId": 7468,
    "map": "innershadows",
    "monsters": [
      "Infected Minion"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7469,
    "map": "innershadows",
    "ids": [
      7274
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7470,
    "map": "innershadows",
    "monsters": [
      "ShadowSpitter",
      "Shadowcrow"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 7471,
    "map": "innershadows",
    "ids": [
      7275
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 7472,
    "map": "innershadows",
    "monsters": [
      "Krahen"
    ]
  },
  {
    "kind": "kill",
    "questId": 8125,
    "map": "fireplanewar",
    "monsters": [
      "Shadowflame Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 8126,
    "map": "fireplanewar",
    "monsters": [
      "Shadowflame Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 8127,
    "map": "fireplanewar",
    "monsters": [
      "Shadefire Onslaught"
    ]
  },
  {
    "kind": "kill",
    "questId": 8128,
    "map": "fireplanewar",
    "monsters": [
      "Shadowflame Soldier"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8129,
    "map": "fireplanewar",
    "ids": [
      8523
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 8129,
    "map": "fireplanewar",
    "monsters": [
      "Shadowflame Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 8130,
    "map": "fireplanewar",
    "monsters": [
      "Shadefire Onslaught"
    ]
  },
  {
    "kind": "kill",
    "questId": 8131,
    "map": "fireplanewar",
    "monsters": [
      "ShadowClaw"
    ]
  },
  {
    "kind": "kill",
    "questId": 8132,
    "map": "fireplanewar",
    "monsters": [
      "Shadefire Elemental"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8133,
    "map": "fireplanewar",
    "ids": [
      8524
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 8133,
    "map": "fireplanewar",
    "monsters": [
      "Living Shadowflame"
    ]
  },
  {
    "kind": "kill",
    "questId": 8134,
    "map": "fireplanewar",
    "monsters": [
      "Living Shadowflame"
    ]
  },
  {
    "kind": "kill",
    "questId": 8135,
    "map": "fireplanewar",
    "monsters": [
      "ShadowFlame Phedra"
    ]
  },
  {
    "kind": "kill",
    "questId": 8136,
    "map": "shadowfireplane",
    "monsters": [
      "Living Shadowflame"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8137,
    "map": "shadowfireplane",
    "ids": [
      8544
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 8138,
    "map": "shadowfireplane",
    "monsters": [
      "Onslaught Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8139,
    "map": "shadowfireplane",
    "ids": [
      8542
    ]
  },
  {
    "kind": "plan",
    "questId": 8140,
    "actions": [
      {
        "kind": "mapItem",
        "id": 8543
      },
      {
        "kind": "hunt",
        "map": "shadowfireplane",
        "cell": "r6",
        "pad": "Left",
        "monster": "Shadow Wing",
        "item": "Shadow Flamewing Defeated",
        "quantity": 2
      },
      {
        "kind": "hunt",
        "map": "shadowfireplane",
        "cell": "r6",
        "pad": "Left",
        "monster": "Shadowfire Summoner",
        "item": "Shadowfire Summoner Defeated",
        "quantity": 1
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 8141,
    "map": "shadowfireplane",
    "monsters": [
      "Shadowfire Corporal",
      "Onslaught Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 8142,
    "map": "shadowfireplane",
    "monsters": [
      "Shadowfire Tiger"
    ]
  },
  {
    "kind": "kill",
    "questId": 8143,
    "map": "shadowfireplane",
    "monsters": [
      "Shadowfire Corporal"
    ]
  },
  {
    "kind": "kill",
    "questId": 8144,
    "map": "shadowfireplane",
    "monsters": [
      "Elius"
    ]
  },
  {
    "kind": "kill",
    "questId": 8179,
    "map": "fireinvasion",
    "monsters": [
      "Onslaught Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8180,
    "map": "fireinvasion",
    "ids": [
      8728
    ],
    "quantity": 3
  },
  {
    "kind": "kill",
    "questId": 8180,
    "map": "fireinvasion",
    "monsters": [
      "Shadowfire Tiger"
    ]
  },
  {
    "kind": "kill",
    "questId": 8181,
    "map": "fireinvasion",
    "monsters": [
      "Shadefire Cavalry"
    ]
  },
  {
    "kind": "kill",
    "questId": 8182,
    "map": "fireinvasion",
    "monsters": [
      "Shadowfire Corporal"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8183,
    "map": "fireinvasion",
    "ids": [
      8729
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 8183,
    "map": "fireinvasion",
    "monsters": [
      "Shadefire Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 8184,
    "map": "fireinvasion",
    "monsters": [
      "Shadefire Major"
    ]
  },
  {
    "kind": "plan",
    "questId": 8185,
    "actions": [
      {
        "kind": "hunt",
        "map": "fireinvasion",
        "cell": "r8",
        "pad": "Top",
        "monster": "Shadefire Elemental",
        "item": "Elemental Slain",
        "quantity": 7
      },
      {
        "kind": "hunt",
        "map": "fireinvasion",
        "cell": "r7",
        "pad": "Top",
        "monster": "Shadowfire Tiger",
        "item": "Tiger Slain",
        "quantity": 7
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 8186,
    "map": "fireinvasion",
    "monsters": [
      "Living Shadowflame"
    ]
  },
  {
    "kind": "kill",
    "questId": 8187,
    "map": "fireinvasion",
    "monsters": [
      "Shadefire Colonel"
    ]
  },
  {
    "kind": "kill",
    "questId": 8188,
    "map": "fireinvasion",
    "monsters": [
      "Living Shadowflame"
    ]
  },
  {
    "kind": "kill",
    "questId": 8189,
    "map": "fireinvasion",
    "monsters": [
      "Onslaught Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 8190,
    "map": "fireinvasion",
    "monsters": [
      "Shadefire General"
    ]
  },
  {
    "kind": "kill",
    "questId": 8191,
    "map": "fireinvasion",
    "monsters": [
      "Shadowflame Kyron"
    ]
  },
  {
    "kind": "kill",
    "questId": 8192,
    "map": "fireinvasion",
    "monsters": [
      "Living Shadowflame",
      "Shadefire Cavalry"
    ]
  },
  {
    "kind": "kill",
    "questId": 8193,
    "map": "wartraining",
    "monsters": [
      "Simulated Shadefire"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8194,
    "map": "wartraining",
    "ids": [
      8746
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 8195,
    "map": "wartraining",
    "monsters": [
      "Simulated Major"
    ]
  },
  {
    "kind": "kill",
    "questId": 8196,
    "map": "wartraining",
    "monsters": [
      "Simulated Elius"
    ]
  },
  {
    "kind": "kill",
    "questId": 8197,
    "map": "wartraining",
    "monsters": [
      "Simulated Fire"
    ]
  },
  {
    "kind": "kill",
    "questId": 8198,
    "map": "wartraining",
    "monsters": [
      "Simulated Elemental"
    ]
  },
  {
    "kind": "kill",
    "questId": 8199,
    "map": "wartraining",
    "monsters": [
      "Simulated Fire"
    ]
  },
  {
    "kind": "kill",
    "questId": 8200,
    "map": "wartraining",
    "monsters": [
      "Fire Champion"
    ]
  },
  {
    "kind": "kill",
    "questId": 8201,
    "map": "wartraining",
    "monsters": [
      "Warfury Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 8202,
    "map": "wartraining",
    "monsters": [
      "Warfury Elite"
    ]
  },
  {
    "kind": "kill",
    "questId": 8203,
    "map": "wartraining",
    "monsters": [
      "Varga"
    ]
  },
  {
    "kind": "kill",
    "questId": 8204,
    "map": "wartraining",
    "monsters": [
      "Warfury Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 8233,
    "map": "fireavatar",
    "monsters": [
      "Shadefire Colonel"
    ]
  },
  {
    "kind": "kill",
    "questId": 8234,
    "map": "fireavatar",
    "monsters": [
      "Shadefire Major"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8235,
    "map": "fireavatar",
    "ids": [
      8859
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 8236,
    "map": "fireavatar",
    "monsters": [
      "Shadefire Cavalry"
    ]
  },
  {
    "kind": "kill",
    "questId": 8237,
    "map": "fireavatar",
    "monsters": [
      "Shadefire Colonel"
    ]
  },
  {
    "kind": "kill",
    "questId": 8238,
    "map": "fireavatar",
    "monsters": [
      "Elius"
    ]
  },
  {
    "kind": "kill",
    "questId": 8239,
    "map": "fireavatar",
    "monsters": [
      "Living Shadowflame"
    ]
  },
  {
    "kind": "kill",
    "questId": 8240,
    "map": "fireavatar",
    "monsters": [
      "Shadefire Elemental"
    ]
  },
  {
    "kind": "plan",
    "questId": 8241,
    "actions": [
      {
        "kind": "hunt",
        "map": "fireavatar",
        "cell": "r8",
        "pad": "Left",
        "monster": "Shadow Lava",
        "item": "Shadow Lava Defeated",
        "quantity": 8
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 8242,
    "actions": [
      {
        "kind": "hunt",
        "map": "fireavatar",
        "cell": "r7",
        "pad": "Left",
        "monster": "Living Shadowflame",
        "item": "Power Restored",
        "quantity": 10
      }
    ]
  },
  {
    "kind": "kill",
    "questId": 8243,
    "map": "fireavatar",
    "monsters": [
      "Fire Orb",
      "Avatar Tyndarius"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.shadows-of-war.15tyndarius",
    category: "Story",
    map: "darkally",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
