// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Doomwood Paladins Trial",
  "description": "This will finish the Doomwood Paladins Trial quest.",
  "tags": [
    "story",
    "quest",
    "queen-of-monsters",
    "doomwood-paladins-trial",
    "queenof",
    "monsters",
    "2doomwood",
    "paladins",
    "trial"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "plan",
    "questId": 5404,
    "actions": []
  },
  {
    "kind": "plan",
    "questId": 5405,
    "actions": [
      {
        "kind": "hunt",
        "map": "sandsea",
        "monster": "Oasis Monkey",
        "item": "Pally Luwak Beans"
      }
    ]
  },
  {
    "kind": "chain",
    "questId": 5404
  },
  {
    "kind": "kill",
    "questId": 5406,
    "map": "doompally",
    "monsters": [
      "Doomwood Ectomancer"
    ]
  },
  {
    "kind": "kill",
    "questId": 5407,
    "map": "doompally",
    "monsters": [
      "Doomwood Soldier"
    ]
  },
  {
    "kind": "kill",
    "questId": 5408,
    "map": "doompally",
    "monsters": [
      "Doomwood Ectomancer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5409,
    "map": "doompally",
    "ids": [
      4758
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5410,
    "map": "doompally",
    "ids": [
      4759
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 5410,
    "map": "doompally",
    "monsters": [
      "Doomwood Bonemuncher"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5411,
    "map": "doompally",
    "ids": [
      4761
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5411,
    "map": "doompally",
    "ids": [
      4760
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 5412,
    "map": "doompally",
    "monsters": [
      "Doomwood Treeant"
    ]
  },
  {
    "kind": "kill",
    "questId": 5413,
    "map": "doompally",
    "monsters": [
      "Doomwood Ectomancer"
    ]
  },
  {
    "kind": "kill",
    "questId": 5414,
    "map": "doompally",
    "monsters": [
      "Doomwood Bonemuncher"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5415,
    "map": "doompally",
    "ids": [
      4762
    ]
  },
  {
    "kind": "kill",
    "questId": 5416,
    "map": "doompally",
    "monsters": [
      "Skeletal Subjugator"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.queenof-monsters.2doomwood-paladins-trial",
    category: "Story",
    map: "sandsea",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
