// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Shadowfall Darkness Rising",
  "description": "This will finish the Shadowfall Darkness Rising quest.",
  "tags": [
    "story",
    "quest",
    "queen-monsters",
    "shadowfall-darkness-rising",
    "queenof",
    "monsters",
    "4shadowfall",
    "darkness",
    "rising"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "kill",
    "questId": 5487,
    "map": "DarkoviaInvasion",
    "monsters": [
      "Underworld Hound",
      "Infernal Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5488,
    "map": "DarkoviaInvasion",
    "ids": [
      4905
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 5489,
    "map": "DarkoviaInvasion",
    "monsters": [
      "Grievous Fiend"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5490,
    "map": "SafiriaInvasion",
    "ids": [
      4904
    ]
  },
  {
    "kind": "kill",
    "questId": 5491,
    "map": "SafiriaInvasion",
    "monsters": [
      "Fallen Knight",
      "Infernal Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5492,
    "map": "SafiriaInvasion",
    "ids": [
      4895
    ],
    "quantity": 6
  },
  {
    "kind": "mapItem",
    "questId": 5492,
    "map": "SafiriaInvasion",
    "ids": [
      4896
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5493,
    "map": "SafiriaInvasion",
    "ids": [
      4897
    ],
    "quantity": 9
  },
  {
    "kind": "mapItem",
    "questId": 5494,
    "map": "SafiriaInvasion",
    "ids": [
      4898,
      4899
    ]
  },
  {
    "kind": "kill",
    "questId": 5494,
    "map": "SafiriaInvasion",
    "monsters": [
      "Blood Maggot"
    ]
  },
  {
    "kind": "kill",
    "questId": 5495,
    "map": "SafiriaInvasion",
    "monsters": [
      "Ma'alech"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5496,
    "map": "LycanInvasion",
    "ids": [
      4900
    ]
  },
  {
    "kind": "kill",
    "questId": 5497,
    "map": "LycanInvasion",
    "monsters": [
      "Infernal Knight",
      "Fallen Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 5498,
    "map": "LycanInvasion",
    "monsters": [
      "Dire Wolf"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5499,
    "map": "LycanInvasion",
    "ids": [
      4901
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5499,
    "map": "LycanInvasion",
    "ids": [
      4903
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 5500,
    "map": "LycanInvasion",
    "monsters": [
      "Lord Balax'el"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5501,
    "map": "SafiriaInvasion",
    "ids": [
      4902
    ]
  },
  {
    "kind": "kill",
    "questId": 5501,
    "map": "SafiriaInvasion",
    "monsters": [
      "Fallen Knight"
    ]
  },
  {
    "kind": "kill",
    "questId": 5502,
    "map": "SafiriaInvasion",
    "monsters": [
      "Shadow Imp",
      "Revenant"
    ]
  },
  {
    "kind": "kill",
    "questId": 5503,
    "map": "SafiriaInvasion",
    "monsters": [
      "Noddharath"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5543,
    "map": "shadowfallinvasion",
    "ids": [
      5024
    ]
  },
  {
    "kind": "kill",
    "questId": 5544,
    "map": "shadowfallinvasion",
    "monsters": [
      "Infernal Imp",
      "Infernal Knight"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5545,
    "map": "shadowfallinvasion",
    "ids": [
      5025
    ],
    "quantity": 4
  },
  {
    "kind": "mapItem",
    "questId": 5545,
    "map": "shadowfallinvasion",
    "ids": [
      5026
    ],
    "quantity": 4
  },
  {
    "kind": "kill",
    "questId": 5546,
    "map": "shadowfallinvasion",
    "monsters": [
      "Infernal Imp"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5547,
    "map": "shadowfallinvasion",
    "ids": [
      5027
    ],
    "quantity": 5
  },
  {
    "kind": "mapItem",
    "questId": 5548,
    "map": "shadowfallinvasion",
    "ids": [
      5028
    ]
  },
  {
    "kind": "kill",
    "questId": 5549,
    "map": "shadowfallinvasion",
    "monsters": [
      "Bone Creeper"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5550,
    "map": "shadowfallinvasion",
    "ids": [
      5029
    ]
  },
  {
    "kind": "plan",
    "questId": 5551,
    "actions": [
      {
        "kind": "hunt",
        "map": "shadowfallinvasion",
        "monster": "Bone Guardian",
        "item": "Bone Guardian Slain"
      },
      {
        "kind": "hunt",
        "map": "shadowfallinvasion",
        "monster": "Bone Guardian",
        "item": "Soul Fragment Retrievement"
      }
    ]
  },
  {
    "kind": "plan",
    "questId": 5552,
    "actions": [
      {
        "kind": "hunt",
        "map": "shadowfallinvasion",
        "monster": "Nethermage",
        "item": "Nethermage Slain",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "shadowfallinvasion",
        "monster": "Diabolical Scryer",
        "item": "Diabolical Scryer Slain",
        "quantity": 4
      },
      {
        "kind": "hunt",
        "map": "shadowfallinvasion",
        "monster": "Fallen Knight",
        "item": "Fallen Knight Slain",
        "quantity": 4
      }
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5553,
    "map": "shadowfallinvasion",
    "ids": [
      5030
    ],
    "quantity": 9
  },
  {
    "kind": "mapItem",
    "questId": 5554,
    "map": "shadowfallinvasion",
    "ids": [
      5031
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5555,
    "map": "shadowfallinvasion",
    "ids": [
      5032
    ]
  },
  {
    "kind": "kill",
    "questId": 5555,
    "map": "shadowfallinvasion",
    "monsters": [
      "Diabolical Scryer"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 5556,
    "map": "shadowfallinvasion",
    "ids": [
      5033
    ]
  },
  {
    "kind": "kill",
    "questId": 5557,
    "map": "shadowfallinvasion",
    "monsters": [
      "Lord Balax'el"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.queenof-monsters.4shadowfall-darkness-rising",
    category: "Story",
    map: "DarkoviaInvasion",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
