// @generated by scripts/generate-story-scripts.cjs
// Do not edit by hand. Run pnpm stories:generate.

import { defineGeneratedStory, type StoryStep } from "../runner.js";

export const meta = {
  "name": "Genesis Garden",
  "description": "This will finish the Genesis Garden quest.",
  "tags": [
    "story",
    "quest",
    "elegy-of-madness",
    "darkon",
    "genesis-garden",
    "elegyof",
    "madness",
    "8genesis",
    "garden"
  ],
  "version": "0.1.0"
};

const steps: StoryStep[] = [
  {
    "kind": "mapItem",
    "questId": 8630,
    "map": "FirstObservatory",
    "ids": [
      10083
    ]
  },
  {
    "kind": "kill",
    "questId": 8631,
    "map": "FirstObservatory",
    "monsters": [
      "Astra Scorpio"
    ]
  },
  {
    "kind": "kill",
    "questId": 8632,
    "map": "FirstObservatory",
    "monsters": [
      "Astra Leo"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8633,
    "map": "FirstObservatory",
    "ids": [
      10084
    ]
  },
  {
    "kind": "kill",
    "questId": 8633,
    "map": "FirstObservatory",
    "monsters": [
      "Ancient Turret"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8634,
    "map": "FirstObservatory",
    "ids": [
      10085
    ]
  },
  {
    "kind": "kill",
    "questId": 8635,
    "map": "FirstObservatory",
    "monsters": [
      "Ancient Creature"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8636,
    "map": "FirstObservatory",
    "ids": [
      10086,
      10087
    ]
  },
  {
    "kind": "kill",
    "questId": 8637,
    "map": "FirstObservatory",
    "monsters": [
      "Ancient Turret",
      "Ancient Creature"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8638,
    "map": "FirstObservatory",
    "ids": [
      10088,
      10089
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8639,
    "map": "FirstObservatory",
    "ids": [
      10090
    ]
  },
  {
    "kind": "kill",
    "questId": 8640,
    "map": "FirstObservatory",
    "monsters": [
      "Empress’ Finger"
    ]
  },
  {
    "kind": "kill",
    "questId": 8641,
    "map": "FirstObservatory",
    "monsters": [
      "Ancient Creature",
      "Ancient Turret",
      "Empress’ Finger"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8678,
    "map": "genesisgarden",
    "ids": [
      10196
    ],
    "quantity": 6
  },
  {
    "kind": "kill",
    "questId": 8679,
    "map": "genesisgarden",
    "monsters": [
      "Drago's Soldier"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8680,
    "map": "genesisgarden",
    "ids": [
      10197,
      10198,
      10199
    ]
  },
  {
    "kind": "kill",
    "questId": 8681,
    "map": "genesisgarden",
    "monsters": [
      "Drago's Soldier"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8682,
    "map": "genesisgarden",
    "ids": [
      10200,
      10201
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8683,
    "map": "genesisgarden",
    "ids": [
      10202
    ],
    "quantity": 5
  },
  {
    "kind": "kill",
    "questId": 8684,
    "map": "genesisgarden",
    "monsters": [
      "Ancient Creature",
      "Plant Beast"
    ]
  },
  {
    "kind": "mapItem",
    "questId": 8685,
    "map": "genesisgarden",
    "ids": [
      10203
    ]
  },
  {
    "kind": "kill",
    "questId": 8685,
    "map": "genesisgarden",
    "monsters": [
      "Ancient Turret"
    ]
  },
  {
    "kind": "kill",
    "questId": 8686,
    "map": "genesisgarden",
    "monsters": [
      "Undead Humanoid"
    ]
  },
  {
    "kind": "kill",
    "questId": 8687,
    "map": "genesisgarden",
    "monsters": [
      "Ancient Mecha"
    ]
  }
];

export const definition = defineGeneratedStory(
  {
    id: "story.elegyof-madness-darkon.8genesis-garden",
    category: "Story",
    map: "FirstObservatory",
    meta
  },
  steps
);

export const main = definition.run;

export default definition;
